// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"
)

// AgentSecretStoreMock is a mock implementation of thundersvc.AgentSecretStore.
//
//	func TestSomethingThatUsesAgentSecretStore(t *testing.T) {
//
//		// make and configure a mocked thundersvc.AgentSecretStore
//		mockedAgentSecretStore := &AgentSecretStoreMock{
//			DeleteFunc: func(ctx context.Context, secretPath string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, secretPath string) (string, string, error) {
//				panic("mock out the Get method")
//			},
//			StoreFunc: func(ctx context.Context, orgName string, projectName string, envName string, agentName string, clientID string, clientSecret string) (string, error) {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedAgentSecretStore in code that requires thundersvc.AgentSecretStore
//		// and then make assertions.
//
//	}
type AgentSecretStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, secretPath string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, secretPath string) (string, string, error)

	// StoreFunc mocks the Store method.
	StoreFunc func(ctx context.Context, orgName string, projectName string, envName string, agentName string, clientID string, clientSecret string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SecretPath is the secretPath argument value.
			SecretPath string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SecretPath is the secretPath argument value.
			SecretPath string
		}
		// Store holds details about calls to the Store method.
		Store []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// EnvName is the envName argument value.
			EnvName string
			// AgentName is the agentName argument value.
			AgentName string
			// ClientID is the clientID argument value.
			ClientID string
			// ClientSecret is the clientSecret argument value.
			ClientSecret string
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockStore  sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *AgentSecretStoreMock) Delete(ctx context.Context, secretPath string) error {
	if mock.DeleteFunc == nil {
		panic("AgentSecretStoreMock.DeleteFunc: method is nil but AgentSecretStore.Delete was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SecretPath string
	}{
		Ctx:        ctx,
		SecretPath: secretPath,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, secretPath)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAgentSecretStore.DeleteCalls())
func (mock *AgentSecretStoreMock) DeleteCalls() []struct {
	Ctx        context.Context
	SecretPath string
} {
	var calls []struct {
		Ctx        context.Context
		SecretPath string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *AgentSecretStoreMock) Get(ctx context.Context, secretPath string) (string, string, error) {
	if mock.GetFunc == nil {
		panic("AgentSecretStoreMock.GetFunc: method is nil but AgentSecretStore.Get was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SecretPath string
	}{
		Ctx:        ctx,
		SecretPath: secretPath,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, secretPath)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedAgentSecretStore.GetCalls())
func (mock *AgentSecretStoreMock) GetCalls() []struct {
	Ctx        context.Context
	SecretPath string
} {
	var calls []struct {
		Ctx        context.Context
		SecretPath string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Store calls StoreFunc.
func (mock *AgentSecretStoreMock) Store(ctx context.Context, orgName string, projectName string, envName string, agentName string, clientID string, clientSecret string) (string, error) {
	if mock.StoreFunc == nil {
		panic("AgentSecretStoreMock.StoreFunc: method is nil but AgentSecretStore.Store was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OrgName      string
		ProjectName  string
		EnvName      string
		AgentName    string
		ClientID     string
		ClientSecret string
	}{
		Ctx:          ctx,
		OrgName:      orgName,
		ProjectName:  projectName,
		EnvName:      envName,
		AgentName:    agentName,
		ClientID:     clientID,
		ClientSecret: clientSecret,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	return mock.StoreFunc(ctx, orgName, projectName, envName, agentName, clientID, clientSecret)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedAgentSecretStore.StoreCalls())
func (mock *AgentSecretStoreMock) StoreCalls() []struct {
	Ctx          context.Context
	OrgName      string
	ProjectName  string
	EnvName      string
	AgentName    string
	ClientID     string
	ClientSecret string
} {
	var calls []struct {
		Ctx          context.Context
		OrgName      string
		ProjectName  string
		EnvName      string
		AgentName    string
		ClientID     string
		ClientSecret string
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
