// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/clients/thundersvc"
)

// EnvThunderResolverMock is a mock implementation of thundersvc.EnvThunderResolver.
//
//	func TestSomethingThatUsesEnvThunderResolver(t *testing.T) {
//
//		// make and configure a mocked thundersvc.EnvThunderResolver
//		mockedEnvThunderResolver := &EnvThunderResolverMock{
//			ResolveFunc: func(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.ThunderClient, error) {
//				panic("mock out the Resolve method")
//			},
//			ResolveIdentityFunc: func(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.EnvIdentityClient, error) {
//				panic("mock out the ResolveIdentity method")
//			},
//		}
//
//		// use mockedEnvThunderResolver in code that requires thundersvc.EnvThunderResolver
//		// and then make assertions.
//
//	}
type EnvThunderResolverMock struct {
	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.ThunderClient, error)

	// ResolveIdentityFunc mocks the ResolveIdentity method.
	ResolveIdentityFunc func(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.EnvIdentityClient, error)

	// calls tracks calls to the methods.
	calls struct {
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// OrgNamespace is the orgNamespace argument value.
			OrgNamespace string
			// EnvName is the envName argument value.
			EnvName string
		}
		// ResolveIdentity holds details about calls to the ResolveIdentity method.
		ResolveIdentity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// OrgNamespace is the orgNamespace argument value.
			OrgNamespace string
			// EnvName is the envName argument value.
			EnvName string
		}
	}
	lockResolve         sync.RWMutex
	lockResolveIdentity sync.RWMutex
}

// Resolve calls ResolveFunc.
func (mock *EnvThunderResolverMock) Resolve(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.ThunderClient, error) {
	if mock.ResolveFunc == nil {
		panic("EnvThunderResolverMock.ResolveFunc: method is nil but EnvThunderResolver.Resolve was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OuID         string
		OrgNamespace string
		EnvName      string
	}{
		Ctx:          ctx,
		OuID:         ouID,
		OrgNamespace: orgNamespace,
		EnvName:      envName,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(ctx, ouID, orgNamespace, envName)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedEnvThunderResolver.ResolveCalls())
func (mock *EnvThunderResolverMock) ResolveCalls() []struct {
	Ctx          context.Context
	OuID         string
	OrgNamespace string
	EnvName      string
} {
	var calls []struct {
		Ctx          context.Context
		OuID         string
		OrgNamespace string
		EnvName      string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// ResolveIdentity calls ResolveIdentityFunc.
func (mock *EnvThunderResolverMock) ResolveIdentity(ctx context.Context, ouID string, orgNamespace string, envName string) (thundersvc.EnvIdentityClient, error) {
	if mock.ResolveIdentityFunc == nil {
		panic("EnvThunderResolverMock.ResolveIdentityFunc: method is nil but EnvThunderResolver.ResolveIdentity was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OuID         string
		OrgNamespace string
		EnvName      string
	}{
		Ctx:          ctx,
		OuID:         ouID,
		OrgNamespace: orgNamespace,
		EnvName:      envName,
	}
	mock.lockResolveIdentity.Lock()
	mock.calls.ResolveIdentity = append(mock.calls.ResolveIdentity, callInfo)
	mock.lockResolveIdentity.Unlock()
	return mock.ResolveIdentityFunc(ctx, ouID, orgNamespace, envName)
}

// ResolveIdentityCalls gets all the calls that were made to ResolveIdentity.
// Check the length with:
//
//	len(mockedEnvThunderResolver.ResolveIdentityCalls())
func (mock *EnvThunderResolverMock) ResolveIdentityCalls() []struct {
	Ctx          context.Context
	OuID         string
	OrgNamespace string
	EnvName      string
} {
	var calls []struct {
		Ctx          context.Context
		OuID         string
		OrgNamespace string
		EnvName      string
	}
	mock.lockResolveIdentity.RLock()
	calls = mock.calls.ResolveIdentity
	mock.lockResolveIdentity.RUnlock()
	return calls
}
