// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/clients/thundersvc"
)

// EnvIdentityClientMock is a mock implementation of thundersvc.EnvIdentityClient.
//
//	func TestSomethingThatUsesEnvIdentityClient(t *testing.T) {
//
//		// make and configure a mocked thundersvc.EnvIdentityClient
//		mockedEnvIdentityClient := &EnvIdentityClientMock{
//			AddGroupMemberEntriesFunc: func(ctx context.Context, groupID string, members []thundersvc.GroupMember) error {
//				panic("mock out the AddGroupMemberEntries method")
//			},
//			AddGroupMembersFunc: func(ctx context.Context, groupID string, userIDs []string) error {
//				panic("mock out the AddGroupMembers method")
//			},
//			AddRoleAssigneesFunc: func(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error {
//				panic("mock out the AddRoleAssignees method")
//			},
//			AddRolePermissionsFunc: func(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error {
//				panic("mock out the AddRolePermissions method")
//			},
//			CreateGroupFunc: func(ctx context.Context, req thundersvc.CreateGroupRequest) (*thundersvc.ThunderGroup, error) {
//				panic("mock out the CreateGroup method")
//			},
//			CreateRoleFunc: func(ctx context.Context, req thundersvc.CreateRoleRequest) (*thundersvc.ThunderRole, error) {
//				panic("mock out the CreateRole method")
//			},
//			CreateUserFunc: func(ctx context.Context, req thundersvc.CreateUserRequest) (*thundersvc.ThunderUser, error) {
//				panic("mock out the CreateUser method")
//			},
//			DeleteGroupFunc: func(ctx context.Context, groupID string) error {
//				panic("mock out the DeleteGroup method")
//			},
//			DeleteProxyResourceServerFunc: func(ctx context.Context, proxyHandle string) error {
//				panic("mock out the DeleteProxyResourceServer method")
//			},
//			DeleteProxyResourceServerActionFunc: func(ctx context.Context, proxyHandle string, action string) (string, error) {
//				panic("mock out the DeleteProxyResourceServerAction method")
//			},
//			DeleteRoleFunc: func(ctx context.Context, roleID string) error {
//				panic("mock out the DeleteRole method")
//			},
//			DeleteUserFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the DeleteUser method")
//			},
//			EnsureProxyResourceServerFunc: func(ctx context.Context, proxyHandle string, displayName string, actions []string) (string, error) {
//				panic("mock out the EnsureProxyResourceServer method")
//			},
//			GetDefaultOUIDFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the GetDefaultOUID method")
//			},
//			GetGroupFunc: func(ctx context.Context, groupID string) (*thundersvc.ThunderGroup, error) {
//				panic("mock out the GetGroup method")
//			},
//			GetGroupMembersFunc: func(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
//				panic("mock out the GetGroupMembers method")
//			},
//			GetGroupRolesFunc: func(ctx context.Context, groupID string) ([]thundersvc.ThunderRole, error) {
//				panic("mock out the GetGroupRoles method")
//			},
//			GetOUIDByHandleFunc: func(ctx context.Context, handle string) (string, error) {
//				panic("mock out the GetOUIDByHandle method")
//			},
//			GetRoleFunc: func(ctx context.Context, roleID string) (*thundersvc.ThunderRole, error) {
//				panic("mock out the GetRole method")
//			},
//			GetRoleAssignmentsFunc: func(ctx context.Context, roleID string) (*thundersvc.RoleAssignments, error) {
//				panic("mock out the GetRoleAssignments method")
//			},
//			GetUserFunc: func(ctx context.Context, userID string) (*thundersvc.ThunderUser, error) {
//				panic("mock out the GetUser method")
//			},
//			GetUserGroupsFunc: func(ctx context.Context, userID string) ([]thundersvc.ThunderGroup, error) {
//				panic("mock out the GetUserGroups method")
//			},
//			GetUserRolesFunc: func(ctx context.Context, userID string) ([]thundersvc.ThunderRole, error) {
//				panic("mock out the GetUserRoles method")
//			},
//			InviteUserFunc: func(ctx context.Context, email string, ouID string) (string, error) {
//				panic("mock out the InviteUser method")
//			},
//			ListAMPPermissionsFunc: func(ctx context.Context) ([]thundersvc.ThunderPermission, string, error) {
//				panic("mock out the ListAMPPermissions method")
//			},
//			ListChildOUsFunc: func(ctx context.Context, parentOUID string, limit int, offset int) ([]thundersvc.ThunderOU, int, error) {
//				panic("mock out the ListChildOUs method")
//			},
//			ListGroupMemberEntriesFunc: func(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.GroupMember, int, error) {
//				panic("mock out the ListGroupMemberEntries method")
//			},
//			ListGroupsFunc: func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error) {
//				panic("mock out the ListGroups method")
//			},
//			ListGroupsByOUIdFunc: func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error) {
//				panic("mock out the ListGroupsByOUId method")
//			},
//			ListRolesFunc: func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderRole, int, error) {
//				panic("mock out the ListRoles method")
//			},
//			ListUsersFunc: func(ctx context.Context, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
//				panic("mock out the ListUsers method")
//			},
//			ListUsersByOUIdFunc: func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
//				panic("mock out the ListUsersByOUId method")
//			},
//			RemoveGroupMemberEntriesFunc: func(ctx context.Context, groupID string, members []thundersvc.GroupMember) error {
//				panic("mock out the RemoveGroupMemberEntries method")
//			},
//			RemoveGroupMembersFunc: func(ctx context.Context, groupID string, userIDs []string) error {
//				panic("mock out the RemoveGroupMembers method")
//			},
//			RemoveRoleAssigneesFunc: func(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error {
//				panic("mock out the RemoveRoleAssignees method")
//			},
//			RemoveRolePermissionsFunc: func(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error {
//				panic("mock out the RemoveRolePermissions method")
//			},
//			UpdateGroupFunc: func(ctx context.Context, groupID string, req thundersvc.UpdateGroupRequest) (*thundersvc.ThunderGroup, error) {
//				panic("mock out the UpdateGroup method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, roleID string, req thundersvc.UpdateRoleRequest) (*thundersvc.ThunderRole, error) {
//				panic("mock out the UpdateRole method")
//			},
//			UpdateUserFunc: func(ctx context.Context, userID string, req thundersvc.UpdateUserRequest) (*thundersvc.ThunderUser, error) {
//				panic("mock out the UpdateUser method")
//			},
//		}
//
//		// use mockedEnvIdentityClient in code that requires thundersvc.EnvIdentityClient
//		// and then make assertions.
//
//	}
type EnvIdentityClientMock struct {
	// AddGroupMemberEntriesFunc mocks the AddGroupMemberEntries method.
	AddGroupMemberEntriesFunc func(ctx context.Context, groupID string, members []thundersvc.GroupMember) error

	// AddGroupMembersFunc mocks the AddGroupMembers method.
	AddGroupMembersFunc func(ctx context.Context, groupID string, userIDs []string) error

	// AddRoleAssigneesFunc mocks the AddRoleAssignees method.
	AddRoleAssigneesFunc func(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error

	// AddRolePermissionsFunc mocks the AddRolePermissions method.
	AddRolePermissionsFunc func(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error

	// CreateGroupFunc mocks the CreateGroup method.
	CreateGroupFunc func(ctx context.Context, req thundersvc.CreateGroupRequest) (*thundersvc.ThunderGroup, error)

	// CreateRoleFunc mocks the CreateRole method.
	CreateRoleFunc func(ctx context.Context, req thundersvc.CreateRoleRequest) (*thundersvc.ThunderRole, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, req thundersvc.CreateUserRequest) (*thundersvc.ThunderUser, error)

	// DeleteGroupFunc mocks the DeleteGroup method.
	DeleteGroupFunc func(ctx context.Context, groupID string) error

	// DeleteProxyResourceServerFunc mocks the DeleteProxyResourceServer method.
	DeleteProxyResourceServerFunc func(ctx context.Context, proxyHandle string) error

	// DeleteProxyResourceServerActionFunc mocks the DeleteProxyResourceServerAction method.
	DeleteProxyResourceServerActionFunc func(ctx context.Context, proxyHandle string, action string) (string, error)

	// DeleteRoleFunc mocks the DeleteRole method.
	DeleteRoleFunc func(ctx context.Context, roleID string) error

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, userID string) error

	// EnsureProxyResourceServerFunc mocks the EnsureProxyResourceServer method.
	EnsureProxyResourceServerFunc func(ctx context.Context, proxyHandle string, displayName string, actions []string) (string, error)

	// GetDefaultOUIDFunc mocks the GetDefaultOUID method.
	GetDefaultOUIDFunc func(ctx context.Context) (string, error)

	// GetGroupFunc mocks the GetGroup method.
	GetGroupFunc func(ctx context.Context, groupID string) (*thundersvc.ThunderGroup, error)

	// GetGroupMembersFunc mocks the GetGroupMembers method.
	GetGroupMembersFunc func(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error)

	// GetGroupRolesFunc mocks the GetGroupRoles method.
	GetGroupRolesFunc func(ctx context.Context, groupID string) ([]thundersvc.ThunderRole, error)

	// GetOUIDByHandleFunc mocks the GetOUIDByHandle method.
	GetOUIDByHandleFunc func(ctx context.Context, handle string) (string, error)

	// GetRoleFunc mocks the GetRole method.
	GetRoleFunc func(ctx context.Context, roleID string) (*thundersvc.ThunderRole, error)

	// GetRoleAssignmentsFunc mocks the GetRoleAssignments method.
	GetRoleAssignmentsFunc func(ctx context.Context, roleID string) (*thundersvc.RoleAssignments, error)

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(ctx context.Context, userID string) (*thundersvc.ThunderUser, error)

	// GetUserGroupsFunc mocks the GetUserGroups method.
	GetUserGroupsFunc func(ctx context.Context, userID string) ([]thundersvc.ThunderGroup, error)

	// GetUserRolesFunc mocks the GetUserRoles method.
	GetUserRolesFunc func(ctx context.Context, userID string) ([]thundersvc.ThunderRole, error)

	// InviteUserFunc mocks the InviteUser method.
	InviteUserFunc func(ctx context.Context, email string, ouID string) (string, error)

	// ListAMPPermissionsFunc mocks the ListAMPPermissions method.
	ListAMPPermissionsFunc func(ctx context.Context) ([]thundersvc.ThunderPermission, string, error)

	// ListChildOUsFunc mocks the ListChildOUs method.
	ListChildOUsFunc func(ctx context.Context, parentOUID string, limit int, offset int) ([]thundersvc.ThunderOU, int, error)

	// ListGroupMemberEntriesFunc mocks the ListGroupMemberEntries method.
	ListGroupMemberEntriesFunc func(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.GroupMember, int, error)

	// ListGroupsFunc mocks the ListGroups method.
	ListGroupsFunc func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error)

	// ListGroupsByOUIdFunc mocks the ListGroupsByOUId method.
	ListGroupsByOUIdFunc func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error)

	// ListRolesFunc mocks the ListRoles method.
	ListRolesFunc func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderRole, int, error)

	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context, offset int, limit int) ([]thundersvc.ThunderUser, int, error)

	// ListUsersByOUIdFunc mocks the ListUsersByOUId method.
	ListUsersByOUIdFunc func(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error)

	// RemoveGroupMemberEntriesFunc mocks the RemoveGroupMemberEntries method.
	RemoveGroupMemberEntriesFunc func(ctx context.Context, groupID string, members []thundersvc.GroupMember) error

	// RemoveGroupMembersFunc mocks the RemoveGroupMembers method.
	RemoveGroupMembersFunc func(ctx context.Context, groupID string, userIDs []string) error

	// RemoveRoleAssigneesFunc mocks the RemoveRoleAssignees method.
	RemoveRoleAssigneesFunc func(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error

	// RemoveRolePermissionsFunc mocks the RemoveRolePermissions method.
	RemoveRolePermissionsFunc func(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error

	// UpdateGroupFunc mocks the UpdateGroup method.
	UpdateGroupFunc func(ctx context.Context, groupID string, req thundersvc.UpdateGroupRequest) (*thundersvc.ThunderGroup, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, roleID string, req thundersvc.UpdateRoleRequest) (*thundersvc.ThunderRole, error)

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(ctx context.Context, userID string, req thundersvc.UpdateUserRequest) (*thundersvc.ThunderUser, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddGroupMemberEntries holds details about calls to the AddGroupMemberEntries method.
		AddGroupMemberEntries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// Members is the members argument value.
			Members []thundersvc.GroupMember
		}
		// AddGroupMembers holds details about calls to the AddGroupMembers method.
		AddGroupMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// UserIDs is the userIDs argument value.
			UserIDs []string
		}
		// AddRoleAssignees holds details about calls to the AddRoleAssignees method.
		AddRoleAssignees []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
			// Req is the req argument value.
			Req thundersvc.RoleAssignmentsRequest
		}
		// AddRolePermissions holds details about calls to the AddRolePermissions method.
		AddRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
			// Req is the req argument value.
			Req thundersvc.RolePermissionRequest
		}
		// CreateGroup holds details about calls to the CreateGroup method.
		CreateGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req thundersvc.CreateGroupRequest
		}
		// CreateRole holds details about calls to the CreateRole method.
		CreateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req thundersvc.CreateRoleRequest
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req thundersvc.CreateUserRequest
		}
		// DeleteGroup holds details about calls to the DeleteGroup method.
		DeleteGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
		}
		// DeleteProxyResourceServer holds details about calls to the DeleteProxyResourceServer method.
		DeleteProxyResourceServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProxyHandle is the proxyHandle argument value.
			ProxyHandle string
		}
		// DeleteProxyResourceServerAction holds details about calls to the DeleteProxyResourceServerAction method.
		DeleteProxyResourceServerAction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProxyHandle is the proxyHandle argument value.
			ProxyHandle string
			// Action is the action argument value.
			Action string
		}
		// DeleteRole holds details about calls to the DeleteRole method.
		DeleteRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// EnsureProxyResourceServer holds details about calls to the EnsureProxyResourceServer method.
		EnsureProxyResourceServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProxyHandle is the proxyHandle argument value.
			ProxyHandle string
			// DisplayName is the displayName argument value.
			DisplayName string
			// Actions is the actions argument value.
			Actions []string
		}
		// GetDefaultOUID holds details about calls to the GetDefaultOUID method.
		GetDefaultOUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetGroup holds details about calls to the GetGroup method.
		GetGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
		}
		// GetGroupMembers holds details about calls to the GetGroupMembers method.
		GetGroupMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// GetGroupRoles holds details about calls to the GetGroupRoles method.
		GetGroupRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
		}
		// GetOUIDByHandle holds details about calls to the GetOUIDByHandle method.
		GetOUIDByHandle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle string
		}
		// GetRole holds details about calls to the GetRole method.
		GetRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
		}
		// GetRoleAssignments holds details about calls to the GetRoleAssignments method.
		GetRoleAssignments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// GetUserGroups holds details about calls to the GetUserGroups method.
		GetUserGroups []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// GetUserRoles holds details about calls to the GetUserRoles method.
		GetUserRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// InviteUser holds details about calls to the InviteUser method.
		InviteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// OuID is the ouID argument value.
			OuID string
		}
		// ListAMPPermissions holds details about calls to the ListAMPPermissions method.
		ListAMPPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListChildOUs holds details about calls to the ListChildOUs method.
		ListChildOUs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentOUID is the parentOUID argument value.
			ParentOUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListGroupMemberEntries holds details about calls to the ListGroupMemberEntries method.
		ListGroupMemberEntries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// ListGroups holds details about calls to the ListGroups method.
		ListGroups []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// ListGroupsByOUId holds details about calls to the ListGroupsByOUId method.
		ListGroupsByOUId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// ListRoles holds details about calls to the ListRoles method.
		ListRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// ListUsersByOUId holds details about calls to the ListUsersByOUId method.
		ListUsersByOUId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// RemoveGroupMemberEntries holds details about calls to the RemoveGroupMemberEntries method.
		RemoveGroupMemberEntries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// Members is the members argument value.
			Members []thundersvc.GroupMember
		}
		// RemoveGroupMembers holds details about calls to the RemoveGroupMembers method.
		RemoveGroupMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// UserIDs is the userIDs argument value.
			UserIDs []string
		}
		// RemoveRoleAssignees holds details about calls to the RemoveRoleAssignees method.
		RemoveRoleAssignees []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
			// Req is the req argument value.
			Req thundersvc.RoleAssignmentsRequest
		}
		// RemoveRolePermissions holds details about calls to the RemoveRolePermissions method.
		RemoveRolePermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
			// Req is the req argument value.
			Req thundersvc.RolePermissionRequest
		}
		// UpdateGroup holds details about calls to the UpdateGroup method.
		UpdateGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GroupID is the groupID argument value.
			GroupID string
			// Req is the req argument value.
			Req thundersvc.UpdateGroupRequest
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID string
			// Req is the req argument value.
			Req thundersvc.UpdateRoleRequest
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Req is the req argument value.
			Req thundersvc.UpdateUserRequest
		}
	}
	lockAddGroupMemberEntries           sync.RWMutex
	lockAddGroupMembers                 sync.RWMutex
	lockAddRoleAssignees                sync.RWMutex
	lockAddRolePermissions              sync.RWMutex
	lockCreateGroup                     sync.RWMutex
	lockCreateRole                      sync.RWMutex
	lockCreateUser                      sync.RWMutex
	lockDeleteGroup                     sync.RWMutex
	lockDeleteProxyResourceServer       sync.RWMutex
	lockDeleteProxyResourceServerAction sync.RWMutex
	lockDeleteRole                      sync.RWMutex
	lockDeleteUser                      sync.RWMutex
	lockEnsureProxyResourceServer       sync.RWMutex
	lockGetDefaultOUID                  sync.RWMutex
	lockGetGroup                        sync.RWMutex
	lockGetGroupMembers                 sync.RWMutex
	lockGetGroupRoles                   sync.RWMutex
	lockGetOUIDByHandle                 sync.RWMutex
	lockGetRole                         sync.RWMutex
	lockGetRoleAssignments              sync.RWMutex
	lockGetUser                         sync.RWMutex
	lockGetUserGroups                   sync.RWMutex
	lockGetUserRoles                    sync.RWMutex
	lockInviteUser                      sync.RWMutex
	lockListAMPPermissions              sync.RWMutex
	lockListChildOUs                    sync.RWMutex
	lockListGroupMemberEntries          sync.RWMutex
	lockListGroups                      sync.RWMutex
	lockListGroupsByOUId                sync.RWMutex
	lockListRoles                       sync.RWMutex
	lockListUsers                       sync.RWMutex
	lockListUsersByOUId                 sync.RWMutex
	lockRemoveGroupMemberEntries        sync.RWMutex
	lockRemoveGroupMembers              sync.RWMutex
	lockRemoveRoleAssignees             sync.RWMutex
	lockRemoveRolePermissions           sync.RWMutex
	lockUpdateGroup                     sync.RWMutex
	lockUpdateRole                      sync.RWMutex
	lockUpdateUser                      sync.RWMutex
}

// AddGroupMemberEntries calls AddGroupMemberEntriesFunc.
func (mock *EnvIdentityClientMock) AddGroupMemberEntries(ctx context.Context, groupID string, members []thundersvc.GroupMember) error {
	if mock.AddGroupMemberEntriesFunc == nil {
		panic("EnvIdentityClientMock.AddGroupMemberEntriesFunc: method is nil but EnvIdentityClient.AddGroupMemberEntries was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		Members []thundersvc.GroupMember
	}{
		Ctx:     ctx,
		GroupID: groupID,
		Members: members,
	}
	mock.lockAddGroupMemberEntries.Lock()
	mock.calls.AddGroupMemberEntries = append(mock.calls.AddGroupMemberEntries, callInfo)
	mock.lockAddGroupMemberEntries.Unlock()
	return mock.AddGroupMemberEntriesFunc(ctx, groupID, members)
}

// AddGroupMemberEntriesCalls gets all the calls that were made to AddGroupMemberEntries.
// Check the length with:
//
//	len(mockedEnvIdentityClient.AddGroupMemberEntriesCalls())
func (mock *EnvIdentityClientMock) AddGroupMemberEntriesCalls() []struct {
	Ctx     context.Context
	GroupID string
	Members []thundersvc.GroupMember
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		Members []thundersvc.GroupMember
	}
	mock.lockAddGroupMemberEntries.RLock()
	calls = mock.calls.AddGroupMemberEntries
	mock.lockAddGroupMemberEntries.RUnlock()
	return calls
}

// AddGroupMembers calls AddGroupMembersFunc.
func (mock *EnvIdentityClientMock) AddGroupMembers(ctx context.Context, groupID string, userIDs []string) error {
	if mock.AddGroupMembersFunc == nil {
		panic("EnvIdentityClientMock.AddGroupMembersFunc: method is nil but EnvIdentityClient.AddGroupMembers was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		UserIDs []string
	}{
		Ctx:     ctx,
		GroupID: groupID,
		UserIDs: userIDs,
	}
	mock.lockAddGroupMembers.Lock()
	mock.calls.AddGroupMembers = append(mock.calls.AddGroupMembers, callInfo)
	mock.lockAddGroupMembers.Unlock()
	return mock.AddGroupMembersFunc(ctx, groupID, userIDs)
}

// AddGroupMembersCalls gets all the calls that were made to AddGroupMembers.
// Check the length with:
//
//	len(mockedEnvIdentityClient.AddGroupMembersCalls())
func (mock *EnvIdentityClientMock) AddGroupMembersCalls() []struct {
	Ctx     context.Context
	GroupID string
	UserIDs []string
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		UserIDs []string
	}
	mock.lockAddGroupMembers.RLock()
	calls = mock.calls.AddGroupMembers
	mock.lockAddGroupMembers.RUnlock()
	return calls
}

// AddRoleAssignees calls AddRoleAssigneesFunc.
func (mock *EnvIdentityClientMock) AddRoleAssignees(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error {
	if mock.AddRoleAssigneesFunc == nil {
		panic("EnvIdentityClientMock.AddRoleAssigneesFunc: method is nil but EnvIdentityClient.AddRoleAssignees was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RoleAssignmentsRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockAddRoleAssignees.Lock()
	mock.calls.AddRoleAssignees = append(mock.calls.AddRoleAssignees, callInfo)
	mock.lockAddRoleAssignees.Unlock()
	return mock.AddRoleAssigneesFunc(ctx, roleID, req)
}

// AddRoleAssigneesCalls gets all the calls that were made to AddRoleAssignees.
// Check the length with:
//
//	len(mockedEnvIdentityClient.AddRoleAssigneesCalls())
func (mock *EnvIdentityClientMock) AddRoleAssigneesCalls() []struct {
	Ctx    context.Context
	RoleID string
	Req    thundersvc.RoleAssignmentsRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RoleAssignmentsRequest
	}
	mock.lockAddRoleAssignees.RLock()
	calls = mock.calls.AddRoleAssignees
	mock.lockAddRoleAssignees.RUnlock()
	return calls
}

// AddRolePermissions calls AddRolePermissionsFunc.
func (mock *EnvIdentityClientMock) AddRolePermissions(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error {
	if mock.AddRolePermissionsFunc == nil {
		panic("EnvIdentityClientMock.AddRolePermissionsFunc: method is nil but EnvIdentityClient.AddRolePermissions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RolePermissionRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockAddRolePermissions.Lock()
	mock.calls.AddRolePermissions = append(mock.calls.AddRolePermissions, callInfo)
	mock.lockAddRolePermissions.Unlock()
	return mock.AddRolePermissionsFunc(ctx, roleID, req)
}

// AddRolePermissionsCalls gets all the calls that were made to AddRolePermissions.
// Check the length with:
//
//	len(mockedEnvIdentityClient.AddRolePermissionsCalls())
func (mock *EnvIdentityClientMock) AddRolePermissionsCalls() []struct {
	Ctx    context.Context
	RoleID string
	Req    thundersvc.RolePermissionRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RolePermissionRequest
	}
	mock.lockAddRolePermissions.RLock()
	calls = mock.calls.AddRolePermissions
	mock.lockAddRolePermissions.RUnlock()
	return calls
}

// CreateGroup calls CreateGroupFunc.
func (mock *EnvIdentityClientMock) CreateGroup(ctx context.Context, req thundersvc.CreateGroupRequest) (*thundersvc.ThunderGroup, error) {
	if mock.CreateGroupFunc == nil {
		panic("EnvIdentityClientMock.CreateGroupFunc: method is nil but EnvIdentityClient.CreateGroup was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req thundersvc.CreateGroupRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateGroup.Lock()
	mock.calls.CreateGroup = append(mock.calls.CreateGroup, callInfo)
	mock.lockCreateGroup.Unlock()
	return mock.CreateGroupFunc(ctx, req)
}

// CreateGroupCalls gets all the calls that were made to CreateGroup.
// Check the length with:
//
//	len(mockedEnvIdentityClient.CreateGroupCalls())
func (mock *EnvIdentityClientMock) CreateGroupCalls() []struct {
	Ctx context.Context
	Req thundersvc.CreateGroupRequest
} {
	var calls []struct {
		Ctx context.Context
		Req thundersvc.CreateGroupRequest
	}
	mock.lockCreateGroup.RLock()
	calls = mock.calls.CreateGroup
	mock.lockCreateGroup.RUnlock()
	return calls
}

// CreateRole calls CreateRoleFunc.
func (mock *EnvIdentityClientMock) CreateRole(ctx context.Context, req thundersvc.CreateRoleRequest) (*thundersvc.ThunderRole, error) {
	if mock.CreateRoleFunc == nil {
		panic("EnvIdentityClientMock.CreateRoleFunc: method is nil but EnvIdentityClient.CreateRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req thundersvc.CreateRoleRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateRole.Lock()
	mock.calls.CreateRole = append(mock.calls.CreateRole, callInfo)
	mock.lockCreateRole.Unlock()
	return mock.CreateRoleFunc(ctx, req)
}

// CreateRoleCalls gets all the calls that were made to CreateRole.
// Check the length with:
//
//	len(mockedEnvIdentityClient.CreateRoleCalls())
func (mock *EnvIdentityClientMock) CreateRoleCalls() []struct {
	Ctx context.Context
	Req thundersvc.CreateRoleRequest
} {
	var calls []struct {
		Ctx context.Context
		Req thundersvc.CreateRoleRequest
	}
	mock.lockCreateRole.RLock()
	calls = mock.calls.CreateRole
	mock.lockCreateRole.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *EnvIdentityClientMock) CreateUser(ctx context.Context, req thundersvc.CreateUserRequest) (*thundersvc.ThunderUser, error) {
	if mock.CreateUserFunc == nil {
		panic("EnvIdentityClientMock.CreateUserFunc: method is nil but EnvIdentityClient.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req thundersvc.CreateUserRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, req)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedEnvIdentityClient.CreateUserCalls())
func (mock *EnvIdentityClientMock) CreateUserCalls() []struct {
	Ctx context.Context
	Req thundersvc.CreateUserRequest
} {
	var calls []struct {
		Ctx context.Context
		Req thundersvc.CreateUserRequest
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// DeleteGroup calls DeleteGroupFunc.
func (mock *EnvIdentityClientMock) DeleteGroup(ctx context.Context, groupID string) error {
	if mock.DeleteGroupFunc == nil {
		panic("EnvIdentityClientMock.DeleteGroupFunc: method is nil but EnvIdentityClient.DeleteGroup was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
	}{
		Ctx:     ctx,
		GroupID: groupID,
	}
	mock.lockDeleteGroup.Lock()
	mock.calls.DeleteGroup = append(mock.calls.DeleteGroup, callInfo)
	mock.lockDeleteGroup.Unlock()
	return mock.DeleteGroupFunc(ctx, groupID)
}

// DeleteGroupCalls gets all the calls that were made to DeleteGroup.
// Check the length with:
//
//	len(mockedEnvIdentityClient.DeleteGroupCalls())
func (mock *EnvIdentityClientMock) DeleteGroupCalls() []struct {
	Ctx     context.Context
	GroupID string
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
	}
	mock.lockDeleteGroup.RLock()
	calls = mock.calls.DeleteGroup
	mock.lockDeleteGroup.RUnlock()
	return calls
}

// DeleteProxyResourceServer calls DeleteProxyResourceServerFunc.
func (mock *EnvIdentityClientMock) DeleteProxyResourceServer(ctx context.Context, proxyHandle string) error {
	if mock.DeleteProxyResourceServerFunc == nil {
		panic("EnvIdentityClientMock.DeleteProxyResourceServerFunc: method is nil but EnvIdentityClient.DeleteProxyResourceServer was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ProxyHandle string
	}{
		Ctx:         ctx,
		ProxyHandle: proxyHandle,
	}
	mock.lockDeleteProxyResourceServer.Lock()
	mock.calls.DeleteProxyResourceServer = append(mock.calls.DeleteProxyResourceServer, callInfo)
	mock.lockDeleteProxyResourceServer.Unlock()
	return mock.DeleteProxyResourceServerFunc(ctx, proxyHandle)
}

// DeleteProxyResourceServerCalls gets all the calls that were made to DeleteProxyResourceServer.
// Check the length with:
//
//	len(mockedEnvIdentityClient.DeleteProxyResourceServerCalls())
func (mock *EnvIdentityClientMock) DeleteProxyResourceServerCalls() []struct {
	Ctx         context.Context
	ProxyHandle string
} {
	var calls []struct {
		Ctx         context.Context
		ProxyHandle string
	}
	mock.lockDeleteProxyResourceServer.RLock()
	calls = mock.calls.DeleteProxyResourceServer
	mock.lockDeleteProxyResourceServer.RUnlock()
	return calls
}

// DeleteProxyResourceServerAction calls DeleteProxyResourceServerActionFunc.
func (mock *EnvIdentityClientMock) DeleteProxyResourceServerAction(ctx context.Context, proxyHandle string, action string) (string, error) {
	if mock.DeleteProxyResourceServerActionFunc == nil {
		panic("EnvIdentityClientMock.DeleteProxyResourceServerActionFunc: method is nil but EnvIdentityClient.DeleteProxyResourceServerAction was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ProxyHandle string
		Action      string
	}{
		Ctx:         ctx,
		ProxyHandle: proxyHandle,
		Action:      action,
	}
	mock.lockDeleteProxyResourceServerAction.Lock()
	mock.calls.DeleteProxyResourceServerAction = append(mock.calls.DeleteProxyResourceServerAction, callInfo)
	mock.lockDeleteProxyResourceServerAction.Unlock()
	return mock.DeleteProxyResourceServerActionFunc(ctx, proxyHandle, action)
}

// DeleteProxyResourceServerActionCalls gets all the calls that were made to DeleteProxyResourceServerAction.
// Check the length with:
//
//	len(mockedEnvIdentityClient.DeleteProxyResourceServerActionCalls())
func (mock *EnvIdentityClientMock) DeleteProxyResourceServerActionCalls() []struct {
	Ctx         context.Context
	ProxyHandle string
	Action      string
} {
	var calls []struct {
		Ctx         context.Context
		ProxyHandle string
		Action      string
	}
	mock.lockDeleteProxyResourceServerAction.RLock()
	calls = mock.calls.DeleteProxyResourceServerAction
	mock.lockDeleteProxyResourceServerAction.RUnlock()
	return calls
}

// DeleteRole calls DeleteRoleFunc.
func (mock *EnvIdentityClientMock) DeleteRole(ctx context.Context, roleID string) error {
	if mock.DeleteRoleFunc == nil {
		panic("EnvIdentityClientMock.DeleteRoleFunc: method is nil but EnvIdentityClient.DeleteRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockDeleteRole.Lock()
	mock.calls.DeleteRole = append(mock.calls.DeleteRole, callInfo)
	mock.lockDeleteRole.Unlock()
	return mock.DeleteRoleFunc(ctx, roleID)
}

// DeleteRoleCalls gets all the calls that were made to DeleteRole.
// Check the length with:
//
//	len(mockedEnvIdentityClient.DeleteRoleCalls())
func (mock *EnvIdentityClientMock) DeleteRoleCalls() []struct {
	Ctx    context.Context
	RoleID string
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
	}
	mock.lockDeleteRole.RLock()
	calls = mock.calls.DeleteRole
	mock.lockDeleteRole.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *EnvIdentityClientMock) DeleteUser(ctx context.Context, userID string) error {
	if mock.DeleteUserFunc == nil {
		panic("EnvIdentityClientMock.DeleteUserFunc: method is nil but EnvIdentityClient.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, userID)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedEnvIdentityClient.DeleteUserCalls())
func (mock *EnvIdentityClientMock) DeleteUserCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// EnsureProxyResourceServer calls EnsureProxyResourceServerFunc.
func (mock *EnvIdentityClientMock) EnsureProxyResourceServer(ctx context.Context, proxyHandle string, displayName string, actions []string) (string, error) {
	if mock.EnsureProxyResourceServerFunc == nil {
		panic("EnvIdentityClientMock.EnsureProxyResourceServerFunc: method is nil but EnvIdentityClient.EnsureProxyResourceServer was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ProxyHandle string
		DisplayName string
		Actions     []string
	}{
		Ctx:         ctx,
		ProxyHandle: proxyHandle,
		DisplayName: displayName,
		Actions:     actions,
	}
	mock.lockEnsureProxyResourceServer.Lock()
	mock.calls.EnsureProxyResourceServer = append(mock.calls.EnsureProxyResourceServer, callInfo)
	mock.lockEnsureProxyResourceServer.Unlock()
	return mock.EnsureProxyResourceServerFunc(ctx, proxyHandle, displayName, actions)
}

// EnsureProxyResourceServerCalls gets all the calls that were made to EnsureProxyResourceServer.
// Check the length with:
//
//	len(mockedEnvIdentityClient.EnsureProxyResourceServerCalls())
func (mock *EnvIdentityClientMock) EnsureProxyResourceServerCalls() []struct {
	Ctx         context.Context
	ProxyHandle string
	DisplayName string
	Actions     []string
} {
	var calls []struct {
		Ctx         context.Context
		ProxyHandle string
		DisplayName string
		Actions     []string
	}
	mock.lockEnsureProxyResourceServer.RLock()
	calls = mock.calls.EnsureProxyResourceServer
	mock.lockEnsureProxyResourceServer.RUnlock()
	return calls
}

// GetDefaultOUID calls GetDefaultOUIDFunc.
func (mock *EnvIdentityClientMock) GetDefaultOUID(ctx context.Context) (string, error) {
	if mock.GetDefaultOUIDFunc == nil {
		panic("EnvIdentityClientMock.GetDefaultOUIDFunc: method is nil but EnvIdentityClient.GetDefaultOUID was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDefaultOUID.Lock()
	mock.calls.GetDefaultOUID = append(mock.calls.GetDefaultOUID, callInfo)
	mock.lockGetDefaultOUID.Unlock()
	return mock.GetDefaultOUIDFunc(ctx)
}

// GetDefaultOUIDCalls gets all the calls that were made to GetDefaultOUID.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetDefaultOUIDCalls())
func (mock *EnvIdentityClientMock) GetDefaultOUIDCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDefaultOUID.RLock()
	calls = mock.calls.GetDefaultOUID
	mock.lockGetDefaultOUID.RUnlock()
	return calls
}

// GetGroup calls GetGroupFunc.
func (mock *EnvIdentityClientMock) GetGroup(ctx context.Context, groupID string) (*thundersvc.ThunderGroup, error) {
	if mock.GetGroupFunc == nil {
		panic("EnvIdentityClientMock.GetGroupFunc: method is nil but EnvIdentityClient.GetGroup was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
	}{
		Ctx:     ctx,
		GroupID: groupID,
	}
	mock.lockGetGroup.Lock()
	mock.calls.GetGroup = append(mock.calls.GetGroup, callInfo)
	mock.lockGetGroup.Unlock()
	return mock.GetGroupFunc(ctx, groupID)
}

// GetGroupCalls gets all the calls that were made to GetGroup.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetGroupCalls())
func (mock *EnvIdentityClientMock) GetGroupCalls() []struct {
	Ctx     context.Context
	GroupID string
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
	}
	mock.lockGetGroup.RLock()
	calls = mock.calls.GetGroup
	mock.lockGetGroup.RUnlock()
	return calls
}

// GetGroupMembers calls GetGroupMembersFunc.
func (mock *EnvIdentityClientMock) GetGroupMembers(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
	if mock.GetGroupMembersFunc == nil {
		panic("EnvIdentityClientMock.GetGroupMembersFunc: method is nil but EnvIdentityClient.GetGroupMembers was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		Offset  int
		Limit   int
	}{
		Ctx:     ctx,
		GroupID: groupID,
		Offset:  offset,
		Limit:   limit,
	}
	mock.lockGetGroupMembers.Lock()
	mock.calls.GetGroupMembers = append(mock.calls.GetGroupMembers, callInfo)
	mock.lockGetGroupMembers.Unlock()
	return mock.GetGroupMembersFunc(ctx, groupID, offset, limit)
}

// GetGroupMembersCalls gets all the calls that were made to GetGroupMembers.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetGroupMembersCalls())
func (mock *EnvIdentityClientMock) GetGroupMembersCalls() []struct {
	Ctx     context.Context
	GroupID string
	Offset  int
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		Offset  int
		Limit   int
	}
	mock.lockGetGroupMembers.RLock()
	calls = mock.calls.GetGroupMembers
	mock.lockGetGroupMembers.RUnlock()
	return calls
}

// GetGroupRoles calls GetGroupRolesFunc.
func (mock *EnvIdentityClientMock) GetGroupRoles(ctx context.Context, groupID string) ([]thundersvc.ThunderRole, error) {
	if mock.GetGroupRolesFunc == nil {
		panic("EnvIdentityClientMock.GetGroupRolesFunc: method is nil but EnvIdentityClient.GetGroupRoles was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
	}{
		Ctx:     ctx,
		GroupID: groupID,
	}
	mock.lockGetGroupRoles.Lock()
	mock.calls.GetGroupRoles = append(mock.calls.GetGroupRoles, callInfo)
	mock.lockGetGroupRoles.Unlock()
	return mock.GetGroupRolesFunc(ctx, groupID)
}

// GetGroupRolesCalls gets all the calls that were made to GetGroupRoles.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetGroupRolesCalls())
func (mock *EnvIdentityClientMock) GetGroupRolesCalls() []struct {
	Ctx     context.Context
	GroupID string
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
	}
	mock.lockGetGroupRoles.RLock()
	calls = mock.calls.GetGroupRoles
	mock.lockGetGroupRoles.RUnlock()
	return calls
}

// GetOUIDByHandle calls GetOUIDByHandleFunc.
func (mock *EnvIdentityClientMock) GetOUIDByHandle(ctx context.Context, handle string) (string, error) {
	if mock.GetOUIDByHandleFunc == nil {
		panic("EnvIdentityClientMock.GetOUIDByHandleFunc: method is nil but EnvIdentityClient.GetOUIDByHandle was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Handle string
	}{
		Ctx:    ctx,
		Handle: handle,
	}
	mock.lockGetOUIDByHandle.Lock()
	mock.calls.GetOUIDByHandle = append(mock.calls.GetOUIDByHandle, callInfo)
	mock.lockGetOUIDByHandle.Unlock()
	return mock.GetOUIDByHandleFunc(ctx, handle)
}

// GetOUIDByHandleCalls gets all the calls that were made to GetOUIDByHandle.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetOUIDByHandleCalls())
func (mock *EnvIdentityClientMock) GetOUIDByHandleCalls() []struct {
	Ctx    context.Context
	Handle string
} {
	var calls []struct {
		Ctx    context.Context
		Handle string
	}
	mock.lockGetOUIDByHandle.RLock()
	calls = mock.calls.GetOUIDByHandle
	mock.lockGetOUIDByHandle.RUnlock()
	return calls
}

// GetRole calls GetRoleFunc.
func (mock *EnvIdentityClientMock) GetRole(ctx context.Context, roleID string) (*thundersvc.ThunderRole, error) {
	if mock.GetRoleFunc == nil {
		panic("EnvIdentityClientMock.GetRoleFunc: method is nil but EnvIdentityClient.GetRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockGetRole.Lock()
	mock.calls.GetRole = append(mock.calls.GetRole, callInfo)
	mock.lockGetRole.Unlock()
	return mock.GetRoleFunc(ctx, roleID)
}

// GetRoleCalls gets all the calls that were made to GetRole.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetRoleCalls())
func (mock *EnvIdentityClientMock) GetRoleCalls() []struct {
	Ctx    context.Context
	RoleID string
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
	}
	mock.lockGetRole.RLock()
	calls = mock.calls.GetRole
	mock.lockGetRole.RUnlock()
	return calls
}

// GetRoleAssignments calls GetRoleAssignmentsFunc.
func (mock *EnvIdentityClientMock) GetRoleAssignments(ctx context.Context, roleID string) (*thundersvc.RoleAssignments, error) {
	if mock.GetRoleAssignmentsFunc == nil {
		panic("EnvIdentityClientMock.GetRoleAssignmentsFunc: method is nil but EnvIdentityClient.GetRoleAssignments was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockGetRoleAssignments.Lock()
	mock.calls.GetRoleAssignments = append(mock.calls.GetRoleAssignments, callInfo)
	mock.lockGetRoleAssignments.Unlock()
	return mock.GetRoleAssignmentsFunc(ctx, roleID)
}

// GetRoleAssignmentsCalls gets all the calls that were made to GetRoleAssignments.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetRoleAssignmentsCalls())
func (mock *EnvIdentityClientMock) GetRoleAssignmentsCalls() []struct {
	Ctx    context.Context
	RoleID string
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
	}
	mock.lockGetRoleAssignments.RLock()
	calls = mock.calls.GetRoleAssignments
	mock.lockGetRoleAssignments.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *EnvIdentityClientMock) GetUser(ctx context.Context, userID string) (*thundersvc.ThunderUser, error) {
	if mock.GetUserFunc == nil {
		panic("EnvIdentityClientMock.GetUserFunc: method is nil but EnvIdentityClient.GetUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(ctx, userID)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetUserCalls())
func (mock *EnvIdentityClientMock) GetUserCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// GetUserGroups calls GetUserGroupsFunc.
func (mock *EnvIdentityClientMock) GetUserGroups(ctx context.Context, userID string) ([]thundersvc.ThunderGroup, error) {
	if mock.GetUserGroupsFunc == nil {
		panic("EnvIdentityClientMock.GetUserGroupsFunc: method is nil but EnvIdentityClient.GetUserGroups was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserGroups.Lock()
	mock.calls.GetUserGroups = append(mock.calls.GetUserGroups, callInfo)
	mock.lockGetUserGroups.Unlock()
	return mock.GetUserGroupsFunc(ctx, userID)
}

// GetUserGroupsCalls gets all the calls that were made to GetUserGroups.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetUserGroupsCalls())
func (mock *EnvIdentityClientMock) GetUserGroupsCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGetUserGroups.RLock()
	calls = mock.calls.GetUserGroups
	mock.lockGetUserGroups.RUnlock()
	return calls
}

// GetUserRoles calls GetUserRolesFunc.
func (mock *EnvIdentityClientMock) GetUserRoles(ctx context.Context, userID string) ([]thundersvc.ThunderRole, error) {
	if mock.GetUserRolesFunc == nil {
		panic("EnvIdentityClientMock.GetUserRolesFunc: method is nil but EnvIdentityClient.GetUserRoles was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserRoles.Lock()
	mock.calls.GetUserRoles = append(mock.calls.GetUserRoles, callInfo)
	mock.lockGetUserRoles.Unlock()
	return mock.GetUserRolesFunc(ctx, userID)
}

// GetUserRolesCalls gets all the calls that were made to GetUserRoles.
// Check the length with:
//
//	len(mockedEnvIdentityClient.GetUserRolesCalls())
func (mock *EnvIdentityClientMock) GetUserRolesCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGetUserRoles.RLock()
	calls = mock.calls.GetUserRoles
	mock.lockGetUserRoles.RUnlock()
	return calls
}

// InviteUser calls InviteUserFunc.
func (mock *EnvIdentityClientMock) InviteUser(ctx context.Context, email string, ouID string) (string, error) {
	if mock.InviteUserFunc == nil {
		panic("EnvIdentityClientMock.InviteUserFunc: method is nil but EnvIdentityClient.InviteUser was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
		OuID  string
	}{
		Ctx:   ctx,
		Email: email,
		OuID:  ouID,
	}
	mock.lockInviteUser.Lock()
	mock.calls.InviteUser = append(mock.calls.InviteUser, callInfo)
	mock.lockInviteUser.Unlock()
	return mock.InviteUserFunc(ctx, email, ouID)
}

// InviteUserCalls gets all the calls that were made to InviteUser.
// Check the length with:
//
//	len(mockedEnvIdentityClient.InviteUserCalls())
func (mock *EnvIdentityClientMock) InviteUserCalls() []struct {
	Ctx   context.Context
	Email string
	OuID  string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
		OuID  string
	}
	mock.lockInviteUser.RLock()
	calls = mock.calls.InviteUser
	mock.lockInviteUser.RUnlock()
	return calls
}

// ListAMPPermissions calls ListAMPPermissionsFunc.
func (mock *EnvIdentityClientMock) ListAMPPermissions(ctx context.Context) ([]thundersvc.ThunderPermission, string, error) {
	if mock.ListAMPPermissionsFunc == nil {
		panic("EnvIdentityClientMock.ListAMPPermissionsFunc: method is nil but EnvIdentityClient.ListAMPPermissions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAMPPermissions.Lock()
	mock.calls.ListAMPPermissions = append(mock.calls.ListAMPPermissions, callInfo)
	mock.lockListAMPPermissions.Unlock()
	return mock.ListAMPPermissionsFunc(ctx)
}

// ListAMPPermissionsCalls gets all the calls that were made to ListAMPPermissions.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListAMPPermissionsCalls())
func (mock *EnvIdentityClientMock) ListAMPPermissionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAMPPermissions.RLock()
	calls = mock.calls.ListAMPPermissions
	mock.lockListAMPPermissions.RUnlock()
	return calls
}

// ListChildOUs calls ListChildOUsFunc.
func (mock *EnvIdentityClientMock) ListChildOUs(ctx context.Context, parentOUID string, limit int, offset int) ([]thundersvc.ThunderOU, int, error) {
	if mock.ListChildOUsFunc == nil {
		panic("EnvIdentityClientMock.ListChildOUsFunc: method is nil but EnvIdentityClient.ListChildOUs was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ParentOUID string
		Limit      int
		Offset     int
	}{
		Ctx:        ctx,
		ParentOUID: parentOUID,
		Limit:      limit,
		Offset:     offset,
	}
	mock.lockListChildOUs.Lock()
	mock.calls.ListChildOUs = append(mock.calls.ListChildOUs, callInfo)
	mock.lockListChildOUs.Unlock()
	return mock.ListChildOUsFunc(ctx, parentOUID, limit, offset)
}

// ListChildOUsCalls gets all the calls that were made to ListChildOUs.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListChildOUsCalls())
func (mock *EnvIdentityClientMock) ListChildOUsCalls() []struct {
	Ctx        context.Context
	ParentOUID string
	Limit      int
	Offset     int
} {
	var calls []struct {
		Ctx        context.Context
		ParentOUID string
		Limit      int
		Offset     int
	}
	mock.lockListChildOUs.RLock()
	calls = mock.calls.ListChildOUs
	mock.lockListChildOUs.RUnlock()
	return calls
}

// ListGroupMemberEntries calls ListGroupMemberEntriesFunc.
func (mock *EnvIdentityClientMock) ListGroupMemberEntries(ctx context.Context, groupID string, offset int, limit int) ([]thundersvc.GroupMember, int, error) {
	if mock.ListGroupMemberEntriesFunc == nil {
		panic("EnvIdentityClientMock.ListGroupMemberEntriesFunc: method is nil but EnvIdentityClient.ListGroupMemberEntries was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		Offset  int
		Limit   int
	}{
		Ctx:     ctx,
		GroupID: groupID,
		Offset:  offset,
		Limit:   limit,
	}
	mock.lockListGroupMemberEntries.Lock()
	mock.calls.ListGroupMemberEntries = append(mock.calls.ListGroupMemberEntries, callInfo)
	mock.lockListGroupMemberEntries.Unlock()
	return mock.ListGroupMemberEntriesFunc(ctx, groupID, offset, limit)
}

// ListGroupMemberEntriesCalls gets all the calls that were made to ListGroupMemberEntries.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListGroupMemberEntriesCalls())
func (mock *EnvIdentityClientMock) ListGroupMemberEntriesCalls() []struct {
	Ctx     context.Context
	GroupID string
	Offset  int
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		Offset  int
		Limit   int
	}
	mock.lockListGroupMemberEntries.RLock()
	calls = mock.calls.ListGroupMemberEntries
	mock.lockListGroupMemberEntries.RUnlock()
	return calls
}

// ListGroups calls ListGroupsFunc.
func (mock *EnvIdentityClientMock) ListGroups(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error) {
	if mock.ListGroupsFunc == nil {
		panic("EnvIdentityClientMock.ListGroupsFunc: method is nil but EnvIdentityClient.ListGroups was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		OuID:   ouID,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListGroups.Lock()
	mock.calls.ListGroups = append(mock.calls.ListGroups, callInfo)
	mock.lockListGroups.Unlock()
	return mock.ListGroupsFunc(ctx, ouID, offset, limit)
}

// ListGroupsCalls gets all the calls that were made to ListGroups.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListGroupsCalls())
func (mock *EnvIdentityClientMock) ListGroupsCalls() []struct {
	Ctx    context.Context
	OuID   string
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}
	mock.lockListGroups.RLock()
	calls = mock.calls.ListGroups
	mock.lockListGroups.RUnlock()
	return calls
}

// ListGroupsByOUId calls ListGroupsByOUIdFunc.
func (mock *EnvIdentityClientMock) ListGroupsByOUId(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderGroup, int, error) {
	if mock.ListGroupsByOUIdFunc == nil {
		panic("EnvIdentityClientMock.ListGroupsByOUIdFunc: method is nil but EnvIdentityClient.ListGroupsByOUId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		OuID:   ouID,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListGroupsByOUId.Lock()
	mock.calls.ListGroupsByOUId = append(mock.calls.ListGroupsByOUId, callInfo)
	mock.lockListGroupsByOUId.Unlock()
	return mock.ListGroupsByOUIdFunc(ctx, ouID, offset, limit)
}

// ListGroupsByOUIdCalls gets all the calls that were made to ListGroupsByOUId.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListGroupsByOUIdCalls())
func (mock *EnvIdentityClientMock) ListGroupsByOUIdCalls() []struct {
	Ctx    context.Context
	OuID   string
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}
	mock.lockListGroupsByOUId.RLock()
	calls = mock.calls.ListGroupsByOUId
	mock.lockListGroupsByOUId.RUnlock()
	return calls
}

// ListRoles calls ListRolesFunc.
func (mock *EnvIdentityClientMock) ListRoles(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderRole, int, error) {
	if mock.ListRolesFunc == nil {
		panic("EnvIdentityClientMock.ListRolesFunc: method is nil but EnvIdentityClient.ListRoles was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		OuID:   ouID,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = append(mock.calls.ListRoles, callInfo)
	mock.lockListRoles.Unlock()
	return mock.ListRolesFunc(ctx, ouID, offset, limit)
}

// ListRolesCalls gets all the calls that were made to ListRoles.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListRolesCalls())
func (mock *EnvIdentityClientMock) ListRolesCalls() []struct {
	Ctx    context.Context
	OuID   string
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}
	mock.lockListRoles.RLock()
	calls = mock.calls.ListRoles
	mock.lockListRoles.RUnlock()
	return calls
}

// ListUsers calls ListUsersFunc.
func (mock *EnvIdentityClientMock) ListUsers(ctx context.Context, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
	if mock.ListUsersFunc == nil {
		panic("EnvIdentityClientMock.ListUsersFunc: method is nil but EnvIdentityClient.ListUsers was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx, offset, limit)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListUsersCalls())
func (mock *EnvIdentityClientMock) ListUsersCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// ListUsersByOUId calls ListUsersByOUIdFunc.
func (mock *EnvIdentityClientMock) ListUsersByOUId(ctx context.Context, ouID string, offset int, limit int) ([]thundersvc.ThunderUser, int, error) {
	if mock.ListUsersByOUIdFunc == nil {
		panic("EnvIdentityClientMock.ListUsersByOUIdFunc: method is nil but EnvIdentityClient.ListUsersByOUId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		OuID:   ouID,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListUsersByOUId.Lock()
	mock.calls.ListUsersByOUId = append(mock.calls.ListUsersByOUId, callInfo)
	mock.lockListUsersByOUId.Unlock()
	return mock.ListUsersByOUIdFunc(ctx, ouID, offset, limit)
}

// ListUsersByOUIdCalls gets all the calls that were made to ListUsersByOUId.
// Check the length with:
//
//	len(mockedEnvIdentityClient.ListUsersByOUIdCalls())
func (mock *EnvIdentityClientMock) ListUsersByOUIdCalls() []struct {
	Ctx    context.Context
	OuID   string
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		OuID   string
		Offset int
		Limit  int
	}
	mock.lockListUsersByOUId.RLock()
	calls = mock.calls.ListUsersByOUId
	mock.lockListUsersByOUId.RUnlock()
	return calls
}

// RemoveGroupMemberEntries calls RemoveGroupMemberEntriesFunc.
func (mock *EnvIdentityClientMock) RemoveGroupMemberEntries(ctx context.Context, groupID string, members []thundersvc.GroupMember) error {
	if mock.RemoveGroupMemberEntriesFunc == nil {
		panic("EnvIdentityClientMock.RemoveGroupMemberEntriesFunc: method is nil but EnvIdentityClient.RemoveGroupMemberEntries was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		Members []thundersvc.GroupMember
	}{
		Ctx:     ctx,
		GroupID: groupID,
		Members: members,
	}
	mock.lockRemoveGroupMemberEntries.Lock()
	mock.calls.RemoveGroupMemberEntries = append(mock.calls.RemoveGroupMemberEntries, callInfo)
	mock.lockRemoveGroupMemberEntries.Unlock()
	return mock.RemoveGroupMemberEntriesFunc(ctx, groupID, members)
}

// RemoveGroupMemberEntriesCalls gets all the calls that were made to RemoveGroupMemberEntries.
// Check the length with:
//
//	len(mockedEnvIdentityClient.RemoveGroupMemberEntriesCalls())
func (mock *EnvIdentityClientMock) RemoveGroupMemberEntriesCalls() []struct {
	Ctx     context.Context
	GroupID string
	Members []thundersvc.GroupMember
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		Members []thundersvc.GroupMember
	}
	mock.lockRemoveGroupMemberEntries.RLock()
	calls = mock.calls.RemoveGroupMemberEntries
	mock.lockRemoveGroupMemberEntries.RUnlock()
	return calls
}

// RemoveGroupMembers calls RemoveGroupMembersFunc.
func (mock *EnvIdentityClientMock) RemoveGroupMembers(ctx context.Context, groupID string, userIDs []string) error {
	if mock.RemoveGroupMembersFunc == nil {
		panic("EnvIdentityClientMock.RemoveGroupMembersFunc: method is nil but EnvIdentityClient.RemoveGroupMembers was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		UserIDs []string
	}{
		Ctx:     ctx,
		GroupID: groupID,
		UserIDs: userIDs,
	}
	mock.lockRemoveGroupMembers.Lock()
	mock.calls.RemoveGroupMembers = append(mock.calls.RemoveGroupMembers, callInfo)
	mock.lockRemoveGroupMembers.Unlock()
	return mock.RemoveGroupMembersFunc(ctx, groupID, userIDs)
}

// RemoveGroupMembersCalls gets all the calls that were made to RemoveGroupMembers.
// Check the length with:
//
//	len(mockedEnvIdentityClient.RemoveGroupMembersCalls())
func (mock *EnvIdentityClientMock) RemoveGroupMembersCalls() []struct {
	Ctx     context.Context
	GroupID string
	UserIDs []string
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		UserIDs []string
	}
	mock.lockRemoveGroupMembers.RLock()
	calls = mock.calls.RemoveGroupMembers
	mock.lockRemoveGroupMembers.RUnlock()
	return calls
}

// RemoveRoleAssignees calls RemoveRoleAssigneesFunc.
func (mock *EnvIdentityClientMock) RemoveRoleAssignees(ctx context.Context, roleID string, req thundersvc.RoleAssignmentsRequest) error {
	if mock.RemoveRoleAssigneesFunc == nil {
		panic("EnvIdentityClientMock.RemoveRoleAssigneesFunc: method is nil but EnvIdentityClient.RemoveRoleAssignees was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RoleAssignmentsRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockRemoveRoleAssignees.Lock()
	mock.calls.RemoveRoleAssignees = append(mock.calls.RemoveRoleAssignees, callInfo)
	mock.lockRemoveRoleAssignees.Unlock()
	return mock.RemoveRoleAssigneesFunc(ctx, roleID, req)
}

// RemoveRoleAssigneesCalls gets all the calls that were made to RemoveRoleAssignees.
// Check the length with:
//
//	len(mockedEnvIdentityClient.RemoveRoleAssigneesCalls())
func (mock *EnvIdentityClientMock) RemoveRoleAssigneesCalls() []struct {
	Ctx    context.Context
	RoleID string
	Req    thundersvc.RoleAssignmentsRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RoleAssignmentsRequest
	}
	mock.lockRemoveRoleAssignees.RLock()
	calls = mock.calls.RemoveRoleAssignees
	mock.lockRemoveRoleAssignees.RUnlock()
	return calls
}

// RemoveRolePermissions calls RemoveRolePermissionsFunc.
func (mock *EnvIdentityClientMock) RemoveRolePermissions(ctx context.Context, roleID string, req thundersvc.RolePermissionRequest) error {
	if mock.RemoveRolePermissionsFunc == nil {
		panic("EnvIdentityClientMock.RemoveRolePermissionsFunc: method is nil but EnvIdentityClient.RemoveRolePermissions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RolePermissionRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockRemoveRolePermissions.Lock()
	mock.calls.RemoveRolePermissions = append(mock.calls.RemoveRolePermissions, callInfo)
	mock.lockRemoveRolePermissions.Unlock()
	return mock.RemoveRolePermissionsFunc(ctx, roleID, req)
}

// RemoveRolePermissionsCalls gets all the calls that were made to RemoveRolePermissions.
// Check the length with:
//
//	len(mockedEnvIdentityClient.RemoveRolePermissionsCalls())
func (mock *EnvIdentityClientMock) RemoveRolePermissionsCalls() []struct {
	Ctx    context.Context
	RoleID string
	Req    thundersvc.RolePermissionRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.RolePermissionRequest
	}
	mock.lockRemoveRolePermissions.RLock()
	calls = mock.calls.RemoveRolePermissions
	mock.lockRemoveRolePermissions.RUnlock()
	return calls
}

// UpdateGroup calls UpdateGroupFunc.
func (mock *EnvIdentityClientMock) UpdateGroup(ctx context.Context, groupID string, req thundersvc.UpdateGroupRequest) (*thundersvc.ThunderGroup, error) {
	if mock.UpdateGroupFunc == nil {
		panic("EnvIdentityClientMock.UpdateGroupFunc: method is nil but EnvIdentityClient.UpdateGroup was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		GroupID string
		Req     thundersvc.UpdateGroupRequest
	}{
		Ctx:     ctx,
		GroupID: groupID,
		Req:     req,
	}
	mock.lockUpdateGroup.Lock()
	mock.calls.UpdateGroup = append(mock.calls.UpdateGroup, callInfo)
	mock.lockUpdateGroup.Unlock()
	return mock.UpdateGroupFunc(ctx, groupID, req)
}

// UpdateGroupCalls gets all the calls that were made to UpdateGroup.
// Check the length with:
//
//	len(mockedEnvIdentityClient.UpdateGroupCalls())
func (mock *EnvIdentityClientMock) UpdateGroupCalls() []struct {
	Ctx     context.Context
	GroupID string
	Req     thundersvc.UpdateGroupRequest
} {
	var calls []struct {
		Ctx     context.Context
		GroupID string
		Req     thundersvc.UpdateGroupRequest
	}
	mock.lockUpdateGroup.RLock()
	calls = mock.calls.UpdateGroup
	mock.lockUpdateGroup.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *EnvIdentityClientMock) UpdateRole(ctx context.Context, roleID string, req thundersvc.UpdateRoleRequest) (*thundersvc.ThunderRole, error) {
	if mock.UpdateRoleFunc == nil {
		panic("EnvIdentityClientMock.UpdateRoleFunc: method is nil but EnvIdentityClient.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.UpdateRoleRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, roleID, req)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedEnvIdentityClient.UpdateRoleCalls())
func (mock *EnvIdentityClientMock) UpdateRoleCalls() []struct {
	Ctx    context.Context
	RoleID string
	Req    thundersvc.UpdateRoleRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID string
		Req    thundersvc.UpdateRoleRequest
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *EnvIdentityClientMock) UpdateUser(ctx context.Context, userID string, req thundersvc.UpdateUserRequest) (*thundersvc.ThunderUser, error) {
	if mock.UpdateUserFunc == nil {
		panic("EnvIdentityClientMock.UpdateUserFunc: method is nil but EnvIdentityClient.UpdateUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Req    thundersvc.UpdateUserRequest
	}{
		Ctx:    ctx,
		UserID: userID,
		Req:    req,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(ctx, userID, req)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedEnvIdentityClient.UpdateUserCalls())
func (mock *EnvIdentityClientMock) UpdateUserCalls() []struct {
	Ctx    context.Context
	UserID string
	Req    thundersvc.UpdateUserRequest
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Req    thundersvc.UpdateUserRequest
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}
