// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// ObserverSvcClientMock is a mock implementation of observersvc.ObserverSvcClient.
//
//	func TestSomethingThatUsesObserverSvcClient(t *testing.T) {
//
//		// make and configure a mocked observersvc.ObserverSvcClient
//		mockedObserverSvcClient := &ObserverSvcClientMock{
//			GetWorkflowRunLogsFunc: func(ctx context.Context, organization string, workflowRunName string) (*models.LogsResponse, error) {
//				panic("mock out the GetWorkflowRunLogs method")
//			},
//		}
//
//		// use mockedObserverSvcClient in code that requires observersvc.ObserverSvcClient
//		// and then make assertions.
//
//	}
type ObserverSvcClientMock struct {
	// GetWorkflowRunLogsFunc mocks the GetWorkflowRunLogs method.
	GetWorkflowRunLogsFunc func(ctx context.Context, organization string, workflowRunName string) (*models.LogsResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetWorkflowRunLogs holds details about calls to the GetWorkflowRunLogs method.
		GetWorkflowRunLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// WorkflowRunName is the workflowRunName argument value.
			WorkflowRunName string
		}
	}
	lockGetWorkflowRunLogs sync.RWMutex
}

// GetWorkflowRunLogs calls GetWorkflowRunLogsFunc.
func (mock *ObserverSvcClientMock) GetWorkflowRunLogs(ctx context.Context, organization string, workflowRunName string) (*models.LogsResponse, error) {
	if mock.GetWorkflowRunLogsFunc == nil {
		panic("ObserverSvcClientMock.GetWorkflowRunLogsFunc: method is nil but ObserverSvcClient.GetWorkflowRunLogs was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		Organization    string
		WorkflowRunName string
	}{
		Ctx:             ctx,
		Organization:    organization,
		WorkflowRunName: workflowRunName,
	}
	mock.lockGetWorkflowRunLogs.Lock()
	mock.calls.GetWorkflowRunLogs = append(mock.calls.GetWorkflowRunLogs, callInfo)
	mock.lockGetWorkflowRunLogs.Unlock()
	return mock.GetWorkflowRunLogsFunc(ctx, organization, workflowRunName)
}

// GetWorkflowRunLogsCalls gets all the calls that were made to GetWorkflowRunLogs.
// Check the length with:
//
//	len(mockedObserverSvcClient.GetWorkflowRunLogsCalls())
func (mock *ObserverSvcClientMock) GetWorkflowRunLogsCalls() []struct {
	Ctx             context.Context
	Organization    string
	WorkflowRunName string
} {
	var calls []struct {
		Ctx             context.Context
		Organization    string
		WorkflowRunName string
	}
	mock.lockGetWorkflowRunLogs.RLock()
	calls = mock.calls.GetWorkflowRunLogs
	mock.lockGetWorkflowRunLogs.RUnlock()
	return calls
}
