/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// AgentIdentitiesAPIService AgentIdentitiesAPI service
type AgentIdentitiesAPIService service

type ApiListAgentIdentityScopesRequest struct {
	ctx        context.Context
	ApiService *AgentIdentitiesAPIService
	orgName    string
	envName    string
}

func (r ApiListAgentIdentityScopesRequest) Execute() (*AgentIdentityScopeListResponse, *http.Response, error) {
	return r.ApiService.ListAgentIdentityScopesExecute(r)
}

/*
ListAgentIdentityScopes List grantable agent-identity scopes for an environment

Aggregates scopes from MCP proxies that target this environment with identity security enabled. Read-only; powers role building.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param orgName
	@param envName
	@return ApiListAgentIdentityScopesRequest
*/
func (a *AgentIdentitiesAPIService) ListAgentIdentityScopes(ctx context.Context, orgName string, envName string) ApiListAgentIdentityScopesRequest {
	return ApiListAgentIdentityScopesRequest{
		ApiService: a,
		ctx:        ctx,
		orgName:    orgName,
		envName:    envName,
	}
}

// Execute executes the request
//
//	@return AgentIdentityScopeListResponse
func (a *AgentIdentitiesAPIService) ListAgentIdentityScopesExecute(r ApiListAgentIdentityScopesRequest) (*AgentIdentityScopeListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AgentIdentityScopeListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentIdentitiesAPIService.ListAgentIdentityScopes")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/orgs/{orgName}/environments/{envName}/agent-identities/scopes"
	localVarPath = strings.Replace(localVarPath, "{"+"orgName"+"}", url.PathEscape(parameterValueToString(r.orgName, "orgName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"envName"+"}", url.PathEscape(parameterValueToString(r.envName, "envName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
