/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPProxyScopeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyScopeRequest{}

// MCPProxyScopeRequest struct for MCPProxyScopeRequest
type MCPProxyScopeRequest struct {
	// Action name on the proxy's resource server; the token scope is \"<proxy-handle>:<action>\".
	Action      string  `json:"action"`
	Description *string `json:"description,omitempty"`
	// MCP tool names this scope authorizes.
	Tools []string `json:"tools"`
}

// NewMCPProxyScopeRequest instantiates a new MCPProxyScopeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyScopeRequest(action string, tools []string) *MCPProxyScopeRequest {
	this := MCPProxyScopeRequest{}
	this.Action = action
	this.Tools = tools
	return &this
}

// NewMCPProxyScopeRequestWithDefaults instantiates a new MCPProxyScopeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyScopeRequestWithDefaults() *MCPProxyScopeRequest {
	this := MCPProxyScopeRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *MCPProxyScopeRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MCPProxyScopeRequest) SetAction(v string) {
	o.Action = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MCPProxyScopeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MCPProxyScopeRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MCPProxyScopeRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTools returns the Tools field value
func (o *MCPProxyScopeRequest) GetTools() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeRequest) GetToolsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools, true
}

// SetTools sets field value
func (o *MCPProxyScopeRequest) SetTools(v []string) {
	o.Tools = v
}

func (o MCPProxyScopeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyScopeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["tools"] = o.Tools
	return toSerialize, nil
}

type NullableMCPProxyScopeRequest struct {
	value *MCPProxyScopeRequest
	isSet bool
}

func (v NullableMCPProxyScopeRequest) Get() *MCPProxyScopeRequest {
	return v.value
}

func (v *NullableMCPProxyScopeRequest) Set(val *MCPProxyScopeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyScopeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyScopeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyScopeRequest(val *MCPProxyScopeRequest) *NullableMCPProxyScopeRequest {
	return &NullableMCPProxyScopeRequest{value: val, isSet: true}
}

func (v NullableMCPProxyScopeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyScopeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
