/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GroupListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupListResponse{}

// GroupListResponse struct for GroupListResponse
type GroupListResponse struct {
	Groups []GroupResponse `json:"groups"`
	// Total number of groups
	Total int32 `json:"total"`
	// Number of results skipped
	Offset int32 `json:"offset"`
	// Maximum results returned
	Limit int32 `json:"limit"`
}

// NewGroupListResponse instantiates a new GroupListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupListResponse(groups []GroupResponse, total int32, offset int32, limit int32) *GroupListResponse {
	this := GroupListResponse{}
	this.Groups = groups
	this.Total = total
	this.Offset = offset
	this.Limit = limit
	return &this
}

// NewGroupListResponseWithDefaults instantiates a new GroupListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupListResponseWithDefaults() *GroupListResponse {
	this := GroupListResponse{}
	return &this
}

// GetGroups returns the Groups field value
func (o *GroupListResponse) GetGroups() []GroupResponse {
	if o == nil {
		var ret []GroupResponse
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetGroupsOk() ([]GroupResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *GroupListResponse) SetGroups(v []GroupResponse) {
	o.Groups = v
}

// GetTotal returns the Total field value
func (o *GroupListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GroupListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetOffset returns the Offset field value
func (o *GroupListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *GroupListResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetLimit returns the Limit field value
func (o *GroupListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *GroupListResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o GroupListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groups"] = o.Groups
	toSerialize["total"] = o.Total
	toSerialize["offset"] = o.Offset
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

type NullableGroupListResponse struct {
	value *GroupListResponse
	isSet bool
}

func (v NullableGroupListResponse) Get() *GroupListResponse {
	return v.value
}

func (v *NullableGroupListResponse) Set(val *GroupListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupListResponse(val *GroupListResponse) *NullableGroupListResponse {
	return &NullableGroupListResponse{value: val, isSet: true}
}

func (v NullableGroupListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
