/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateUserCredentialsRequestAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserCredentialsRequestAttributes{}

// UpdateUserCredentialsRequestAttributes struct for UpdateUserCredentialsRequestAttributes
type UpdateUserCredentialsRequestAttributes struct {
	// New password
	Password string `json:"password"`
}

// NewUpdateUserCredentialsRequestAttributes instantiates a new UpdateUserCredentialsRequestAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserCredentialsRequestAttributes(password string) *UpdateUserCredentialsRequestAttributes {
	this := UpdateUserCredentialsRequestAttributes{}
	this.Password = password
	return &this
}

// NewUpdateUserCredentialsRequestAttributesWithDefaults instantiates a new UpdateUserCredentialsRequestAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserCredentialsRequestAttributesWithDefaults() *UpdateUserCredentialsRequestAttributes {
	this := UpdateUserCredentialsRequestAttributes{}
	return &this
}

// GetPassword returns the Password field value
func (o *UpdateUserCredentialsRequestAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UpdateUserCredentialsRequestAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UpdateUserCredentialsRequestAttributes) SetPassword(v string) {
	o.Password = v
}

func (o UpdateUserCredentialsRequestAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserCredentialsRequestAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableUpdateUserCredentialsRequestAttributes struct {
	value *UpdateUserCredentialsRequestAttributes
	isSet bool
}

func (v NullableUpdateUserCredentialsRequestAttributes) Get() *UpdateUserCredentialsRequestAttributes {
	return v.value
}

func (v *NullableUpdateUserCredentialsRequestAttributes) Set(val *UpdateUserCredentialsRequestAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserCredentialsRequestAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserCredentialsRequestAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserCredentialsRequestAttributes(val *UpdateUserCredentialsRequestAttributes) *NullableUpdateUserCredentialsRequestAttributes {
	return &NullableUpdateUserCredentialsRequestAttributes{value: val, isSet: true}
}

func (v NullableUpdateUserCredentialsRequestAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserCredentialsRequestAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
