/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleResponse{}

// RoleResponse struct for RoleResponse
type RoleResponse struct {
	// Role ID
	Id string `json:"id"`
	// Role name
	Name string `json:"name"`
	// Role description
	Description *string `json:"description,omitempty"`
	// Whether this is a predefined read-only role
	IsReadOnly *bool `json:"isReadOnly,omitempty"`
	// Organization unit ID
	OuId *string `json:"ouId,omitempty"`
	// Role permissions
	Permissions []RoleResponsePermissionsInner `json:"permissions,omitempty"`
}

// NewRoleResponse instantiates a new RoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleResponse(id string, name string) *RoleResponse {
	this := RoleResponse{}
	this.Id = id
	this.Name = name
	return &this
}

// NewRoleResponseWithDefaults instantiates a new RoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleResponseWithDefaults() *RoleResponse {
	this := RoleResponse{}
	return &this
}

// GetId returns the Id field value
func (o *RoleResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RoleResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *RoleResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoleResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoleResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoleResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoleResponse) SetDescription(v string) {
	o.Description = &v
}

// GetIsReadOnly returns the IsReadOnly field value if set, zero value otherwise.
func (o *RoleResponse) GetIsReadOnly() bool {
	if o == nil || IsNil(o.IsReadOnly) {
		var ret bool
		return ret
	}
	return *o.IsReadOnly
}

// GetIsReadOnlyOk returns a tuple with the IsReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetIsReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsReadOnly) {
		return nil, false
	}
	return o.IsReadOnly, true
}

// HasIsReadOnly returns a boolean if a field has been set.
func (o *RoleResponse) HasIsReadOnly() bool {
	if o != nil && !IsNil(o.IsReadOnly) {
		return true
	}

	return false
}

// SetIsReadOnly gets a reference to the given bool and assigns it to the IsReadOnly field.
func (o *RoleResponse) SetIsReadOnly(v bool) {
	o.IsReadOnly = &v
}

// GetOuId returns the OuId field value if set, zero value otherwise.
func (o *RoleResponse) GetOuId() string {
	if o == nil || IsNil(o.OuId) {
		var ret string
		return ret
	}
	return *o.OuId
}

// GetOuIdOk returns a tuple with the OuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetOuIdOk() (*string, bool) {
	if o == nil || IsNil(o.OuId) {
		return nil, false
	}
	return o.OuId, true
}

// HasOuId returns a boolean if a field has been set.
func (o *RoleResponse) HasOuId() bool {
	if o != nil && !IsNil(o.OuId) {
		return true
	}

	return false
}

// SetOuId gets a reference to the given string and assigns it to the OuId field.
func (o *RoleResponse) SetOuId(v string) {
	o.OuId = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *RoleResponse) GetPermissions() []RoleResponsePermissionsInner {
	if o == nil || IsNil(o.Permissions) {
		var ret []RoleResponsePermissionsInner
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleResponse) GetPermissionsOk() ([]RoleResponsePermissionsInner, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *RoleResponse) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []RoleResponsePermissionsInner and assigns it to the Permissions field.
func (o *RoleResponse) SetPermissions(v []RoleResponsePermissionsInner) {
	o.Permissions = v
}

func (o RoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsReadOnly) {
		toSerialize["isReadOnly"] = o.IsReadOnly
	}
	if !IsNil(o.OuId) {
		toSerialize["ouId"] = o.OuId
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableRoleResponse struct {
	value *RoleResponse
	isSet bool
}

func (v NullableRoleResponse) Get() *RoleResponse {
	return v.value
}

func (v *NullableRoleResponse) Set(val *RoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleResponse(val *RoleResponse) *NullableRoleResponse {
	return &NullableRoleResponse{value: val, isSet: true}
}

func (v NullableRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
