/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityAgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityAgentResponse{}

// AgentIdentityAgentResponse struct for AgentIdentityAgentResponse
type AgentIdentityAgentResponse struct {
	AgentName   string `json:"agentName"`
	ProjectName string `json:"projectName"`
	// Thunder binding status (pending/in_progress/completed/failed)
	Status         string  `json:"status"`
	ThunderAgentId *string `json:"thunderAgentId,omitempty"`
}

// NewAgentIdentityAgentResponse instantiates a new AgentIdentityAgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityAgentResponse(agentName string, projectName string, status string) *AgentIdentityAgentResponse {
	this := AgentIdentityAgentResponse{}
	this.AgentName = agentName
	this.ProjectName = projectName
	this.Status = status
	return &this
}

// NewAgentIdentityAgentResponseWithDefaults instantiates a new AgentIdentityAgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityAgentResponseWithDefaults() *AgentIdentityAgentResponse {
	this := AgentIdentityAgentResponse{}
	return &this
}

// GetAgentName returns the AgentName field value
func (o *AgentIdentityAgentResponse) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAgentResponse) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *AgentIdentityAgentResponse) SetAgentName(v string) {
	o.AgentName = v
}

// GetProjectName returns the ProjectName field value
func (o *AgentIdentityAgentResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAgentResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *AgentIdentityAgentResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetStatus returns the Status field value
func (o *AgentIdentityAgentResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAgentResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentIdentityAgentResponse) SetStatus(v string) {
	o.Status = v
}

// GetThunderAgentId returns the ThunderAgentId field value if set, zero value otherwise.
func (o *AgentIdentityAgentResponse) GetThunderAgentId() string {
	if o == nil || IsNil(o.ThunderAgentId) {
		var ret string
		return ret
	}
	return *o.ThunderAgentId
}

// GetThunderAgentIdOk returns a tuple with the ThunderAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityAgentResponse) GetThunderAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ThunderAgentId) {
		return nil, false
	}
	return o.ThunderAgentId, true
}

// HasThunderAgentId returns a boolean if a field has been set.
func (o *AgentIdentityAgentResponse) HasThunderAgentId() bool {
	if o != nil && !IsNil(o.ThunderAgentId) {
		return true
	}

	return false
}

// SetThunderAgentId gets a reference to the given string and assigns it to the ThunderAgentId field.
func (o *AgentIdentityAgentResponse) SetThunderAgentId(v string) {
	o.ThunderAgentId = &v
}

func (o AgentIdentityAgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityAgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agentName"] = o.AgentName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["status"] = o.Status
	if !IsNil(o.ThunderAgentId) {
		toSerialize["thunderAgentId"] = o.ThunderAgentId
	}
	return toSerialize, nil
}

type NullableAgentIdentityAgentResponse struct {
	value *AgentIdentityAgentResponse
	isSet bool
}

func (v NullableAgentIdentityAgentResponse) Get() *AgentIdentityAgentResponse {
	return v.value
}

func (v *NullableAgentIdentityAgentResponse) Set(val *AgentIdentityAgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityAgentResponse(val *AgentIdentityAgentResponse) *NullableAgentIdentityAgentResponse {
	return &NullableAgentIdentityAgentResponse{value: val, isSet: true}
}

func (v NullableAgentIdentityAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
