/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityScopeEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityScopeEntry{}

// AgentIdentityScopeEntry struct for AgentIdentityScopeEntry
type AgentIdentityScopeEntry struct {
	Scope       string  `json:"scope"`
	Description *string `json:"description,omitempty"`
	// Handle of the owning MCP proxy.
	McpProxyId   string  `json:"mcpProxyId"`
	McpProxyName *string `json:"mcpProxyName,omitempty"`
}

// NewAgentIdentityScopeEntry instantiates a new AgentIdentityScopeEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityScopeEntry(scope string, mcpProxyId string) *AgentIdentityScopeEntry {
	this := AgentIdentityScopeEntry{}
	this.Scope = scope
	this.McpProxyId = mcpProxyId
	return &this
}

// NewAgentIdentityScopeEntryWithDefaults instantiates a new AgentIdentityScopeEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityScopeEntryWithDefaults() *AgentIdentityScopeEntry {
	this := AgentIdentityScopeEntry{}
	return &this
}

// GetScope returns the Scope field value
func (o *AgentIdentityScopeEntry) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityScopeEntry) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *AgentIdentityScopeEntry) SetScope(v string) {
	o.Scope = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentIdentityScopeEntry) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityScopeEntry) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentIdentityScopeEntry) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentIdentityScopeEntry) SetDescription(v string) {
	o.Description = &v
}

// GetMcpProxyId returns the McpProxyId field value
func (o *AgentIdentityScopeEntry) GetMcpProxyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McpProxyId
}

// GetMcpProxyIdOk returns a tuple with the McpProxyId field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityScopeEntry) GetMcpProxyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpProxyId, true
}

// SetMcpProxyId sets field value
func (o *AgentIdentityScopeEntry) SetMcpProxyId(v string) {
	o.McpProxyId = v
}

// GetMcpProxyName returns the McpProxyName field value if set, zero value otherwise.
func (o *AgentIdentityScopeEntry) GetMcpProxyName() string {
	if o == nil || IsNil(o.McpProxyName) {
		var ret string
		return ret
	}
	return *o.McpProxyName
}

// GetMcpProxyNameOk returns a tuple with the McpProxyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityScopeEntry) GetMcpProxyNameOk() (*string, bool) {
	if o == nil || IsNil(o.McpProxyName) {
		return nil, false
	}
	return o.McpProxyName, true
}

// HasMcpProxyName returns a boolean if a field has been set.
func (o *AgentIdentityScopeEntry) HasMcpProxyName() bool {
	if o != nil && !IsNil(o.McpProxyName) {
		return true
	}

	return false
}

// SetMcpProxyName gets a reference to the given string and assigns it to the McpProxyName field.
func (o *AgentIdentityScopeEntry) SetMcpProxyName(v string) {
	o.McpProxyName = &v
}

func (o AgentIdentityScopeEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityScopeEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["mcpProxyId"] = o.McpProxyId
	if !IsNil(o.McpProxyName) {
		toSerialize["mcpProxyName"] = o.McpProxyName
	}
	return toSerialize, nil
}

type NullableAgentIdentityScopeEntry struct {
	value *AgentIdentityScopeEntry
	isSet bool
}

func (v NullableAgentIdentityScopeEntry) Get() *AgentIdentityScopeEntry {
	return v.value
}

func (v *NullableAgentIdentityScopeEntry) Set(val *AgentIdentityScopeEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityScopeEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityScopeEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityScopeEntry(val *AgentIdentityScopeEntry) *NullableAgentIdentityScopeEntry {
	return &NullableAgentIdentityScopeEntry{value: val, isSet: true}
}

func (v NullableAgentIdentityScopeEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityScopeEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
