/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPPolicyAvailableItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPPolicyAvailableItem{}

// MCPPolicyAvailableItem struct for MCPPolicyAvailableItem
type MCPPolicyAvailableItem struct {
	// Policy name
	Name string `json:"name"`
	// Policy version
	Version string `json:"version"`
}

// NewMCPPolicyAvailableItem instantiates a new MCPPolicyAvailableItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPPolicyAvailableItem(name string, version string) *MCPPolicyAvailableItem {
	this := MCPPolicyAvailableItem{}
	this.Name = name
	this.Version = version
	return &this
}

// NewMCPPolicyAvailableItemWithDefaults instantiates a new MCPPolicyAvailableItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPPolicyAvailableItemWithDefaults() *MCPPolicyAvailableItem {
	this := MCPPolicyAvailableItem{}
	return &this
}

// GetName returns the Name field value
func (o *MCPPolicyAvailableItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MCPPolicyAvailableItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MCPPolicyAvailableItem) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *MCPPolicyAvailableItem) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *MCPPolicyAvailableItem) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *MCPPolicyAvailableItem) SetVersion(v string) {
	o.Version = v
}

func (o MCPPolicyAvailableItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPPolicyAvailableItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

type NullableMCPPolicyAvailableItem struct {
	value *MCPPolicyAvailableItem
	isSet bool
}

func (v NullableMCPPolicyAvailableItem) Get() *MCPPolicyAvailableItem {
	return v.value
}

func (v *NullableMCPPolicyAvailableItem) Set(val *MCPPolicyAvailableItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPPolicyAvailableItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPPolicyAvailableItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPPolicyAvailableItem(val *MCPPolicyAvailableItem) *NullableMCPPolicyAvailableItem {
	return &NullableMCPPolicyAvailableItem{value: val, isSet: true}
}

func (v NullableMCPPolicyAvailableItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPPolicyAvailableItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
