/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPProxyScopeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyScopeListResponse{}

// MCPProxyScopeListResponse struct for MCPProxyScopeListResponse
type MCPProxyScopeListResponse struct {
	Scopes []MCPProxyScopeResponse `json:"scopes"`
}

// NewMCPProxyScopeListResponse instantiates a new MCPProxyScopeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyScopeListResponse(scopes []MCPProxyScopeResponse) *MCPProxyScopeListResponse {
	this := MCPProxyScopeListResponse{}
	this.Scopes = scopes
	return &this
}

// NewMCPProxyScopeListResponseWithDefaults instantiates a new MCPProxyScopeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyScopeListResponseWithDefaults() *MCPProxyScopeListResponse {
	this := MCPProxyScopeListResponse{}
	return &this
}

// GetScopes returns the Scopes field value
func (o *MCPProxyScopeListResponse) GetScopes() []MCPProxyScopeResponse {
	if o == nil {
		var ret []MCPProxyScopeResponse
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeListResponse) GetScopesOk() ([]MCPProxyScopeResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *MCPProxyScopeListResponse) SetScopes(v []MCPProxyScopeResponse) {
	o.Scopes = v
}

func (o MCPProxyScopeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyScopeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scopes"] = o.Scopes
	return toSerialize, nil
}

type NullableMCPProxyScopeListResponse struct {
	value *MCPProxyScopeListResponse
	isSet bool
}

func (v NullableMCPProxyScopeListResponse) Get() *MCPProxyScopeListResponse {
	return v.value
}

func (v *NullableMCPProxyScopeListResponse) Set(val *MCPProxyScopeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyScopeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyScopeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyScopeListResponse(val *MCPProxyScopeListResponse) *NullableMCPProxyScopeListResponse {
	return &NullableMCPProxyScopeListResponse{value: val, isSet: true}
}

func (v NullableMCPProxyScopeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyScopeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
