/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMPolicyAvailabilityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMPolicyAvailabilityResponse{}

// LLMPolicyAvailabilityResponse struct for LLMPolicyAvailabilityResponse
type LLMPolicyAvailabilityResponse struct {
	Count int32                 `json:"count"`
	List  []LLMPolicyDefinition `json:"list"`
}

// NewLLMPolicyAvailabilityResponse instantiates a new LLMPolicyAvailabilityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMPolicyAvailabilityResponse(count int32, list []LLMPolicyDefinition) *LLMPolicyAvailabilityResponse {
	this := LLMPolicyAvailabilityResponse{}
	this.Count = count
	this.List = list
	return &this
}

// NewLLMPolicyAvailabilityResponseWithDefaults instantiates a new LLMPolicyAvailabilityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMPolicyAvailabilityResponseWithDefaults() *LLMPolicyAvailabilityResponse {
	this := LLMPolicyAvailabilityResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *LLMPolicyAvailabilityResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyAvailabilityResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *LLMPolicyAvailabilityResponse) SetCount(v int32) {
	o.Count = v
}

// GetList returns the List field value
func (o *LLMPolicyAvailabilityResponse) GetList() []LLMPolicyDefinition {
	if o == nil {
		var ret []LLMPolicyDefinition
		return ret
	}

	return o.List
}

// GetListOk returns a tuple with the List field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyAvailabilityResponse) GetListOk() ([]LLMPolicyDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return o.List, true
}

// SetList sets field value
func (o *LLMPolicyAvailabilityResponse) SetList(v []LLMPolicyDefinition) {
	o.List = v
}

func (o LLMPolicyAvailabilityResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMPolicyAvailabilityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["list"] = o.List
	return toSerialize, nil
}

type NullableLLMPolicyAvailabilityResponse struct {
	value *LLMPolicyAvailabilityResponse
	isSet bool
}

func (v NullableLLMPolicyAvailabilityResponse) Get() *LLMPolicyAvailabilityResponse {
	return v.value
}

func (v *NullableLLMPolicyAvailabilityResponse) Set(val *LLMPolicyAvailabilityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMPolicyAvailabilityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMPolicyAvailabilityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMPolicyAvailabilityResponse(val *LLMPolicyAvailabilityResponse) *NullableLLMPolicyAvailabilityResponse {
	return &NullableLLMPolicyAvailabilityResponse{value: val, isSet: true}
}

func (v NullableLLMPolicyAvailabilityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMPolicyAvailabilityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
