/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityAssignmentEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityAssignmentEntry{}

// AgentIdentityAssignmentEntry struct for AgentIdentityAssignmentEntry
type AgentIdentityAssignmentEntry struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// NewAgentIdentityAssignmentEntry instantiates a new AgentIdentityAssignmentEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityAssignmentEntry(id string, type_ string) *AgentIdentityAssignmentEntry {
	this := AgentIdentityAssignmentEntry{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewAgentIdentityAssignmentEntryWithDefaults instantiates a new AgentIdentityAssignmentEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityAssignmentEntryWithDefaults() *AgentIdentityAssignmentEntry {
	this := AgentIdentityAssignmentEntry{}
	return &this
}

// GetId returns the Id field value
func (o *AgentIdentityAssignmentEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAssignmentEntry) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentIdentityAssignmentEntry) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AgentIdentityAssignmentEntry) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAssignmentEntry) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AgentIdentityAssignmentEntry) SetType(v string) {
	o.Type = v
}

func (o AgentIdentityAssignmentEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityAssignmentEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableAgentIdentityAssignmentEntry struct {
	value *AgentIdentityAssignmentEntry
	isSet bool
}

func (v NullableAgentIdentityAssignmentEntry) Get() *AgentIdentityAssignmentEntry {
	return v.value
}

func (v *NullableAgentIdentityAssignmentEntry) Set(val *AgentIdentityAssignmentEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityAssignmentEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityAssignmentEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityAssignmentEntry(val *AgentIdentityAssignmentEntry) *NullableAgentIdentityAssignmentEntry {
	return &NullableAgentIdentityAssignmentEntry{value: val, isSet: true}
}

func (v NullableAgentIdentityAssignmentEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityAssignmentEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
