/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentRegenerateSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRegenerateSecretResponse{}

// AgentRegenerateSecretResponse Response for rotating an AgentID secret
type AgentRegenerateSecretResponse struct {
	EnvironmentName string `json:"environmentName"`
	// Whether the agent runs on the platform (`internal`) or outside it (`external`)
	ProvisioningType string `json:"provisioningType"`
	ClientId         string `json:"clientId"`
	// The newly generated OAuth2 client secret, sent back to both platform-hosted and external agents
	ClientSecret string `json:"clientSecret"`
	Status       string `json:"status"`
}

// NewAgentRegenerateSecretResponse instantiates a new AgentRegenerateSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRegenerateSecretResponse(environmentName string, provisioningType string, clientId string, clientSecret string, status string) *AgentRegenerateSecretResponse {
	this := AgentRegenerateSecretResponse{}
	this.EnvironmentName = environmentName
	this.ProvisioningType = provisioningType
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.Status = status
	return &this
}

// NewAgentRegenerateSecretResponseWithDefaults instantiates a new AgentRegenerateSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentRegenerateSecretResponseWithDefaults() *AgentRegenerateSecretResponse {
	this := AgentRegenerateSecretResponse{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *AgentRegenerateSecretResponse) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *AgentRegenerateSecretResponse) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *AgentRegenerateSecretResponse) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetProvisioningType returns the ProvisioningType field value
func (o *AgentRegenerateSecretResponse) GetProvisioningType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProvisioningType
}

// GetProvisioningTypeOk returns a tuple with the ProvisioningType field value
// and a boolean to check if the value has been set.
func (o *AgentRegenerateSecretResponse) GetProvisioningTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProvisioningType, true
}

// SetProvisioningType sets field value
func (o *AgentRegenerateSecretResponse) SetProvisioningType(v string) {
	o.ProvisioningType = v
}

// GetClientId returns the ClientId field value
func (o *AgentRegenerateSecretResponse) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AgentRegenerateSecretResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AgentRegenerateSecretResponse) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AgentRegenerateSecretResponse) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AgentRegenerateSecretResponse) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AgentRegenerateSecretResponse) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetStatus returns the Status field value
func (o *AgentRegenerateSecretResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentRegenerateSecretResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentRegenerateSecretResponse) SetStatus(v string) {
	o.Status = v
}

func (o AgentRegenerateSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRegenerateSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	toSerialize["provisioningType"] = o.ProvisioningType
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableAgentRegenerateSecretResponse struct {
	value *AgentRegenerateSecretResponse
	isSet bool
}

func (v NullableAgentRegenerateSecretResponse) Get() *AgentRegenerateSecretResponse {
	return v.value
}

func (v *NullableAgentRegenerateSecretResponse) Set(val *AgentRegenerateSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRegenerateSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRegenerateSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRegenerateSecretResponse(val *AgentRegenerateSecretResponse) *NullableAgentRegenerateSecretResponse {
	return &NullableAgentRegenerateSecretResponse{value: val, isSet: true}
}

func (v NullableAgentRegenerateSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRegenerateSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
