/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPProxyCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyCapabilities{}

// MCPProxyCapabilities struct for MCPProxyCapabilities
type MCPProxyCapabilities struct {
	Prompts   []map[string]interface{} `json:"prompts,omitempty"`
	Resources []map[string]interface{} `json:"resources,omitempty"`
	Tools     []map[string]interface{} `json:"tools,omitempty"`
}

// NewMCPProxyCapabilities instantiates a new MCPProxyCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyCapabilities() *MCPProxyCapabilities {
	this := MCPProxyCapabilities{}
	return &this
}

// NewMCPProxyCapabilitiesWithDefaults instantiates a new MCPProxyCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyCapabilitiesWithDefaults() *MCPProxyCapabilities {
	this := MCPProxyCapabilities{}
	return &this
}

// GetPrompts returns the Prompts field value if set, zero value otherwise.
func (o *MCPProxyCapabilities) GetPrompts() []map[string]interface{} {
	if o == nil || IsNil(o.Prompts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Prompts
}

// GetPromptsOk returns a tuple with the Prompts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyCapabilities) GetPromptsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Prompts) {
		return nil, false
	}
	return o.Prompts, true
}

// HasPrompts returns a boolean if a field has been set.
func (o *MCPProxyCapabilities) HasPrompts() bool {
	if o != nil && !IsNil(o.Prompts) {
		return true
	}

	return false
}

// SetPrompts gets a reference to the given []map[string]interface{} and assigns it to the Prompts field.
func (o *MCPProxyCapabilities) SetPrompts(v []map[string]interface{}) {
	o.Prompts = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *MCPProxyCapabilities) GetResources() []map[string]interface{} {
	if o == nil || IsNil(o.Resources) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyCapabilities) GetResourcesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *MCPProxyCapabilities) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []map[string]interface{} and assigns it to the Resources field.
func (o *MCPProxyCapabilities) SetResources(v []map[string]interface{}) {
	o.Resources = v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *MCPProxyCapabilities) GetTools() []map[string]interface{} {
	if o == nil || IsNil(o.Tools) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyCapabilities) GetToolsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *MCPProxyCapabilities) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []map[string]interface{} and assigns it to the Tools field.
func (o *MCPProxyCapabilities) SetTools(v []map[string]interface{}) {
	o.Tools = v
}

func (o MCPProxyCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prompts) {
		toSerialize["prompts"] = o.Prompts
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	return toSerialize, nil
}

type NullableMCPProxyCapabilities struct {
	value *MCPProxyCapabilities
	isSet bool
}

func (v NullableMCPProxyCapabilities) Get() *MCPProxyCapabilities {
	return v.value
}

func (v *NullableMCPProxyCapabilities) Set(val *MCPProxyCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyCapabilities(val *MCPProxyCapabilities) *NullableMCPProxyCapabilities {
	return &NullableMCPProxyCapabilities{value: val, isSet: true}
}

func (v NullableMCPProxyCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
