/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the MCPProxyScopeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyScopeResponse{}

// MCPProxyScopeResponse struct for MCPProxyScopeResponse
type MCPProxyScopeResponse struct {
	Action string `json:"action"`
	// Derived token scope string (\"<proxy-handle>:<action>\").
	Scope       string     `json:"scope"`
	Description *string    `json:"description,omitempty"`
	Tools       []string   `json:"tools"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

// NewMCPProxyScopeResponse instantiates a new MCPProxyScopeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyScopeResponse(action string, scope string, tools []string) *MCPProxyScopeResponse {
	this := MCPProxyScopeResponse{}
	this.Action = action
	this.Scope = scope
	this.Tools = tools
	return &this
}

// NewMCPProxyScopeResponseWithDefaults instantiates a new MCPProxyScopeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyScopeResponseWithDefaults() *MCPProxyScopeResponse {
	this := MCPProxyScopeResponse{}
	return &this
}

// GetAction returns the Action field value
func (o *MCPProxyScopeResponse) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MCPProxyScopeResponse) SetAction(v string) {
	o.Action = v
}

// GetScope returns the Scope field value
func (o *MCPProxyScopeResponse) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *MCPProxyScopeResponse) SetScope(v string) {
	o.Scope = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MCPProxyScopeResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MCPProxyScopeResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MCPProxyScopeResponse) SetDescription(v string) {
	o.Description = &v
}

// GetTools returns the Tools field value
func (o *MCPProxyScopeResponse) GetTools() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetToolsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools, true
}

// SetTools sets field value
func (o *MCPProxyScopeResponse) SetTools(v []string) {
	o.Tools = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MCPProxyScopeResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MCPProxyScopeResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MCPProxyScopeResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MCPProxyScopeResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyScopeResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MCPProxyScopeResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *MCPProxyScopeResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o MCPProxyScopeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyScopeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["scope"] = o.Scope
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["tools"] = o.Tools
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMCPProxyScopeResponse struct {
	value *MCPProxyScopeResponse
	isSet bool
}

func (v NullableMCPProxyScopeResponse) Get() *MCPProxyScopeResponse {
	return v.value
}

func (v *NullableMCPProxyScopeResponse) Set(val *MCPProxyScopeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyScopeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyScopeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyScopeResponse(val *MCPProxyScopeResponse) *NullableMCPProxyScopeResponse {
	return &NullableMCPProxyScopeResponse{value: val, isSet: true}
}

func (v NullableMCPProxyScopeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyScopeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
