/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPServerInfoFetchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPServerInfoFetchResponse{}

// MCPServerInfoFetchResponse struct for MCPServerInfoFetchResponse
type MCPServerInfoFetchResponse struct {
	// MCP server metadata returned by initialize
	ServerInfo map[string]interface{}   `json:"serverInfo,omitempty"`
	Prompts    []map[string]interface{} `json:"prompts,omitempty"`
	Resources  []map[string]interface{} `json:"resources,omitempty"`
	Tools      []map[string]interface{} `json:"tools,omitempty"`
}

// NewMCPServerInfoFetchResponse instantiates a new MCPServerInfoFetchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPServerInfoFetchResponse() *MCPServerInfoFetchResponse {
	this := MCPServerInfoFetchResponse{}
	return &this
}

// NewMCPServerInfoFetchResponseWithDefaults instantiates a new MCPServerInfoFetchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPServerInfoFetchResponseWithDefaults() *MCPServerInfoFetchResponse {
	this := MCPServerInfoFetchResponse{}
	return &this
}

// GetServerInfo returns the ServerInfo field value if set, zero value otherwise.
func (o *MCPServerInfoFetchResponse) GetServerInfo() map[string]interface{} {
	if o == nil || IsNil(o.ServerInfo) {
		var ret map[string]interface{}
		return ret
	}
	return o.ServerInfo
}

// GetServerInfoOk returns a tuple with the ServerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchResponse) GetServerInfoOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ServerInfo) {
		return map[string]interface{}{}, false
	}
	return o.ServerInfo, true
}

// HasServerInfo returns a boolean if a field has been set.
func (o *MCPServerInfoFetchResponse) HasServerInfo() bool {
	if o != nil && !IsNil(o.ServerInfo) {
		return true
	}

	return false
}

// SetServerInfo gets a reference to the given map[string]interface{} and assigns it to the ServerInfo field.
func (o *MCPServerInfoFetchResponse) SetServerInfo(v map[string]interface{}) {
	o.ServerInfo = v
}

// GetPrompts returns the Prompts field value if set, zero value otherwise.
func (o *MCPServerInfoFetchResponse) GetPrompts() []map[string]interface{} {
	if o == nil || IsNil(o.Prompts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Prompts
}

// GetPromptsOk returns a tuple with the Prompts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchResponse) GetPromptsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Prompts) {
		return nil, false
	}
	return o.Prompts, true
}

// HasPrompts returns a boolean if a field has been set.
func (o *MCPServerInfoFetchResponse) HasPrompts() bool {
	if o != nil && !IsNil(o.Prompts) {
		return true
	}

	return false
}

// SetPrompts gets a reference to the given []map[string]interface{} and assigns it to the Prompts field.
func (o *MCPServerInfoFetchResponse) SetPrompts(v []map[string]interface{}) {
	o.Prompts = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *MCPServerInfoFetchResponse) GetResources() []map[string]interface{} {
	if o == nil || IsNil(o.Resources) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchResponse) GetResourcesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *MCPServerInfoFetchResponse) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []map[string]interface{} and assigns it to the Resources field.
func (o *MCPServerInfoFetchResponse) SetResources(v []map[string]interface{}) {
	o.Resources = v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *MCPServerInfoFetchResponse) GetTools() []map[string]interface{} {
	if o == nil || IsNil(o.Tools) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchResponse) GetToolsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *MCPServerInfoFetchResponse) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []map[string]interface{} and assigns it to the Tools field.
func (o *MCPServerInfoFetchResponse) SetTools(v []map[string]interface{}) {
	o.Tools = v
}

func (o MCPServerInfoFetchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPServerInfoFetchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServerInfo) {
		toSerialize["serverInfo"] = o.ServerInfo
	}
	if !IsNil(o.Prompts) {
		toSerialize["prompts"] = o.Prompts
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	return toSerialize, nil
}

type NullableMCPServerInfoFetchResponse struct {
	value *MCPServerInfoFetchResponse
	isSet bool
}

func (v NullableMCPServerInfoFetchResponse) Get() *MCPServerInfoFetchResponse {
	return v.value
}

func (v *NullableMCPServerInfoFetchResponse) Set(val *MCPServerInfoFetchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPServerInfoFetchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPServerInfoFetchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPServerInfoFetchResponse(val *MCPServerInfoFetchResponse) *NullableMCPServerInfoFetchResponse {
	return &NullableMCPServerInfoFetchResponse{value: val, isSet: true}
}

func (v NullableMCPServerInfoFetchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPServerInfoFetchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
