/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityGroupRequest{}

// AgentIdentityGroupRequest struct for AgentIdentityGroupRequest
type AgentIdentityGroupRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

// NewAgentIdentityGroupRequest instantiates a new AgentIdentityGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityGroupRequest(name string) *AgentIdentityGroupRequest {
	this := AgentIdentityGroupRequest{}
	this.Name = name
	return &this
}

// NewAgentIdentityGroupRequestWithDefaults instantiates a new AgentIdentityGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityGroupRequestWithDefaults() *AgentIdentityGroupRequest {
	this := AgentIdentityGroupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AgentIdentityGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentIdentityGroupRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentIdentityGroupRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityGroupRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentIdentityGroupRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentIdentityGroupRequest) SetDescription(v string) {
	o.Description = &v
}

func (o AgentIdentityGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableAgentIdentityGroupRequest struct {
	value *AgentIdentityGroupRequest
	isSet bool
}

func (v NullableAgentIdentityGroupRequest) Get() *AgentIdentityGroupRequest {
	return v.value
}

func (v *NullableAgentIdentityGroupRequest) Set(val *AgentIdentityGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityGroupRequest(val *AgentIdentityGroupRequest) *NullableAgentIdentityGroupRequest {
	return &NullableAgentIdentityGroupRequest{value: val, isSet: true}
}

func (v NullableAgentIdentityGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
