/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ScopeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScopeRequest{}

// ScopeRequest struct for ScopeRequest
type ScopeRequest struct {
	// Scope name (org-global, resource-agnostic)
	Name string `json:"name"`
	// Human-readable description of the scope
	Description *string `json:"description,omitempty"`
}

// NewScopeRequest instantiates a new ScopeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeRequest(name string) *ScopeRequest {
	this := ScopeRequest{}
	this.Name = name
	return &this
}

// NewScopeRequestWithDefaults instantiates a new ScopeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeRequestWithDefaults() *ScopeRequest {
	this := ScopeRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ScopeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScopeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScopeRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScopeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScopeRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScopeRequest) SetDescription(v string) {
	o.Description = &v
}

func (o ScopeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScopeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableScopeRequest struct {
	value *ScopeRequest
	isSet bool
}

func (v NullableScopeRequest) Get() *ScopeRequest {
	return v.value
}

func (v *NullableScopeRequest) Set(val *ScopeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeRequest(val *ScopeRequest) *NullableScopeRequest {
	return &NullableScopeRequest{value: val, isSet: true}
}

func (v NullableScopeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
