/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityScopeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityScopeListResponse{}

// AgentIdentityScopeListResponse struct for AgentIdentityScopeListResponse
type AgentIdentityScopeListResponse struct {
	Scopes []AgentIdentityScopeEntry `json:"scopes"`
}

// NewAgentIdentityScopeListResponse instantiates a new AgentIdentityScopeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityScopeListResponse(scopes []AgentIdentityScopeEntry) *AgentIdentityScopeListResponse {
	this := AgentIdentityScopeListResponse{}
	this.Scopes = scopes
	return &this
}

// NewAgentIdentityScopeListResponseWithDefaults instantiates a new AgentIdentityScopeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityScopeListResponseWithDefaults() *AgentIdentityScopeListResponse {
	this := AgentIdentityScopeListResponse{}
	return &this
}

// GetScopes returns the Scopes field value
func (o *AgentIdentityScopeListResponse) GetScopes() []AgentIdentityScopeEntry {
	if o == nil {
		var ret []AgentIdentityScopeEntry
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityScopeListResponse) GetScopesOk() ([]AgentIdentityScopeEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *AgentIdentityScopeListResponse) SetScopes(v []AgentIdentityScopeEntry) {
	o.Scopes = v
}

func (o AgentIdentityScopeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityScopeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scopes"] = o.Scopes
	return toSerialize, nil
}

type NullableAgentIdentityScopeListResponse struct {
	value *AgentIdentityScopeListResponse
	isSet bool
}

func (v NullableAgentIdentityScopeListResponse) Get() *AgentIdentityScopeListResponse {
	return v.value
}

func (v *NullableAgentIdentityScopeListResponse) Set(val *AgentIdentityScopeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityScopeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityScopeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityScopeListResponse(val *AgentIdentityScopeListResponse) *NullableAgentIdentityScopeListResponse {
	return &NullableAgentIdentityScopeListResponse{value: val, isSet: true}
}

func (v NullableAgentIdentityScopeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityScopeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
