/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UserListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserListResponse{}

// UserListResponse struct for UserListResponse
type UserListResponse struct {
	Users []UserResponse `json:"users"`
	// Total number of users
	Total int32 `json:"total"`
	// Number of results skipped
	Offset int32 `json:"offset"`
	// Maximum results returned
	Limit int32 `json:"limit"`
}

// NewUserListResponse instantiates a new UserListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserListResponse(users []UserResponse, total int32, offset int32, limit int32) *UserListResponse {
	this := UserListResponse{}
	this.Users = users
	this.Total = total
	this.Offset = offset
	this.Limit = limit
	return &this
}

// NewUserListResponseWithDefaults instantiates a new UserListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserListResponseWithDefaults() *UserListResponse {
	this := UserListResponse{}
	return &this
}

// GetUsers returns the Users field value
func (o *UserListResponse) GetUsers() []UserResponse {
	if o == nil {
		var ret []UserResponse
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *UserListResponse) GetUsersOk() ([]UserResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *UserListResponse) SetUsers(v []UserResponse) {
	o.Users = v
}

// GetTotal returns the Total field value
func (o *UserListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *UserListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *UserListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetOffset returns the Offset field value
func (o *UserListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *UserListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *UserListResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetLimit returns the Limit field value
func (o *UserListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *UserListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *UserListResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o UserListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	toSerialize["total"] = o.Total
	toSerialize["offset"] = o.Offset
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

type NullableUserListResponse struct {
	value *UserListResponse
	isSet bool
}

func (v NullableUserListResponse) Get() *UserListResponse {
	return v.value
}

func (v *NullableUserListResponse) Set(val *UserListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserListResponse(val *UserListResponse) *NullableUserListResponse {
	return &NullableUserListResponse{value: val, isSet: true}
}

func (v NullableUserListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
