/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the MCPProxyListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyListItem{}

// MCPProxyListItem struct for MCPProxyListItem
type MCPProxyListItem struct {
	// Unique handle for the MCP proxy
	Id *string `json:"id,omitempty"`
	// Human-readable name of the MCP proxy
	Name *string `json:"name,omitempty"`
	// Description of the MCP proxy
	Description *string `json:"description,omitempty"`
	// Version of the MCP proxy
	Version *string `json:"version,omitempty"`
	// MCP proxy context path
	Context *string `json:"context,omitempty"`
	// MCP specification version implemented by the upstream server
	McpSpecVersion *string `json:"mcpSpecVersion,omitempty"`
	// MCP proxy status
	Status *string `json:"status,omitempty"`
	// User who created the MCP proxy
	CreatedBy *string `json:"createdBy,omitempty"`
	// Timestamp when the resource was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Timestamp when the resource was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewMCPProxyListItem instantiates a new MCPProxyListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyListItem() *MCPProxyListItem {
	this := MCPProxyListItem{}
	return &this
}

// NewMCPProxyListItemWithDefaults instantiates a new MCPProxyListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyListItemWithDefaults() *MCPProxyListItem {
	this := MCPProxyListItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MCPProxyListItem) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MCPProxyListItem) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MCPProxyListItem) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *MCPProxyListItem) SetVersion(v string) {
	o.Version = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *MCPProxyListItem) SetContext(v string) {
	o.Context = &v
}

// GetMcpSpecVersion returns the McpSpecVersion field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetMcpSpecVersion() string {
	if o == nil || IsNil(o.McpSpecVersion) {
		var ret string
		return ret
	}
	return *o.McpSpecVersion
}

// GetMcpSpecVersionOk returns a tuple with the McpSpecVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetMcpSpecVersionOk() (*string, bool) {
	if o == nil || IsNil(o.McpSpecVersion) {
		return nil, false
	}
	return o.McpSpecVersion, true
}

// HasMcpSpecVersion returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasMcpSpecVersion() bool {
	if o != nil && !IsNil(o.McpSpecVersion) {
		return true
	}

	return false
}

// SetMcpSpecVersion gets a reference to the given string and assigns it to the McpSpecVersion field.
func (o *MCPProxyListItem) SetMcpSpecVersion(v string) {
	o.McpSpecVersion = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MCPProxyListItem) SetStatus(v string) {
	o.Status = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *MCPProxyListItem) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MCPProxyListItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MCPProxyListItem) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyListItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MCPProxyListItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *MCPProxyListItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o MCPProxyListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.McpSpecVersion) {
		toSerialize["mcpSpecVersion"] = o.McpSpecVersion
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMCPProxyListItem struct {
	value *MCPProxyListItem
	isSet bool
}

func (v NullableMCPProxyListItem) Get() *MCPProxyListItem {
	return v.value
}

func (v *NullableMCPProxyListItem) Set(val *MCPProxyListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyListItem(val *MCPProxyListItem) *NullableMCPProxyListItem {
	return &NullableMCPProxyListItem{value: val, isSet: true}
}

func (v NullableMCPProxyListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
