/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupResponse{}

// GroupResponse struct for GroupResponse
type GroupResponse struct {
	// Group ID
	Id string `json:"id"`
	// Group name
	Name string `json:"name"`
	// Group description
	Description *string `json:"description,omitempty"`
	// Organization unit ID
	OuId *string `json:"ouId,omitempty"`
}

// NewGroupResponse instantiates a new GroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupResponse(id string, name string) *GroupResponse {
	this := GroupResponse{}
	this.Id = id
	this.Name = name
	return &this
}

// NewGroupResponseWithDefaults instantiates a new GroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupResponseWithDefaults() *GroupResponse {
	this := GroupResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GroupResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GroupResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GroupResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GroupResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GroupResponse) SetDescription(v string) {
	o.Description = &v
}

// GetOuId returns the OuId field value if set, zero value otherwise.
func (o *GroupResponse) GetOuId() string {
	if o == nil || IsNil(o.OuId) {
		var ret string
		return ret
	}
	return *o.OuId
}

// GetOuIdOk returns a tuple with the OuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetOuIdOk() (*string, bool) {
	if o == nil || IsNil(o.OuId) {
		return nil, false
	}
	return o.OuId, true
}

// HasOuId returns a boolean if a field has been set.
func (o *GroupResponse) HasOuId() bool {
	if o != nil && !IsNil(o.OuId) {
		return true
	}

	return false
}

// SetOuId gets a reference to the given string and assigns it to the OuId field.
func (o *GroupResponse) SetOuId(v string) {
	o.OuId = &v
}

func (o GroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.OuId) {
		toSerialize["ouId"] = o.OuId
	}
	return toSerialize, nil
}

type NullableGroupResponse struct {
	value *GroupResponse
	isSet bool
}

func (v NullableGroupResponse) Get() *GroupResponse {
	return v.value
}

func (v *NullableGroupResponse) Set(val *GroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupResponse(val *GroupResponse) *NullableGroupResponse {
	return &NullableGroupResponse{value: val, isSet: true}
}

func (v NullableGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
