/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpsertKeyManagerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertKeyManagerRequest{}

// UpsertKeyManagerRequest Request body for creating or updating a gateway key manager (name is taken from the path).
type UpsertKeyManagerRequest struct {
	// Expected `iss` claim value for tokens validated by this key manager.
	Issuer *string `json:"issuer,omitempty"`
	// Remote JWKS endpoint used to fetch signing keys.
	JwksUri *string `json:"jwksUri,omitempty"`
	// Skip TLS verification when fetching the JWKS endpoint.
	SkipTlsVerify *bool `json:"skipTlsVerify,omitempty"`
}

// NewUpsertKeyManagerRequest instantiates a new UpsertKeyManagerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertKeyManagerRequest() *UpsertKeyManagerRequest {
	this := UpsertKeyManagerRequest{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// NewUpsertKeyManagerRequestWithDefaults instantiates a new UpsertKeyManagerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertKeyManagerRequestWithDefaults() *UpsertKeyManagerRequest {
	this := UpsertKeyManagerRequest{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *UpsertKeyManagerRequest) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertKeyManagerRequest) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *UpsertKeyManagerRequest) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *UpsertKeyManagerRequest) SetIssuer(v string) {
	o.Issuer = &v
}

// GetJwksUri returns the JwksUri field value if set, zero value otherwise.
func (o *UpsertKeyManagerRequest) GetJwksUri() string {
	if o == nil || IsNil(o.JwksUri) {
		var ret string
		return ret
	}
	return *o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertKeyManagerRequest) GetJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUri) {
		return nil, false
	}
	return o.JwksUri, true
}

// HasJwksUri returns a boolean if a field has been set.
func (o *UpsertKeyManagerRequest) HasJwksUri() bool {
	if o != nil && !IsNil(o.JwksUri) {
		return true
	}

	return false
}

// SetJwksUri gets a reference to the given string and assigns it to the JwksUri field.
func (o *UpsertKeyManagerRequest) SetJwksUri(v string) {
	o.JwksUri = &v
}

// GetSkipTlsVerify returns the SkipTlsVerify field value if set, zero value otherwise.
func (o *UpsertKeyManagerRequest) GetSkipTlsVerify() bool {
	if o == nil || IsNil(o.SkipTlsVerify) {
		var ret bool
		return ret
	}
	return *o.SkipTlsVerify
}

// GetSkipTlsVerifyOk returns a tuple with the SkipTlsVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertKeyManagerRequest) GetSkipTlsVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipTlsVerify) {
		return nil, false
	}
	return o.SkipTlsVerify, true
}

// HasSkipTlsVerify returns a boolean if a field has been set.
func (o *UpsertKeyManagerRequest) HasSkipTlsVerify() bool {
	if o != nil && !IsNil(o.SkipTlsVerify) {
		return true
	}

	return false
}

// SetSkipTlsVerify gets a reference to the given bool and assigns it to the SkipTlsVerify field.
func (o *UpsertKeyManagerRequest) SetSkipTlsVerify(v bool) {
	o.SkipTlsVerify = &v
}

func (o UpsertKeyManagerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertKeyManagerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.JwksUri) {
		toSerialize["jwksUri"] = o.JwksUri
	}
	if !IsNil(o.SkipTlsVerify) {
		toSerialize["skipTlsVerify"] = o.SkipTlsVerify
	}
	return toSerialize, nil
}

type NullableUpsertKeyManagerRequest struct {
	value *UpsertKeyManagerRequest
	isSet bool
}

func (v NullableUpsertKeyManagerRequest) Get() *UpsertKeyManagerRequest {
	return v.value
}

func (v *NullableUpsertKeyManagerRequest) Set(val *UpsertKeyManagerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertKeyManagerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertKeyManagerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertKeyManagerRequest(val *UpsertKeyManagerRequest) *NullableUpsertKeyManagerRequest {
	return &NullableUpsertKeyManagerRequest{value: val, isSet: true}
}

func (v NullableUpsertKeyManagerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertKeyManagerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
