/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityAssignmentsRequestAssignmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityAssignmentsRequestAssignmentsInner{}

// AgentIdentityAssignmentsRequestAssignmentsInner struct for AgentIdentityAssignmentsRequestAssignmentsInner
type AgentIdentityAssignmentsRequestAssignmentsInner struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// NewAgentIdentityAssignmentsRequestAssignmentsInner instantiates a new AgentIdentityAssignmentsRequestAssignmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityAssignmentsRequestAssignmentsInner(id string, type_ string) *AgentIdentityAssignmentsRequestAssignmentsInner {
	this := AgentIdentityAssignmentsRequestAssignmentsInner{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewAgentIdentityAssignmentsRequestAssignmentsInnerWithDefaults instantiates a new AgentIdentityAssignmentsRequestAssignmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityAssignmentsRequestAssignmentsInnerWithDefaults() *AgentIdentityAssignmentsRequestAssignmentsInner {
	this := AgentIdentityAssignmentsRequestAssignmentsInner{}
	return &this
}

// GetId returns the Id field value
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AgentIdentityAssignmentsRequestAssignmentsInner) SetType(v string) {
	o.Type = v
}

func (o AgentIdentityAssignmentsRequestAssignmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityAssignmentsRequestAssignmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableAgentIdentityAssignmentsRequestAssignmentsInner struct {
	value *AgentIdentityAssignmentsRequestAssignmentsInner
	isSet bool
}

func (v NullableAgentIdentityAssignmentsRequestAssignmentsInner) Get() *AgentIdentityAssignmentsRequestAssignmentsInner {
	return v.value
}

func (v *NullableAgentIdentityAssignmentsRequestAssignmentsInner) Set(val *AgentIdentityAssignmentsRequestAssignmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityAssignmentsRequestAssignmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityAssignmentsRequestAssignmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityAssignmentsRequestAssignmentsInner(val *AgentIdentityAssignmentsRequestAssignmentsInner) *NullableAgentIdentityAssignmentsRequestAssignmentsInner {
	return &NullableAgentIdentityAssignmentsRequestAssignmentsInner{value: val, isSet: true}
}

func (v NullableAgentIdentityAssignmentsRequestAssignmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityAssignmentsRequestAssignmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
