/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityRoleRequest{}

// AgentIdentityRoleRequest struct for AgentIdentityRoleRequest
type AgentIdentityRoleRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// Scope strings (\"<proxy-handle>:<action>\") carried as the role's permissions.
	Scopes []string `json:"scopes,omitempty"`
}

// NewAgentIdentityRoleRequest instantiates a new AgentIdentityRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityRoleRequest(name string) *AgentIdentityRoleRequest {
	this := AgentIdentityRoleRequest{}
	this.Name = name
	return &this
}

// NewAgentIdentityRoleRequestWithDefaults instantiates a new AgentIdentityRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityRoleRequestWithDefaults() *AgentIdentityRoleRequest {
	this := AgentIdentityRoleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AgentIdentityRoleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentIdentityRoleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentIdentityRoleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentIdentityRoleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentIdentityRoleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AgentIdentityRoleRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AgentIdentityRoleRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AgentIdentityRoleRequest) SetScopes(v []string) {
	o.Scopes = v
}

func (o AgentIdentityRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	return toSerialize, nil
}

type NullableAgentIdentityRoleRequest struct {
	value *AgentIdentityRoleRequest
	isSet bool
}

func (v NullableAgentIdentityRoleRequest) Get() *AgentIdentityRoleRequest {
	return v.value
}

func (v *NullableAgentIdentityRoleRequest) Set(val *AgentIdentityRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityRoleRequest(val *AgentIdentityRoleRequest) *NullableAgentIdentityRoleRequest {
	return &NullableAgentIdentityRoleRequest{value: val, isSet: true}
}

func (v NullableAgentIdentityRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
