/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityActionRequest{}

// AgentIdentityActionRequest Request body for regenerating an AgentID secret
type AgentIdentityActionRequest struct {
	// Environment name to regenerate the AgentID secret in
	Environment string `json:"environment"`
}

// NewAgentIdentityActionRequest instantiates a new AgentIdentityActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityActionRequest(environment string) *AgentIdentityActionRequest {
	this := AgentIdentityActionRequest{}
	this.Environment = environment
	return &this
}

// NewAgentIdentityActionRequestWithDefaults instantiates a new AgentIdentityActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityActionRequestWithDefaults() *AgentIdentityActionRequest {
	this := AgentIdentityActionRequest{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *AgentIdentityActionRequest) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityActionRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *AgentIdentityActionRequest) SetEnvironment(v string) {
	o.Environment = v
}

func (o AgentIdentityActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment
	return toSerialize, nil
}

type NullableAgentIdentityActionRequest struct {
	value *AgentIdentityActionRequest
	isSet bool
}

func (v NullableAgentIdentityActionRequest) Get() *AgentIdentityActionRequest {
	return v.value
}

func (v *NullableAgentIdentityActionRequest) Set(val *AgentIdentityActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityActionRequest(val *AgentIdentityActionRequest) *NullableAgentIdentityActionRequest {
	return &NullableAgentIdentityActionRequest{value: val, isSet: true}
}

func (v NullableAgentIdentityActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
