/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the KeyManager type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyManager{}

// KeyManager A JWT key manager (token issuer) configured on a gateway. Mirrors a gateway-side jwt-auth `system.keyManagers` entry. Only the fields needed to identify an issuer and validate its tokens are surfaced.
type KeyManager struct {
	// Unique key manager name within the gateway (referenced as an issuer).
	Name string `json:"name"`
	// Expected `iss` claim value for tokens validated by this key manager.
	Issuer *string `json:"issuer,omitempty"`
	// Remote JWKS endpoint used to fetch signing keys.
	JwksUri *string `json:"jwksUri,omitempty"`
	// Skip TLS verification when fetching the JWKS endpoint (testing/trusted internal only).
	SkipTlsVerify *bool `json:"skipTlsVerify,omitempty"`
}

// NewKeyManager instantiates a new KeyManager object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyManager(name string) *KeyManager {
	this := KeyManager{}
	this.Name = name
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// NewKeyManagerWithDefaults instantiates a new KeyManager object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyManagerWithDefaults() *KeyManager {
	this := KeyManager{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// GetName returns the Name field value
func (o *KeyManager) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KeyManager) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KeyManager) SetName(v string) {
	o.Name = v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *KeyManager) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyManager) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *KeyManager) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *KeyManager) SetIssuer(v string) {
	o.Issuer = &v
}

// GetJwksUri returns the JwksUri field value if set, zero value otherwise.
func (o *KeyManager) GetJwksUri() string {
	if o == nil || IsNil(o.JwksUri) {
		var ret string
		return ret
	}
	return *o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyManager) GetJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUri) {
		return nil, false
	}
	return o.JwksUri, true
}

// HasJwksUri returns a boolean if a field has been set.
func (o *KeyManager) HasJwksUri() bool {
	if o != nil && !IsNil(o.JwksUri) {
		return true
	}

	return false
}

// SetJwksUri gets a reference to the given string and assigns it to the JwksUri field.
func (o *KeyManager) SetJwksUri(v string) {
	o.JwksUri = &v
}

// GetSkipTlsVerify returns the SkipTlsVerify field value if set, zero value otherwise.
func (o *KeyManager) GetSkipTlsVerify() bool {
	if o == nil || IsNil(o.SkipTlsVerify) {
		var ret bool
		return ret
	}
	return *o.SkipTlsVerify
}

// GetSkipTlsVerifyOk returns a tuple with the SkipTlsVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyManager) GetSkipTlsVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipTlsVerify) {
		return nil, false
	}
	return o.SkipTlsVerify, true
}

// HasSkipTlsVerify returns a boolean if a field has been set.
func (o *KeyManager) HasSkipTlsVerify() bool {
	if o != nil && !IsNil(o.SkipTlsVerify) {
		return true
	}

	return false
}

// SetSkipTlsVerify gets a reference to the given bool and assigns it to the SkipTlsVerify field.
func (o *KeyManager) SetSkipTlsVerify(v bool) {
	o.SkipTlsVerify = &v
}

func (o KeyManager) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyManager) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.JwksUri) {
		toSerialize["jwksUri"] = o.JwksUri
	}
	if !IsNil(o.SkipTlsVerify) {
		toSerialize["skipTlsVerify"] = o.SkipTlsVerify
	}
	return toSerialize, nil
}

type NullableKeyManager struct {
	value *KeyManager
	isSet bool
}

func (v NullableKeyManager) Get() *KeyManager {
	return v.value
}

func (v *NullableKeyManager) Set(val *KeyManager) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyManager) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyManager) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyManager(val *KeyManager) *NullableKeyManager {
	return &NullableKeyManager{value: val, isSet: true}
}

func (v NullableKeyManager) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyManager) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
