/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPServerInfoFetchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPServerInfoFetchRequest{}

// MCPServerInfoFetchRequest struct for MCPServerInfoFetchRequest
type MCPServerInfoFetchRequest struct {
	// MCP server endpoint URL
	Url *string `json:"url,omitempty"`
	// Existing MCP proxy ID to refresh from. Currently unsupported by the backend.
	ProxyId *string       `json:"proxyId,omitempty"`
	Auth    *UpstreamAuth `json:"auth,omitempty"`
}

// NewMCPServerInfoFetchRequest instantiates a new MCPServerInfoFetchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPServerInfoFetchRequest() *MCPServerInfoFetchRequest {
	this := MCPServerInfoFetchRequest{}
	return &this
}

// NewMCPServerInfoFetchRequestWithDefaults instantiates a new MCPServerInfoFetchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPServerInfoFetchRequestWithDefaults() *MCPServerInfoFetchRequest {
	this := MCPServerInfoFetchRequest{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *MCPServerInfoFetchRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *MCPServerInfoFetchRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *MCPServerInfoFetchRequest) SetUrl(v string) {
	o.Url = &v
}

// GetProxyId returns the ProxyId field value if set, zero value otherwise.
func (o *MCPServerInfoFetchRequest) GetProxyId() string {
	if o == nil || IsNil(o.ProxyId) {
		var ret string
		return ret
	}
	return *o.ProxyId
}

// GetProxyIdOk returns a tuple with the ProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchRequest) GetProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyId) {
		return nil, false
	}
	return o.ProxyId, true
}

// HasProxyId returns a boolean if a field has been set.
func (o *MCPServerInfoFetchRequest) HasProxyId() bool {
	if o != nil && !IsNil(o.ProxyId) {
		return true
	}

	return false
}

// SetProxyId gets a reference to the given string and assigns it to the ProxyId field.
func (o *MCPServerInfoFetchRequest) SetProxyId(v string) {
	o.ProxyId = &v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *MCPServerInfoFetchRequest) GetAuth() UpstreamAuth {
	if o == nil || IsNil(o.Auth) {
		var ret UpstreamAuth
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPServerInfoFetchRequest) GetAuthOk() (*UpstreamAuth, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *MCPServerInfoFetchRequest) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given UpstreamAuth and assigns it to the Auth field.
func (o *MCPServerInfoFetchRequest) SetAuth(v UpstreamAuth) {
	o.Auth = &v
}

func (o MCPServerInfoFetchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPServerInfoFetchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.ProxyId) {
		toSerialize["proxyId"] = o.ProxyId
	}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	return toSerialize, nil
}

type NullableMCPServerInfoFetchRequest struct {
	value *MCPServerInfoFetchRequest
	isSet bool
}

func (v NullableMCPServerInfoFetchRequest) Get() *MCPServerInfoFetchRequest {
	return v.value
}

func (v *NullableMCPServerInfoFetchRequest) Set(val *MCPServerInfoFetchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPServerInfoFetchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPServerInfoFetchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPServerInfoFetchRequest(val *MCPServerInfoFetchRequest) *NullableMCPServerInfoFetchRequest {
	return &NullableMCPServerInfoFetchRequest{value: val, isSet: true}
}

func (v NullableMCPServerInfoFetchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPServerInfoFetchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
