/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the MCPProxyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyResponse{}

// MCPProxyResponse struct for MCPProxyResponse
type MCPProxyResponse struct {
	// Unique handle for the MCP proxy
	Id string `json:"id"`
	// Human-readable name of the MCP proxy
	Name string `json:"name"`
	// Description of the MCP proxy
	Description *string `json:"description,omitempty"`
	// Version of the MCP proxy
	Version string `json:"version"`
	// MCP proxy context path
	Context *string `json:"context,omitempty"`
	// Virtual host assigned to the MCP proxy
	Vhost *string `json:"vhost,omitempty"`
	// MCP specification version implemented by the upstream server
	McpSpecVersion *string `json:"mcpSpecVersion,omitempty"`
	// Deployable endpoint definitions of the MCP proxy. Each endpoint reports its per-environment deployment status.
	Endpoints []MCPProxyEndpoint `json:"endpoints,omitempty"`
	// Whether the MCP proxy is available in the catalog
	InCatalog *bool `json:"inCatalog,omitempty"`
	// Gateway UUIDs associated with the MCP proxy
	Gateways []string `json:"gateways,omitempty"`
	// User who created the MCP proxy
	CreatedBy *string `json:"createdBy,omitempty"`
	// Timestamp when the resource was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Timestamp when the resource was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewMCPProxyResponse instantiates a new MCPProxyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyResponse(id string, name string, version string) *MCPProxyResponse {
	this := MCPProxyResponse{}
	this.Id = id
	this.Name = name
	this.Version = version
	return &this
}

// NewMCPProxyResponseWithDefaults instantiates a new MCPProxyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyResponseWithDefaults() *MCPProxyResponse {
	this := MCPProxyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *MCPProxyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MCPProxyResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *MCPProxyResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MCPProxyResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MCPProxyResponse) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value
func (o *MCPProxyResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *MCPProxyResponse) SetVersion(v string) {
	o.Version = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *MCPProxyResponse) SetContext(v string) {
	o.Context = &v
}

// GetVhost returns the Vhost field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetVhost() string {
	if o == nil || IsNil(o.Vhost) {
		var ret string
		return ret
	}
	return *o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetVhostOk() (*string, bool) {
	if o == nil || IsNil(o.Vhost) {
		return nil, false
	}
	return o.Vhost, true
}

// HasVhost returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasVhost() bool {
	if o != nil && !IsNil(o.Vhost) {
		return true
	}

	return false
}

// SetVhost gets a reference to the given string and assigns it to the Vhost field.
func (o *MCPProxyResponse) SetVhost(v string) {
	o.Vhost = &v
}

// GetMcpSpecVersion returns the McpSpecVersion field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetMcpSpecVersion() string {
	if o == nil || IsNil(o.McpSpecVersion) {
		var ret string
		return ret
	}
	return *o.McpSpecVersion
}

// GetMcpSpecVersionOk returns a tuple with the McpSpecVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetMcpSpecVersionOk() (*string, bool) {
	if o == nil || IsNil(o.McpSpecVersion) {
		return nil, false
	}
	return o.McpSpecVersion, true
}

// HasMcpSpecVersion returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasMcpSpecVersion() bool {
	if o != nil && !IsNil(o.McpSpecVersion) {
		return true
	}

	return false
}

// SetMcpSpecVersion gets a reference to the given string and assigns it to the McpSpecVersion field.
func (o *MCPProxyResponse) SetMcpSpecVersion(v string) {
	o.McpSpecVersion = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetEndpoints() []MCPProxyEndpoint {
	if o == nil || IsNil(o.Endpoints) {
		var ret []MCPProxyEndpoint
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetEndpointsOk() ([]MCPProxyEndpoint, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []MCPProxyEndpoint and assigns it to the Endpoints field.
func (o *MCPProxyResponse) SetEndpoints(v []MCPProxyEndpoint) {
	o.Endpoints = v
}

// GetInCatalog returns the InCatalog field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetInCatalog() bool {
	if o == nil || IsNil(o.InCatalog) {
		var ret bool
		return ret
	}
	return *o.InCatalog
}

// GetInCatalogOk returns a tuple with the InCatalog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetInCatalogOk() (*bool, bool) {
	if o == nil || IsNil(o.InCatalog) {
		return nil, false
	}
	return o.InCatalog, true
}

// HasInCatalog returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasInCatalog() bool {
	if o != nil && !IsNil(o.InCatalog) {
		return true
	}

	return false
}

// SetInCatalog gets a reference to the given bool and assigns it to the InCatalog field.
func (o *MCPProxyResponse) SetInCatalog(v bool) {
	o.InCatalog = &v
}

// GetGateways returns the Gateways field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetGateways() []string {
	if o == nil || IsNil(o.Gateways) {
		var ret []string
		return ret
	}
	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetGatewaysOk() ([]string, bool) {
	if o == nil || IsNil(o.Gateways) {
		return nil, false
	}
	return o.Gateways, true
}

// HasGateways returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasGateways() bool {
	if o != nil && !IsNil(o.Gateways) {
		return true
	}

	return false
}

// SetGateways gets a reference to the given []string and assigns it to the Gateways field.
func (o *MCPProxyResponse) SetGateways(v []string) {
	o.Gateways = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *MCPProxyResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MCPProxyResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MCPProxyResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MCPProxyResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *MCPProxyResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o MCPProxyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["version"] = o.Version
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Vhost) {
		toSerialize["vhost"] = o.Vhost
	}
	if !IsNil(o.McpSpecVersion) {
		toSerialize["mcpSpecVersion"] = o.McpSpecVersion
	}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	if !IsNil(o.InCatalog) {
		toSerialize["inCatalog"] = o.InCatalog
	}
	if !IsNil(o.Gateways) {
		toSerialize["gateways"] = o.Gateways
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMCPProxyResponse struct {
	value *MCPProxyResponse
	isSet bool
}

func (v NullableMCPProxyResponse) Get() *MCPProxyResponse {
	return v.value
}

func (v *NullableMCPProxyResponse) Set(val *MCPProxyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyResponse(val *MCPProxyResponse) *NullableMCPProxyResponse {
	return &NullableMCPProxyResponse{value: val, isSet: true}
}

func (v NullableMCPProxyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
