/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RateLimitingScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitingScope{}

// RateLimitingScope Scope-level rate limiting summary
type RateLimitingScope struct {
	// Whether global rate limiting is enabled
	GlobalEnabled *bool `json:"globalEnabled,omitempty"`
	// Whether resource-wise rate limiting is enabled
	ResourceWiseEnabled *bool           `json:"resourceWiseEnabled,omitempty"`
	Request             *RateLimitEntry `json:"request,omitempty"`
	Token               *RateLimitEntry `json:"token,omitempty"`
	Cost                *RateLimitEntry `json:"cost,omitempty"`
}

// NewRateLimitingScope instantiates a new RateLimitingScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitingScope() *RateLimitingScope {
	this := RateLimitingScope{}
	return &this
}

// NewRateLimitingScopeWithDefaults instantiates a new RateLimitingScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitingScopeWithDefaults() *RateLimitingScope {
	this := RateLimitingScope{}
	return &this
}

// GetGlobalEnabled returns the GlobalEnabled field value if set, zero value otherwise.
func (o *RateLimitingScope) GetGlobalEnabled() bool {
	if o == nil || IsNil(o.GlobalEnabled) {
		var ret bool
		return ret
	}
	return *o.GlobalEnabled
}

// GetGlobalEnabledOk returns a tuple with the GlobalEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitingScope) GetGlobalEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.GlobalEnabled) {
		return nil, false
	}
	return o.GlobalEnabled, true
}

// HasGlobalEnabled returns a boolean if a field has been set.
func (o *RateLimitingScope) HasGlobalEnabled() bool {
	if o != nil && !IsNil(o.GlobalEnabled) {
		return true
	}

	return false
}

// SetGlobalEnabled gets a reference to the given bool and assigns it to the GlobalEnabled field.
func (o *RateLimitingScope) SetGlobalEnabled(v bool) {
	o.GlobalEnabled = &v
}

// GetResourceWiseEnabled returns the ResourceWiseEnabled field value if set, zero value otherwise.
func (o *RateLimitingScope) GetResourceWiseEnabled() bool {
	if o == nil || IsNil(o.ResourceWiseEnabled) {
		var ret bool
		return ret
	}
	return *o.ResourceWiseEnabled
}

// GetResourceWiseEnabledOk returns a tuple with the ResourceWiseEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitingScope) GetResourceWiseEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ResourceWiseEnabled) {
		return nil, false
	}
	return o.ResourceWiseEnabled, true
}

// HasResourceWiseEnabled returns a boolean if a field has been set.
func (o *RateLimitingScope) HasResourceWiseEnabled() bool {
	if o != nil && !IsNil(o.ResourceWiseEnabled) {
		return true
	}

	return false
}

// SetResourceWiseEnabled gets a reference to the given bool and assigns it to the ResourceWiseEnabled field.
func (o *RateLimitingScope) SetResourceWiseEnabled(v bool) {
	o.ResourceWiseEnabled = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *RateLimitingScope) GetRequest() RateLimitEntry {
	if o == nil || IsNil(o.Request) {
		var ret RateLimitEntry
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitingScope) GetRequestOk() (*RateLimitEntry, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *RateLimitingScope) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given RateLimitEntry and assigns it to the Request field.
func (o *RateLimitingScope) SetRequest(v RateLimitEntry) {
	o.Request = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *RateLimitingScope) GetToken() RateLimitEntry {
	if o == nil || IsNil(o.Token) {
		var ret RateLimitEntry
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitingScope) GetTokenOk() (*RateLimitEntry, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *RateLimitingScope) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given RateLimitEntry and assigns it to the Token field.
func (o *RateLimitingScope) SetToken(v RateLimitEntry) {
	o.Token = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *RateLimitingScope) GetCost() RateLimitEntry {
	if o == nil || IsNil(o.Cost) {
		var ret RateLimitEntry
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitingScope) GetCostOk() (*RateLimitEntry, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *RateLimitingScope) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given RateLimitEntry and assigns it to the Cost field.
func (o *RateLimitingScope) SetCost(v RateLimitEntry) {
	o.Cost = &v
}

func (o RateLimitingScope) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitingScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalEnabled) {
		toSerialize["globalEnabled"] = o.GlobalEnabled
	}
	if !IsNil(o.ResourceWiseEnabled) {
		toSerialize["resourceWiseEnabled"] = o.ResourceWiseEnabled
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	return toSerialize, nil
}

type NullableRateLimitingScope struct {
	value *RateLimitingScope
	isSet bool
}

func (v NullableRateLimitingScope) Get() *RateLimitingScope {
	return v.value
}

func (v *NullableRateLimitingScope) Set(val *RateLimitingScope) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitingScope) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitingScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitingScope(val *RateLimitingScope) *NullableRateLimitingScope {
	return &NullableRateLimitingScope{value: val, isSet: true}
}

func (v NullableRateLimitingScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitingScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
