/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPProxyListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyListResponse{}

// MCPProxyListResponse struct for MCPProxyListResponse
type MCPProxyListResponse struct {
	Count      int32              `json:"count"`
	List       []MCPProxyListItem `json:"list"`
	Pagination PaginationInfo     `json:"pagination"`
}

// NewMCPProxyListResponse instantiates a new MCPProxyListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyListResponse(count int32, list []MCPProxyListItem, pagination PaginationInfo) *MCPProxyListResponse {
	this := MCPProxyListResponse{}
	this.Count = count
	this.List = list
	this.Pagination = pagination
	return &this
}

// NewMCPProxyListResponseWithDefaults instantiates a new MCPProxyListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyListResponseWithDefaults() *MCPProxyListResponse {
	this := MCPProxyListResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *MCPProxyListResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *MCPProxyListResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *MCPProxyListResponse) SetCount(v int32) {
	o.Count = v
}

// GetList returns the List field value
func (o *MCPProxyListResponse) GetList() []MCPProxyListItem {
	if o == nil {
		var ret []MCPProxyListItem
		return ret
	}

	return o.List
}

// GetListOk returns a tuple with the List field value
// and a boolean to check if the value has been set.
func (o *MCPProxyListResponse) GetListOk() ([]MCPProxyListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.List, true
}

// SetList sets field value
func (o *MCPProxyListResponse) SetList(v []MCPProxyListItem) {
	o.List = v
}

// GetPagination returns the Pagination field value
func (o *MCPProxyListResponse) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *MCPProxyListResponse) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *MCPProxyListResponse) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

func (o MCPProxyListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["list"] = o.List
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

type NullableMCPProxyListResponse struct {
	value *MCPProxyListResponse
	isSet bool
}

func (v NullableMCPProxyListResponse) Get() *MCPProxyListResponse {
	return v.value
}

func (v *NullableMCPProxyListResponse) Set(val *MCPProxyListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyListResponse(val *MCPProxyListResponse) *NullableMCPProxyListResponse {
	return &NullableMCPProxyListResponse{value: val, isSet: true}
}

func (v NullableMCPProxyListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
