/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityAgentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityAgentListResponse{}

// AgentIdentityAgentListResponse struct for AgentIdentityAgentListResponse
type AgentIdentityAgentListResponse struct {
	Agents []AgentIdentityAgentResponse `json:"agents"`
}

// NewAgentIdentityAgentListResponse instantiates a new AgentIdentityAgentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityAgentListResponse(agents []AgentIdentityAgentResponse) *AgentIdentityAgentListResponse {
	this := AgentIdentityAgentListResponse{}
	this.Agents = agents
	return &this
}

// NewAgentIdentityAgentListResponseWithDefaults instantiates a new AgentIdentityAgentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityAgentListResponseWithDefaults() *AgentIdentityAgentListResponse {
	this := AgentIdentityAgentListResponse{}
	return &this
}

// GetAgents returns the Agents field value
func (o *AgentIdentityAgentListResponse) GetAgents() []AgentIdentityAgentResponse {
	if o == nil {
		var ret []AgentIdentityAgentResponse
		return ret
	}

	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityAgentListResponse) GetAgentsOk() ([]AgentIdentityAgentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Agents, true
}

// SetAgents sets field value
func (o *AgentIdentityAgentListResponse) SetAgents(v []AgentIdentityAgentResponse) {
	o.Agents = v
}

func (o AgentIdentityAgentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityAgentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agents"] = o.Agents
	return toSerialize, nil
}

type NullableAgentIdentityAgentListResponse struct {
	value *AgentIdentityAgentListResponse
	isSet bool
}

func (v NullableAgentIdentityAgentListResponse) Get() *AgentIdentityAgentListResponse {
	return v.value
}

func (v *NullableAgentIdentityAgentListResponse) Set(val *AgentIdentityAgentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityAgentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityAgentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityAgentListResponse(val *AgentIdentityAgentListResponse) *NullableAgentIdentityAgentListResponse {
	return &NullableAgentIdentityAgentListResponse{value: val, isSet: true}
}

func (v NullableAgentIdentityAgentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityAgentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
