/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentClaimSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentClaimSecretResponse{}

// AgentClaimSecretResponse Response for the one-time claim of an external agent's secret. This is the only response that will ever include this secret value.
type AgentClaimSecretResponse struct {
	EnvironmentName string `json:"environmentName"`
	// Thunder's own ID for this identity, different from `clientId`
	AgentId  string `json:"agentId"`
	ClientId string `json:"clientId"`
	// The OAuth2 client secret. Save it now, since it can't be fetched this way again.
	ClientSecret string `json:"clientSecret"`
	Status       string `json:"status"`
}

// NewAgentClaimSecretResponse instantiates a new AgentClaimSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentClaimSecretResponse(environmentName string, agentId string, clientId string, clientSecret string, status string) *AgentClaimSecretResponse {
	this := AgentClaimSecretResponse{}
	this.EnvironmentName = environmentName
	this.AgentId = agentId
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.Status = status
	return &this
}

// NewAgentClaimSecretResponseWithDefaults instantiates a new AgentClaimSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentClaimSecretResponseWithDefaults() *AgentClaimSecretResponse {
	this := AgentClaimSecretResponse{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *AgentClaimSecretResponse) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *AgentClaimSecretResponse) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *AgentClaimSecretResponse) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetAgentId returns the AgentId field value
func (o *AgentClaimSecretResponse) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *AgentClaimSecretResponse) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *AgentClaimSecretResponse) SetAgentId(v string) {
	o.AgentId = v
}

// GetClientId returns the ClientId field value
func (o *AgentClaimSecretResponse) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AgentClaimSecretResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AgentClaimSecretResponse) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AgentClaimSecretResponse) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AgentClaimSecretResponse) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AgentClaimSecretResponse) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetStatus returns the Status field value
func (o *AgentClaimSecretResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentClaimSecretResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentClaimSecretResponse) SetStatus(v string) {
	o.Status = v
}

func (o AgentClaimSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentClaimSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	toSerialize["agentId"] = o.AgentId
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableAgentClaimSecretResponse struct {
	value *AgentClaimSecretResponse
	isSet bool
}

func (v NullableAgentClaimSecretResponse) Get() *AgentClaimSecretResponse {
	return v.value
}

func (v *NullableAgentClaimSecretResponse) Set(val *AgentClaimSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentClaimSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentClaimSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentClaimSecretResponse(val *AgentClaimSecretResponse) *NullableAgentClaimSecretResponse {
	return &NullableAgentClaimSecretResponse{value: val, isSet: true}
}

func (v NullableAgentClaimSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentClaimSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
