/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RoleListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleListResponse{}

// RoleListResponse struct for RoleListResponse
type RoleListResponse struct {
	Roles []RoleResponse `json:"roles"`
	// Total number of roles
	Total int32 `json:"total"`
	// Number of results skipped
	Offset int32 `json:"offset"`
	// Maximum results returned
	Limit int32 `json:"limit"`
}

// NewRoleListResponse instantiates a new RoleListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleListResponse(roles []RoleResponse, total int32, offset int32, limit int32) *RoleListResponse {
	this := RoleListResponse{}
	this.Roles = roles
	this.Total = total
	this.Offset = offset
	this.Limit = limit
	return &this
}

// NewRoleListResponseWithDefaults instantiates a new RoleListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleListResponseWithDefaults() *RoleListResponse {
	this := RoleListResponse{}
	return &this
}

// GetRoles returns the Roles field value
func (o *RoleListResponse) GetRoles() []RoleResponse {
	if o == nil {
		var ret []RoleResponse
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *RoleListResponse) GetRolesOk() ([]RoleResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *RoleListResponse) SetRoles(v []RoleResponse) {
	o.Roles = v
}

// GetTotal returns the Total field value
func (o *RoleListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *RoleListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *RoleListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetOffset returns the Offset field value
func (o *RoleListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *RoleListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *RoleListResponse) SetOffset(v int32) {
	o.Offset = v
}

// GetLimit returns the Limit field value
func (o *RoleListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *RoleListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *RoleListResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o RoleListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles
	toSerialize["total"] = o.Total
	toSerialize["offset"] = o.Offset
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

type NullableRoleListResponse struct {
	value *RoleListResponse
	isSet bool
}

func (v NullableRoleListResponse) Get() *RoleListResponse {
	return v.value
}

func (v *NullableRoleListResponse) Set(val *RoleListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleListResponse(val *RoleListResponse) *NullableRoleListResponse {
	return &NullableRoleListResponse{value: val, isSet: true}
}

func (v NullableRoleListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
