/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentRevokeSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRevokeSecretResponse{}

// AgentRevokeSecretResponse Response for revoking an AgentID secret. Never includes a `clientSecret`, since revoke turns access off rather than rotating it.
type AgentRevokeSecretResponse struct {
	EnvironmentName string `json:"environmentName"`
	ClientId        string `json:"clientId"`
	Status          string `json:"status"`
	// Present when the secret was revoked successfully but the best-effort cleanup of the already-running workload's credential could not be completed or verified. The workload may keep referencing the revoked credential until this is confirmed or the workload is redeployed.
	WorkloadRefreshWarning *string `json:"workloadRefreshWarning,omitempty"`
}

// NewAgentRevokeSecretResponse instantiates a new AgentRevokeSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRevokeSecretResponse(environmentName string, clientId string, status string) *AgentRevokeSecretResponse {
	this := AgentRevokeSecretResponse{}
	this.EnvironmentName = environmentName
	this.ClientId = clientId
	this.Status = status
	return &this
}

// NewAgentRevokeSecretResponseWithDefaults instantiates a new AgentRevokeSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentRevokeSecretResponseWithDefaults() *AgentRevokeSecretResponse {
	this := AgentRevokeSecretResponse{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *AgentRevokeSecretResponse) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *AgentRevokeSecretResponse) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *AgentRevokeSecretResponse) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetClientId returns the ClientId field value
func (o *AgentRevokeSecretResponse) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AgentRevokeSecretResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AgentRevokeSecretResponse) SetClientId(v string) {
	o.ClientId = v
}

// GetStatus returns the Status field value
func (o *AgentRevokeSecretResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentRevokeSecretResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentRevokeSecretResponse) SetStatus(v string) {
	o.Status = v
}

// GetWorkloadRefreshWarning returns the WorkloadRefreshWarning field value if set, zero value otherwise.
func (o *AgentRevokeSecretResponse) GetWorkloadRefreshWarning() string {
	if o == nil || IsNil(o.WorkloadRefreshWarning) {
		var ret string
		return ret
	}
	return *o.WorkloadRefreshWarning
}

// GetWorkloadRefreshWarningOk returns a tuple with the WorkloadRefreshWarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRevokeSecretResponse) GetWorkloadRefreshWarningOk() (*string, bool) {
	if o == nil || IsNil(o.WorkloadRefreshWarning) {
		return nil, false
	}
	return o.WorkloadRefreshWarning, true
}

// HasWorkloadRefreshWarning returns a boolean if a field has been set.
func (o *AgentRevokeSecretResponse) HasWorkloadRefreshWarning() bool {
	if o != nil && !IsNil(o.WorkloadRefreshWarning) {
		return true
	}

	return false
}

// SetWorkloadRefreshWarning gets a reference to the given string and assigns it to the WorkloadRefreshWarning field.
func (o *AgentRevokeSecretResponse) SetWorkloadRefreshWarning(v string) {
	o.WorkloadRefreshWarning = &v
}

func (o AgentRevokeSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRevokeSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	toSerialize["clientId"] = o.ClientId
	toSerialize["status"] = o.Status
	if !IsNil(o.WorkloadRefreshWarning) {
		toSerialize["workloadRefreshWarning"] = o.WorkloadRefreshWarning
	}
	return toSerialize, nil
}

type NullableAgentRevokeSecretResponse struct {
	value *AgentRevokeSecretResponse
	isSet bool
}

func (v NullableAgentRevokeSecretResponse) Get() *AgentRevokeSecretResponse {
	return v.value
}

func (v *NullableAgentRevokeSecretResponse) Set(val *AgentRevokeSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRevokeSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRevokeSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRevokeSecretResponse(val *AgentRevokeSecretResponse) *NullableAgentRevokeSecretResponse {
	return &NullableAgentRevokeSecretResponse{value: val, isSet: true}
}

func (v NullableAgentRevokeSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRevokeSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
