/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ScopeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScopeListResponse{}

// ScopeListResponse struct for ScopeListResponse
type ScopeListResponse struct {
	Scopes []ScopeResponse `json:"scopes"`
}

// NewScopeListResponse instantiates a new ScopeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeListResponse(scopes []ScopeResponse) *ScopeListResponse {
	this := ScopeListResponse{}
	this.Scopes = scopes
	return &this
}

// NewScopeListResponseWithDefaults instantiates a new ScopeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeListResponseWithDefaults() *ScopeListResponse {
	this := ScopeListResponse{}
	return &this
}

// GetScopes returns the Scopes field value
func (o *ScopeListResponse) GetScopes() []ScopeResponse {
	if o == nil {
		var ret []ScopeResponse
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *ScopeListResponse) GetScopesOk() ([]ScopeResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *ScopeListResponse) SetScopes(v []ScopeResponse) {
	o.Scopes = v
}

func (o ScopeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScopeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scopes"] = o.Scopes
	return toSerialize, nil
}

type NullableScopeListResponse struct {
	value *ScopeListResponse
	isSet bool
}

func (v NullableScopeListResponse) Get() *ScopeListResponse {
	return v.value
}

func (v *NullableScopeListResponse) Set(val *ScopeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeListResponse(val *ScopeListResponse) *NullableScopeListResponse {
	return &NullableScopeListResponse{value: val, isSet: true}
}

func (v NullableScopeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
