/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityEnvironmentView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityEnvironmentView{}

// AgentIdentityEnvironmentView One environment's AgentID binding. This is a safe view that never includes a secret. For an externally hosted agent, use `POST .../identities` (regenerate) to obtain one.
type AgentIdentityEnvironmentView struct {
	// Environment this binding belongs to
	EnvironmentName string `json:"environmentName"`
	// Whether the agent runs on the platform (`internal`) or outside it (`external`)
	ProvisioningType string             `json:"provisioningType"`
	Status           AgentThunderStatus `json:"status"`
	// Thunder's own ID for this identity. This is different from `clientId`, which is the OAuth2 client ID. Empty until provisioning reaches Thunder.
	AgentId *string `json:"agentId,omitempty"`
	// OAuth2 client ID for this AgentID
	ClientId *string `json:"clientId,omitempty"`
	// Most recent provisioning error, if the last attempt failed
	LastError *string `json:"lastError,omitempty"`
	// Who requested this binding, kept for audit purposes only
	RequestedBy *string `json:"requestedBy,omitempty"`
}

// NewAgentIdentityEnvironmentView instantiates a new AgentIdentityEnvironmentView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityEnvironmentView(environmentName string, provisioningType string, status AgentThunderStatus) *AgentIdentityEnvironmentView {
	this := AgentIdentityEnvironmentView{}
	this.EnvironmentName = environmentName
	this.ProvisioningType = provisioningType
	this.Status = status
	return &this
}

// NewAgentIdentityEnvironmentViewWithDefaults instantiates a new AgentIdentityEnvironmentView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityEnvironmentViewWithDefaults() *AgentIdentityEnvironmentView {
	this := AgentIdentityEnvironmentView{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *AgentIdentityEnvironmentView) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *AgentIdentityEnvironmentView) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetProvisioningType returns the ProvisioningType field value
func (o *AgentIdentityEnvironmentView) GetProvisioningType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProvisioningType
}

// GetProvisioningTypeOk returns a tuple with the ProvisioningType field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetProvisioningTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProvisioningType, true
}

// SetProvisioningType sets field value
func (o *AgentIdentityEnvironmentView) SetProvisioningType(v string) {
	o.ProvisioningType = v
}

// GetStatus returns the Status field value
func (o *AgentIdentityEnvironmentView) GetStatus() AgentThunderStatus {
	if o == nil {
		var ret AgentThunderStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetStatusOk() (*AgentThunderStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentIdentityEnvironmentView) SetStatus(v AgentThunderStatus) {
	o.Status = v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *AgentIdentityEnvironmentView) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *AgentIdentityEnvironmentView) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *AgentIdentityEnvironmentView) SetAgentId(v string) {
	o.AgentId = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AgentIdentityEnvironmentView) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AgentIdentityEnvironmentView) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AgentIdentityEnvironmentView) SetClientId(v string) {
	o.ClientId = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *AgentIdentityEnvironmentView) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *AgentIdentityEnvironmentView) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *AgentIdentityEnvironmentView) SetLastError(v string) {
	o.LastError = &v
}

// GetRequestedBy returns the RequestedBy field value if set, zero value otherwise.
func (o *AgentIdentityEnvironmentView) GetRequestedBy() string {
	if o == nil || IsNil(o.RequestedBy) {
		var ret string
		return ret
	}
	return *o.RequestedBy
}

// GetRequestedByOk returns a tuple with the RequestedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityEnvironmentView) GetRequestedByOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedBy) {
		return nil, false
	}
	return o.RequestedBy, true
}

// HasRequestedBy returns a boolean if a field has been set.
func (o *AgentIdentityEnvironmentView) HasRequestedBy() bool {
	if o != nil && !IsNil(o.RequestedBy) {
		return true
	}

	return false
}

// SetRequestedBy gets a reference to the given string and assigns it to the RequestedBy field.
func (o *AgentIdentityEnvironmentView) SetRequestedBy(v string) {
	o.RequestedBy = &v
}

func (o AgentIdentityEnvironmentView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityEnvironmentView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	toSerialize["provisioningType"] = o.ProvisioningType
	toSerialize["status"] = o.Status
	if !IsNil(o.AgentId) {
		toSerialize["agentId"] = o.AgentId
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.LastError) {
		toSerialize["lastError"] = o.LastError
	}
	if !IsNil(o.RequestedBy) {
		toSerialize["requestedBy"] = o.RequestedBy
	}
	return toSerialize, nil
}

type NullableAgentIdentityEnvironmentView struct {
	value *AgentIdentityEnvironmentView
	isSet bool
}

func (v NullableAgentIdentityEnvironmentView) Get() *AgentIdentityEnvironmentView {
	return v.value
}

func (v *NullableAgentIdentityEnvironmentView) Set(val *AgentIdentityEnvironmentView) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityEnvironmentView) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityEnvironmentView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityEnvironmentView(val *AgentIdentityEnvironmentView) *NullableAgentIdentityEnvironmentView {
	return &NullableAgentIdentityEnvironmentView{value: val, isSet: true}
}

func (v NullableAgentIdentityEnvironmentView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityEnvironmentView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
