/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPToolScopeBinding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPToolScopeBinding{}

// MCPToolScopeBinding struct for MCPToolScopeBinding
type MCPToolScopeBinding struct {
	// Name of the MCP tool the scopes gate
	Tool string `json:"tool"`
	// Catalog scope names required to call the tool
	Scopes []string `json:"scopes"`
}

// NewMCPToolScopeBinding instantiates a new MCPToolScopeBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPToolScopeBinding(tool string, scopes []string) *MCPToolScopeBinding {
	this := MCPToolScopeBinding{}
	this.Tool = tool
	this.Scopes = scopes
	return &this
}

// NewMCPToolScopeBindingWithDefaults instantiates a new MCPToolScopeBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPToolScopeBindingWithDefaults() *MCPToolScopeBinding {
	this := MCPToolScopeBinding{}
	return &this
}

// GetTool returns the Tool field value
func (o *MCPToolScopeBinding) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *MCPToolScopeBinding) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *MCPToolScopeBinding) SetTool(v string) {
	o.Tool = v
}

// GetScopes returns the Scopes field value
func (o *MCPToolScopeBinding) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *MCPToolScopeBinding) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *MCPToolScopeBinding) SetScopes(v []string) {
	o.Scopes = v
}

func (o MCPToolScopeBinding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPToolScopeBinding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tool"] = o.Tool
	toSerialize["scopes"] = o.Scopes
	return toSerialize, nil
}

type NullableMCPToolScopeBinding struct {
	value *MCPToolScopeBinding
	isSet bool
}

func (v NullableMCPToolScopeBinding) Get() *MCPToolScopeBinding {
	return v.value
}

func (v *NullableMCPToolScopeBinding) Set(val *MCPToolScopeBinding) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPToolScopeBinding) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPToolScopeBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPToolScopeBinding(val *MCPToolScopeBinding) *NullableMCPToolScopeBinding {
	return &NullableMCPToolScopeBinding{value: val, isSet: true}
}

func (v NullableMCPToolScopeBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPToolScopeBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
