/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the ScopeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScopeResponse{}

// ScopeResponse struct for ScopeResponse
type ScopeResponse struct {
	Id          *string    `json:"id,omitempty"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	// Number of MCP proxy environment tool bindings referencing this scope
	BindingCount *int32 `json:"bindingCount,omitempty"`
}

// NewScopeResponse instantiates a new ScopeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeResponse(name string) *ScopeResponse {
	this := ScopeResponse{}
	this.Name = name
	return &this
}

// NewScopeResponseWithDefaults instantiates a new ScopeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeResponseWithDefaults() *ScopeResponse {
	this := ScopeResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ScopeResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ScopeResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ScopeResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *ScopeResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScopeResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScopeResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScopeResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScopeResponse) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ScopeResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ScopeResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ScopeResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ScopeResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ScopeResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ScopeResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetBindingCount returns the BindingCount field value if set, zero value otherwise.
func (o *ScopeResponse) GetBindingCount() int32 {
	if o == nil || IsNil(o.BindingCount) {
		var ret int32
		return ret
	}
	return *o.BindingCount
}

// GetBindingCountOk returns a tuple with the BindingCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResponse) GetBindingCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BindingCount) {
		return nil, false
	}
	return o.BindingCount, true
}

// HasBindingCount returns a boolean if a field has been set.
func (o *ScopeResponse) HasBindingCount() bool {
	if o != nil && !IsNil(o.BindingCount) {
		return true
	}

	return false
}

// SetBindingCount gets a reference to the given int32 and assigns it to the BindingCount field.
func (o *ScopeResponse) SetBindingCount(v int32) {
	o.BindingCount = &v
}

func (o ScopeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScopeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.BindingCount) {
		toSerialize["bindingCount"] = o.BindingCount
	}
	return toSerialize, nil
}

type NullableScopeResponse struct {
	value *ScopeResponse
	isSet bool
}

func (v NullableScopeResponse) Get() *ScopeResponse {
	return v.value
}

func (v *NullableScopeResponse) Set(val *ScopeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeResponse(val *ScopeResponse) *NullableScopeResponse {
	return &NullableScopeResponse{value: val, isSet: true}
}

func (v NullableScopeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
