/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the IdentitySecurity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentitySecurity{}

// IdentitySecurity Agent Identity security — callers present a JWT issued by the environment's IdP. v1 pins the issuer to the ThunderKeyManager key manager.
type IdentitySecurity struct {
	// Whether Agent Identity security is enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// NewIdentitySecurity instantiates a new IdentitySecurity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentitySecurity() *IdentitySecurity {
	this := IdentitySecurity{}
	return &this
}

// NewIdentitySecurityWithDefaults instantiates a new IdentitySecurity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentitySecurityWithDefaults() *IdentitySecurity {
	this := IdentitySecurity{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IdentitySecurity) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentitySecurity) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IdentitySecurity) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *IdentitySecurity) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o IdentitySecurity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentitySecurity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableIdentitySecurity struct {
	value *IdentitySecurity
	isSet bool
}

func (v NullableIdentitySecurity) Get() *IdentitySecurity {
	return v.value
}

func (v *NullableIdentitySecurity) Set(val *IdentitySecurity) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentitySecurity) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentitySecurity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentitySecurity(val *IdentitySecurity) *NullableIdentitySecurity {
	return &NullableIdentitySecurity{value: val, isSet: true}
}

func (v NullableIdentitySecurity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentitySecurity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
