/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MCPProxyEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPProxyEndpoint{}

// MCPProxyEndpoint One deployable endpoint of an MCP proxy. An endpoint carries the upstream (URL + auth), policies, capabilities, and security, and is deployed to one or more environments. Within a proxy an endpoint's id is unique and an environment maps to at most one endpoint.
type MCPProxyEndpoint struct {
	// Endpoint handle, unique within the parent proxy
	Id string `json:"id"`
	// Human-readable endpoint name
	Name         *string               `json:"name,omitempty"`
	Upstream     UpstreamConfig        `json:"upstream"`
	Policies     []MCPPolicy           `json:"policies,omitempty"`
	Capabilities *MCPProxyCapabilities `json:"capabilities,omitempty"`
	Security     *SecurityConfig       `json:"security,omitempty"`
	// Environments this endpoint is deployed to.
	Environments []MCPEndpointEnvironment `json:"environments,omitempty"`
}

// NewMCPProxyEndpoint instantiates a new MCPProxyEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPProxyEndpoint(id string, upstream UpstreamConfig) *MCPProxyEndpoint {
	this := MCPProxyEndpoint{}
	this.Id = id
	this.Upstream = upstream
	return &this
}

// NewMCPProxyEndpointWithDefaults instantiates a new MCPProxyEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPProxyEndpointWithDefaults() *MCPProxyEndpoint {
	this := MCPProxyEndpoint{}
	return &this
}

// GetId returns the Id field value
func (o *MCPProxyEndpoint) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MCPProxyEndpoint) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MCPProxyEndpoint) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MCPProxyEndpoint) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MCPProxyEndpoint) SetName(v string) {
	o.Name = &v
}

// GetUpstream returns the Upstream field value
func (o *MCPProxyEndpoint) GetUpstream() UpstreamConfig {
	if o == nil {
		var ret UpstreamConfig
		return ret
	}

	return o.Upstream
}

// GetUpstreamOk returns a tuple with the Upstream field value
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetUpstreamOk() (*UpstreamConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Upstream, true
}

// SetUpstream sets field value
func (o *MCPProxyEndpoint) SetUpstream(v UpstreamConfig) {
	o.Upstream = v
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *MCPProxyEndpoint) GetPolicies() []MCPPolicy {
	if o == nil || IsNil(o.Policies) {
		var ret []MCPPolicy
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetPoliciesOk() ([]MCPPolicy, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *MCPProxyEndpoint) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []MCPPolicy and assigns it to the Policies field.
func (o *MCPProxyEndpoint) SetPolicies(v []MCPPolicy) {
	o.Policies = v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *MCPProxyEndpoint) GetCapabilities() MCPProxyCapabilities {
	if o == nil || IsNil(o.Capabilities) {
		var ret MCPProxyCapabilities
		return ret
	}
	return *o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetCapabilitiesOk() (*MCPProxyCapabilities, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *MCPProxyEndpoint) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given MCPProxyCapabilities and assigns it to the Capabilities field.
func (o *MCPProxyEndpoint) SetCapabilities(v MCPProxyCapabilities) {
	o.Capabilities = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *MCPProxyEndpoint) GetSecurity() SecurityConfig {
	if o == nil || IsNil(o.Security) {
		var ret SecurityConfig
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetSecurityOk() (*SecurityConfig, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *MCPProxyEndpoint) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given SecurityConfig and assigns it to the Security field.
func (o *MCPProxyEndpoint) SetSecurity(v SecurityConfig) {
	o.Security = &v
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *MCPProxyEndpoint) GetEnvironments() []MCPEndpointEnvironment {
	if o == nil || IsNil(o.Environments) {
		var ret []MCPEndpointEnvironment
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPProxyEndpoint) GetEnvironmentsOk() ([]MCPEndpointEnvironment, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *MCPProxyEndpoint) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []MCPEndpointEnvironment and assigns it to the Environments field.
func (o *MCPProxyEndpoint) SetEnvironments(v []MCPEndpointEnvironment) {
	o.Environments = v
}

func (o MCPProxyEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPProxyEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["upstream"] = o.Upstream
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	return toSerialize, nil
}

type NullableMCPProxyEndpoint struct {
	value *MCPProxyEndpoint
	isSet bool
}

func (v NullableMCPProxyEndpoint) Get() *MCPProxyEndpoint {
	return v.value
}

func (v *NullableMCPProxyEndpoint) Set(val *MCPProxyEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPProxyEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPProxyEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPProxyEndpoint(val *MCPProxyEndpoint) *NullableMCPProxyEndpoint {
	return &NullableMCPProxyEndpoint{value: val, isSet: true}
}

func (v NullableMCPProxyEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPProxyEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
