/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentIdentityRoleAssignmentsResponseGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentIdentityRoleAssignmentsResponseGroupsInner{}

// AgentIdentityRoleAssignmentsResponseGroupsInner struct for AgentIdentityRoleAssignmentsResponseGroupsInner
type AgentIdentityRoleAssignmentsResponseGroupsInner struct {
	Id          string  `json:"id"`
	OuId        *string `json:"ouId,omitempty"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CreatedAt   *string `json:"createdAt,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

// NewAgentIdentityRoleAssignmentsResponseGroupsInner instantiates a new AgentIdentityRoleAssignmentsResponseGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentIdentityRoleAssignmentsResponseGroupsInner(id string, name string) *AgentIdentityRoleAssignmentsResponseGroupsInner {
	this := AgentIdentityRoleAssignmentsResponseGroupsInner{}
	this.Id = id
	this.Name = name
	return &this
}

// NewAgentIdentityRoleAssignmentsResponseGroupsInnerWithDefaults instantiates a new AgentIdentityRoleAssignmentsResponseGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentIdentityRoleAssignmentsResponseGroupsInnerWithDefaults() *AgentIdentityRoleAssignmentsResponseGroupsInner {
	this := AgentIdentityRoleAssignmentsResponseGroupsInner{}
	return &this
}

// GetId returns the Id field value
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetId(v string) {
	o.Id = v
}

// GetOuId returns the OuId field value if set, zero value otherwise.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetOuId() string {
	if o == nil || IsNil(o.OuId) {
		var ret string
		return ret
	}
	return *o.OuId
}

// GetOuIdOk returns a tuple with the OuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetOuIdOk() (*string, bool) {
	if o == nil || IsNil(o.OuId) {
		return nil, false
	}
	return o.OuId, true
}

// HasOuId returns a boolean if a field has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) HasOuId() bool {
	if o != nil && !IsNil(o.OuId) {
		return true
	}

	return false
}

// SetOuId gets a reference to the given string and assigns it to the OuId field.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetOuId(v string) {
	o.OuId = &v
}

// GetName returns the Name field value
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *AgentIdentityRoleAssignmentsResponseGroupsInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o AgentIdentityRoleAssignmentsResponseGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentIdentityRoleAssignmentsResponseGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.OuId) {
		toSerialize["ouId"] = o.OuId
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableAgentIdentityRoleAssignmentsResponseGroupsInner struct {
	value *AgentIdentityRoleAssignmentsResponseGroupsInner
	isSet bool
}

func (v NullableAgentIdentityRoleAssignmentsResponseGroupsInner) Get() *AgentIdentityRoleAssignmentsResponseGroupsInner {
	return v.value
}

func (v *NullableAgentIdentityRoleAssignmentsResponseGroupsInner) Set(val *AgentIdentityRoleAssignmentsResponseGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentIdentityRoleAssignmentsResponseGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentIdentityRoleAssignmentsResponseGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentIdentityRoleAssignmentsResponseGroupsInner(val *AgentIdentityRoleAssignmentsResponseGroupsInner) *NullableAgentIdentityRoleAssignmentsResponseGroupsInner {
	return &NullableAgentIdentityRoleAssignmentsResponseGroupsInner{value: val, isSet: true}
}

func (v NullableAgentIdentityRoleAssignmentsResponseGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentIdentityRoleAssignmentsResponseGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
