apiVersion: v2
name: wso2-amp-api-platform-gateway-extension
description: A Helm chart to deploy and auto-register the unified API Platform Gateway for the Agent Management Platform.
type: application
version: v0.15.0-rc7
appVersion: "v0.15.0-rc7"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-gateway
  - api-gateway

maintainers:
  - name: WSO2
    url: https://wso2.com
