// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// AgentLabelRepositoryMock is a mock implementation of repositories.AgentLabelRepository.
//
//	func TestSomethingThatUsesAgentLabelRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AgentLabelRepository
//		mockedAgentLabelRepository := &AgentLabelRepositoryMock{
//			DeleteAllByAgentFunc: func(ctx context.Context, ouID string, projectName string, agentName string) error {
//				panic("mock out the DeleteAllByAgent method")
//			},
//			GetFunc: func(ctx context.Context, ouID string, projectName string, agentName string) (*models.AgentLabel, error) {
//				panic("mock out the Get method")
//			},
//			ListByProjectFunc: func(ctx context.Context, ouID string, projectName string) ([]models.AgentLabel, error) {
//				panic("mock out the ListByProject method")
//			},
//			UpsertFunc: func(ctx context.Context, record *models.AgentLabel) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedAgentLabelRepository in code that requires repositories.AgentLabelRepository
//		// and then make assertions.
//
//	}
type AgentLabelRepositoryMock struct {
	// DeleteAllByAgentFunc mocks the DeleteAllByAgent method.
	DeleteAllByAgentFunc func(ctx context.Context, ouID string, projectName string, agentName string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, ouID string, projectName string, agentName string) (*models.AgentLabel, error)

	// ListByProjectFunc mocks the ListByProject method.
	ListByProjectFunc func(ctx context.Context, ouID string, projectName string) ([]models.AgentLabel, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, record *models.AgentLabel) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteAllByAgent holds details about calls to the DeleteAllByAgent method.
		DeleteAllByAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// ListByProject holds details about calls to the ListByProject method.
		ListByProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Record is the record argument value.
			Record *models.AgentLabel
		}
	}
	lockDeleteAllByAgent sync.RWMutex
	lockGet              sync.RWMutex
	lockListByProject    sync.RWMutex
	lockUpsert           sync.RWMutex
}

// DeleteAllByAgent calls DeleteAllByAgentFunc.
func (mock *AgentLabelRepositoryMock) DeleteAllByAgent(ctx context.Context, ouID string, projectName string, agentName string) error {
	if mock.DeleteAllByAgentFunc == nil {
		panic("AgentLabelRepositoryMock.DeleteAllByAgentFunc: method is nil but AgentLabelRepository.DeleteAllByAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}{
		Ctx:         ctx,
		OuID:        ouID,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockDeleteAllByAgent.Lock()
	mock.calls.DeleteAllByAgent = append(mock.calls.DeleteAllByAgent, callInfo)
	mock.lockDeleteAllByAgent.Unlock()
	return mock.DeleteAllByAgentFunc(ctx, ouID, projectName, agentName)
}

// DeleteAllByAgentCalls gets all the calls that were made to DeleteAllByAgent.
// Check the length with:
//
//	len(mockedAgentLabelRepository.DeleteAllByAgentCalls())
func (mock *AgentLabelRepositoryMock) DeleteAllByAgentCalls() []struct {
	Ctx         context.Context
	OuID        string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}
	mock.lockDeleteAllByAgent.RLock()
	calls = mock.calls.DeleteAllByAgent
	mock.lockDeleteAllByAgent.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *AgentLabelRepositoryMock) Get(ctx context.Context, ouID string, projectName string, agentName string) (*models.AgentLabel, error) {
	if mock.GetFunc == nil {
		panic("AgentLabelRepositoryMock.GetFunc: method is nil but AgentLabelRepository.Get was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}{
		Ctx:         ctx,
		OuID:        ouID,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, ouID, projectName, agentName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedAgentLabelRepository.GetCalls())
func (mock *AgentLabelRepositoryMock) GetCalls() []struct {
	Ctx         context.Context
	OuID        string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ListByProject calls ListByProjectFunc.
func (mock *AgentLabelRepositoryMock) ListByProject(ctx context.Context, ouID string, projectName string) ([]models.AgentLabel, error) {
	if mock.ListByProjectFunc == nil {
		panic("AgentLabelRepositoryMock.ListByProjectFunc: method is nil but AgentLabelRepository.ListByProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
	}{
		Ctx:         ctx,
		OuID:        ouID,
		ProjectName: projectName,
	}
	mock.lockListByProject.Lock()
	mock.calls.ListByProject = append(mock.calls.ListByProject, callInfo)
	mock.lockListByProject.Unlock()
	return mock.ListByProjectFunc(ctx, ouID, projectName)
}

// ListByProjectCalls gets all the calls that were made to ListByProject.
// Check the length with:
//
//	len(mockedAgentLabelRepository.ListByProjectCalls())
func (mock *AgentLabelRepositoryMock) ListByProjectCalls() []struct {
	Ctx         context.Context
	OuID        string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
	}
	mock.lockListByProject.RLock()
	calls = mock.calls.ListByProject
	mock.lockListByProject.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *AgentLabelRepositoryMock) Upsert(ctx context.Context, record *models.AgentLabel) error {
	if mock.UpsertFunc == nil {
		panic("AgentLabelRepositoryMock.UpsertFunc: method is nil but AgentLabelRepository.Upsert was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Record *models.AgentLabel
	}{
		Ctx:    ctx,
		Record: record,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, record)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedAgentLabelRepository.UpsertCalls())
func (mock *AgentLabelRepositoryMock) UpsertCalls() []struct {
	Ctx    context.Context
	Record *models.AgentLabel
} {
	var calls []struct {
		Ctx    context.Context
		Record *models.AgentLabel
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
