// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// EnvThunderSystemClientRepositoryMock is a mock implementation of repositories.EnvThunderSystemClientRepository.
//
//	func TestSomethingThatUsesEnvThunderSystemClientRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.EnvThunderSystemClientRepository
//		mockedEnvThunderSystemClientRepository := &EnvThunderSystemClientRepositoryMock{
//			DeleteFunc: func(ctx context.Context, ouID string, envName string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, ouID string, envName string) (*models.EnvThunderSystemClient, error) {
//				panic("mock out the Get method")
//			},
//			UpsertFunc: func(ctx context.Context, cred *models.EnvThunderSystemClient) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedEnvThunderSystemClientRepository in code that requires repositories.EnvThunderSystemClientRepository
//		// and then make assertions.
//
//	}
type EnvThunderSystemClientRepositoryMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, ouID string, envName string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, ouID string, envName string) (*models.EnvThunderSystemClient, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, cred *models.EnvThunderSystemClient) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cred is the cred argument value.
			Cred *models.EnvThunderSystemClient
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpsert sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *EnvThunderSystemClientRepositoryMock) Delete(ctx context.Context, ouID string, envName string) error {
	if mock.DeleteFunc == nil {
		panic("EnvThunderSystemClientRepositoryMock.DeleteFunc: method is nil but EnvThunderSystemClientRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}{
		Ctx:     ctx,
		OuID:    ouID,
		EnvName: envName,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, ouID, envName)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEnvThunderSystemClientRepository.DeleteCalls())
func (mock *EnvThunderSystemClientRepositoryMock) DeleteCalls() []struct {
	Ctx     context.Context
	OuID    string
	EnvName string
} {
	var calls []struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *EnvThunderSystemClientRepositoryMock) Get(ctx context.Context, ouID string, envName string) (*models.EnvThunderSystemClient, error) {
	if mock.GetFunc == nil {
		panic("EnvThunderSystemClientRepositoryMock.GetFunc: method is nil but EnvThunderSystemClientRepository.Get was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}{
		Ctx:     ctx,
		OuID:    ouID,
		EnvName: envName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, ouID, envName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedEnvThunderSystemClientRepository.GetCalls())
func (mock *EnvThunderSystemClientRepositoryMock) GetCalls() []struct {
	Ctx     context.Context
	OuID    string
	EnvName string
} {
	var calls []struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *EnvThunderSystemClientRepositoryMock) Upsert(ctx context.Context, cred *models.EnvThunderSystemClient) error {
	if mock.UpsertFunc == nil {
		panic("EnvThunderSystemClientRepositoryMock.UpsertFunc: method is nil but EnvThunderSystemClientRepository.Upsert was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Cred *models.EnvThunderSystemClient
	}{
		Ctx:  ctx,
		Cred: cred,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, cred)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedEnvThunderSystemClientRepository.UpsertCalls())
func (mock *EnvThunderSystemClientRepositoryMock) UpsertCalls() []struct {
	Ctx  context.Context
	Cred *models.EnvThunderSystemClient
} {
	var calls []struct {
		Ctx  context.Context
		Cred *models.EnvThunderSystemClient
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
