// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// LLMProxyRepositoryMock is a mock implementation of repositories.LLMProxyRepository.
//
//	func TestSomethingThatUsesLLMProxyRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.LLMProxyRepository
//		mockedLLMProxyRepository := &LLMProxyRepositoryMock{
//			CountFunc: func(ouID string) (int, error) {
//				panic("mock out the Count method")
//			},
//			CountByProjectFunc: func(ouID string, projectUUID string) (int, error) {
//				panic("mock out the CountByProject method")
//			},
//			CountByProviderFunc: func(ouID string, providerUUID string) (int, error) {
//				panic("mock out the CountByProvider method")
//			},
//			CreateFunc: func(p *models.LLMProxy, handle string, name string, version string, ouID string) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(proxyID string, ouID string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(proxyID string, ouID string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetByIDFunc: func(proxyID string, ouID string) (*models.LLMProxy, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByIDAndProjectFunc: func(proxyID string, ouID string, projectUUID string) (*models.LLMProxy, error) {
//				panic("mock out the GetByIDAndProject method")
//			},
//			ListFunc: func(ouID string, limit int, offset int) ([]*models.LLMProxy, error) {
//				panic("mock out the List method")
//			},
//			ListByProjectFunc: func(ouID string, projectUUID string, limit int, offset int) ([]*models.LLMProxy, error) {
//				panic("mock out the ListByProject method")
//			},
//			ListByProviderFunc: func(ouID string, providerUUID string, limit int, offset int) ([]*models.LLMProxy, error) {
//				panic("mock out the ListByProvider method")
//			},
//			UpdateFunc: func(p *models.LLMProxy, handle string, ouID string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedLLMProxyRepository in code that requires repositories.LLMProxyRepository
//		// and then make assertions.
//
//	}
type LLMProxyRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ouID string) (int, error)

	// CountByProjectFunc mocks the CountByProject method.
	CountByProjectFunc func(ouID string, projectUUID string) (int, error)

	// CountByProviderFunc mocks the CountByProvider method.
	CountByProviderFunc func(ouID string, providerUUID string) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(p *models.LLMProxy, handle string, name string, version string, ouID string) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(proxyID string, ouID string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(proxyID string, ouID string) (bool, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(proxyID string, ouID string) (*models.LLMProxy, error)

	// GetByIDAndProjectFunc mocks the GetByIDAndProject method.
	GetByIDAndProjectFunc func(proxyID string, ouID string, projectUUID string) (*models.LLMProxy, error)

	// ListFunc mocks the List method.
	ListFunc func(ouID string, limit int, offset int) ([]*models.LLMProxy, error)

	// ListByProjectFunc mocks the ListByProject method.
	ListByProjectFunc func(ouID string, projectUUID string, limit int, offset int) ([]*models.LLMProxy, error)

	// ListByProviderFunc mocks the ListByProvider method.
	ListByProviderFunc func(ouID string, providerUUID string, limit int, offset int) ([]*models.LLMProxy, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(p *models.LLMProxy, handle string, ouID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// OuID is the ouID argument value.
			OuID string
		}
		// CountByProject holds details about calls to the CountByProject method.
		CountByProject []struct {
			// OuID is the ouID argument value.
			OuID string
			// ProjectUUID is the projectUUID argument value.
			ProjectUUID string
		}
		// CountByProvider holds details about calls to the CountByProvider method.
		CountByProvider []struct {
			// OuID is the ouID argument value.
			OuID string
			// ProviderUUID is the providerUUID argument value.
			ProviderUUID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// P is the p argument value.
			P *models.LLMProxy
			// Handle is the handle argument value.
			Handle string
			// Name is the name argument value.
			Name string
			// Version is the version argument value.
			Version string
			// OuID is the ouID argument value.
			OuID string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ProxyID is the proxyID argument value.
			ProxyID string
			// OuID is the ouID argument value.
			OuID string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// ProxyID is the proxyID argument value.
			ProxyID string
			// OuID is the ouID argument value.
			OuID string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// ProxyID is the proxyID argument value.
			ProxyID string
			// OuID is the ouID argument value.
			OuID string
		}
		// GetByIDAndProject holds details about calls to the GetByIDAndProject method.
		GetByIDAndProject []struct {
			// ProxyID is the proxyID argument value.
			ProxyID string
			// OuID is the ouID argument value.
			OuID string
			// ProjectUUID is the projectUUID argument value.
			ProjectUUID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// OuID is the ouID argument value.
			OuID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByProject holds details about calls to the ListByProject method.
		ListByProject []struct {
			// OuID is the ouID argument value.
			OuID string
			// ProjectUUID is the projectUUID argument value.
			ProjectUUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByProvider holds details about calls to the ListByProvider method.
		ListByProvider []struct {
			// OuID is the ouID argument value.
			OuID string
			// ProviderUUID is the providerUUID argument value.
			ProviderUUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// P is the p argument value.
			P *models.LLMProxy
			// Handle is the handle argument value.
			Handle string
			// OuID is the ouID argument value.
			OuID string
		}
	}
	lockCount             sync.RWMutex
	lockCountByProject    sync.RWMutex
	lockCountByProvider   sync.RWMutex
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockExists            sync.RWMutex
	lockGetByID           sync.RWMutex
	lockGetByIDAndProject sync.RWMutex
	lockList              sync.RWMutex
	lockListByProject     sync.RWMutex
	lockListByProvider    sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Count calls CountFunc.
func (mock *LLMProxyRepositoryMock) Count(ouID string) (int, error) {
	if mock.CountFunc == nil {
		panic("LLMProxyRepositoryMock.CountFunc: method is nil but LLMProxyRepository.Count was just called")
	}
	callInfo := struct {
		OuID string
	}{
		OuID: ouID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ouID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedLLMProxyRepository.CountCalls())
func (mock *LLMProxyRepositoryMock) CountCalls() []struct {
	OuID string
} {
	var calls []struct {
		OuID string
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// CountByProject calls CountByProjectFunc.
func (mock *LLMProxyRepositoryMock) CountByProject(ouID string, projectUUID string) (int, error) {
	if mock.CountByProjectFunc == nil {
		panic("LLMProxyRepositoryMock.CountByProjectFunc: method is nil but LLMProxyRepository.CountByProject was just called")
	}
	callInfo := struct {
		OuID        string
		ProjectUUID string
	}{
		OuID:        ouID,
		ProjectUUID: projectUUID,
	}
	mock.lockCountByProject.Lock()
	mock.calls.CountByProject = append(mock.calls.CountByProject, callInfo)
	mock.lockCountByProject.Unlock()
	return mock.CountByProjectFunc(ouID, projectUUID)
}

// CountByProjectCalls gets all the calls that were made to CountByProject.
// Check the length with:
//
//	len(mockedLLMProxyRepository.CountByProjectCalls())
func (mock *LLMProxyRepositoryMock) CountByProjectCalls() []struct {
	OuID        string
	ProjectUUID string
} {
	var calls []struct {
		OuID        string
		ProjectUUID string
	}
	mock.lockCountByProject.RLock()
	calls = mock.calls.CountByProject
	mock.lockCountByProject.RUnlock()
	return calls
}

// CountByProvider calls CountByProviderFunc.
func (mock *LLMProxyRepositoryMock) CountByProvider(ouID string, providerUUID string) (int, error) {
	if mock.CountByProviderFunc == nil {
		panic("LLMProxyRepositoryMock.CountByProviderFunc: method is nil but LLMProxyRepository.CountByProvider was just called")
	}
	callInfo := struct {
		OuID         string
		ProviderUUID string
	}{
		OuID:         ouID,
		ProviderUUID: providerUUID,
	}
	mock.lockCountByProvider.Lock()
	mock.calls.CountByProvider = append(mock.calls.CountByProvider, callInfo)
	mock.lockCountByProvider.Unlock()
	return mock.CountByProviderFunc(ouID, providerUUID)
}

// CountByProviderCalls gets all the calls that were made to CountByProvider.
// Check the length with:
//
//	len(mockedLLMProxyRepository.CountByProviderCalls())
func (mock *LLMProxyRepositoryMock) CountByProviderCalls() []struct {
	OuID         string
	ProviderUUID string
} {
	var calls []struct {
		OuID         string
		ProviderUUID string
	}
	mock.lockCountByProvider.RLock()
	calls = mock.calls.CountByProvider
	mock.lockCountByProvider.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *LLMProxyRepositoryMock) Create(p *models.LLMProxy, handle string, name string, version string, ouID string) error {
	if mock.CreateFunc == nil {
		panic("LLMProxyRepositoryMock.CreateFunc: method is nil but LLMProxyRepository.Create was just called")
	}
	callInfo := struct {
		P       *models.LLMProxy
		Handle  string
		Name    string
		Version string
		OuID    string
	}{
		P:       p,
		Handle:  handle,
		Name:    name,
		Version: version,
		OuID:    ouID,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(p, handle, name, version, ouID)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedLLMProxyRepository.CreateCalls())
func (mock *LLMProxyRepositoryMock) CreateCalls() []struct {
	P       *models.LLMProxy
	Handle  string
	Name    string
	Version string
	OuID    string
} {
	var calls []struct {
		P       *models.LLMProxy
		Handle  string
		Name    string
		Version string
		OuID    string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *LLMProxyRepositoryMock) Delete(proxyID string, ouID string) error {
	if mock.DeleteFunc == nil {
		panic("LLMProxyRepositoryMock.DeleteFunc: method is nil but LLMProxyRepository.Delete was just called")
	}
	callInfo := struct {
		ProxyID string
		OuID    string
	}{
		ProxyID: proxyID,
		OuID:    ouID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(proxyID, ouID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedLLMProxyRepository.DeleteCalls())
func (mock *LLMProxyRepositoryMock) DeleteCalls() []struct {
	ProxyID string
	OuID    string
} {
	var calls []struct {
		ProxyID string
		OuID    string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *LLMProxyRepositoryMock) Exists(proxyID string, ouID string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("LLMProxyRepositoryMock.ExistsFunc: method is nil but LLMProxyRepository.Exists was just called")
	}
	callInfo := struct {
		ProxyID string
		OuID    string
	}{
		ProxyID: proxyID,
		OuID:    ouID,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(proxyID, ouID)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedLLMProxyRepository.ExistsCalls())
func (mock *LLMProxyRepositoryMock) ExistsCalls() []struct {
	ProxyID string
	OuID    string
} {
	var calls []struct {
		ProxyID string
		OuID    string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *LLMProxyRepositoryMock) GetByID(proxyID string, ouID string) (*models.LLMProxy, error) {
	if mock.GetByIDFunc == nil {
		panic("LLMProxyRepositoryMock.GetByIDFunc: method is nil but LLMProxyRepository.GetByID was just called")
	}
	callInfo := struct {
		ProxyID string
		OuID    string
	}{
		ProxyID: proxyID,
		OuID:    ouID,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(proxyID, ouID)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedLLMProxyRepository.GetByIDCalls())
func (mock *LLMProxyRepositoryMock) GetByIDCalls() []struct {
	ProxyID string
	OuID    string
} {
	var calls []struct {
		ProxyID string
		OuID    string
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByIDAndProject calls GetByIDAndProjectFunc.
func (mock *LLMProxyRepositoryMock) GetByIDAndProject(proxyID string, ouID string, projectUUID string) (*models.LLMProxy, error) {
	if mock.GetByIDAndProjectFunc == nil {
		panic("LLMProxyRepositoryMock.GetByIDAndProjectFunc: method is nil but LLMProxyRepository.GetByIDAndProject was just called")
	}
	callInfo := struct {
		ProxyID     string
		OuID        string
		ProjectUUID string
	}{
		ProxyID:     proxyID,
		OuID:        ouID,
		ProjectUUID: projectUUID,
	}
	mock.lockGetByIDAndProject.Lock()
	mock.calls.GetByIDAndProject = append(mock.calls.GetByIDAndProject, callInfo)
	mock.lockGetByIDAndProject.Unlock()
	return mock.GetByIDAndProjectFunc(proxyID, ouID, projectUUID)
}

// GetByIDAndProjectCalls gets all the calls that were made to GetByIDAndProject.
// Check the length with:
//
//	len(mockedLLMProxyRepository.GetByIDAndProjectCalls())
func (mock *LLMProxyRepositoryMock) GetByIDAndProjectCalls() []struct {
	ProxyID     string
	OuID        string
	ProjectUUID string
} {
	var calls []struct {
		ProxyID     string
		OuID        string
		ProjectUUID string
	}
	mock.lockGetByIDAndProject.RLock()
	calls = mock.calls.GetByIDAndProject
	mock.lockGetByIDAndProject.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *LLMProxyRepositoryMock) List(ouID string, limit int, offset int) ([]*models.LLMProxy, error) {
	if mock.ListFunc == nil {
		panic("LLMProxyRepositoryMock.ListFunc: method is nil but LLMProxyRepository.List was just called")
	}
	callInfo := struct {
		OuID   string
		Limit  int
		Offset int
	}{
		OuID:   ouID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ouID, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedLLMProxyRepository.ListCalls())
func (mock *LLMProxyRepositoryMock) ListCalls() []struct {
	OuID   string
	Limit  int
	Offset int
} {
	var calls []struct {
		OuID   string
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByProject calls ListByProjectFunc.
func (mock *LLMProxyRepositoryMock) ListByProject(ouID string, projectUUID string, limit int, offset int) ([]*models.LLMProxy, error) {
	if mock.ListByProjectFunc == nil {
		panic("LLMProxyRepositoryMock.ListByProjectFunc: method is nil but LLMProxyRepository.ListByProject was just called")
	}
	callInfo := struct {
		OuID        string
		ProjectUUID string
		Limit       int
		Offset      int
	}{
		OuID:        ouID,
		ProjectUUID: projectUUID,
		Limit:       limit,
		Offset:      offset,
	}
	mock.lockListByProject.Lock()
	mock.calls.ListByProject = append(mock.calls.ListByProject, callInfo)
	mock.lockListByProject.Unlock()
	return mock.ListByProjectFunc(ouID, projectUUID, limit, offset)
}

// ListByProjectCalls gets all the calls that were made to ListByProject.
// Check the length with:
//
//	len(mockedLLMProxyRepository.ListByProjectCalls())
func (mock *LLMProxyRepositoryMock) ListByProjectCalls() []struct {
	OuID        string
	ProjectUUID string
	Limit       int
	Offset      int
} {
	var calls []struct {
		OuID        string
		ProjectUUID string
		Limit       int
		Offset      int
	}
	mock.lockListByProject.RLock()
	calls = mock.calls.ListByProject
	mock.lockListByProject.RUnlock()
	return calls
}

// ListByProvider calls ListByProviderFunc.
func (mock *LLMProxyRepositoryMock) ListByProvider(ouID string, providerUUID string, limit int, offset int) ([]*models.LLMProxy, error) {
	if mock.ListByProviderFunc == nil {
		panic("LLMProxyRepositoryMock.ListByProviderFunc: method is nil but LLMProxyRepository.ListByProvider was just called")
	}
	callInfo := struct {
		OuID         string
		ProviderUUID string
		Limit        int
		Offset       int
	}{
		OuID:         ouID,
		ProviderUUID: providerUUID,
		Limit:        limit,
		Offset:       offset,
	}
	mock.lockListByProvider.Lock()
	mock.calls.ListByProvider = append(mock.calls.ListByProvider, callInfo)
	mock.lockListByProvider.Unlock()
	return mock.ListByProviderFunc(ouID, providerUUID, limit, offset)
}

// ListByProviderCalls gets all the calls that were made to ListByProvider.
// Check the length with:
//
//	len(mockedLLMProxyRepository.ListByProviderCalls())
func (mock *LLMProxyRepositoryMock) ListByProviderCalls() []struct {
	OuID         string
	ProviderUUID string
	Limit        int
	Offset       int
} {
	var calls []struct {
		OuID         string
		ProviderUUID string
		Limit        int
		Offset       int
	}
	mock.lockListByProvider.RLock()
	calls = mock.calls.ListByProvider
	mock.lockListByProvider.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *LLMProxyRepositoryMock) Update(p *models.LLMProxy, handle string, ouID string) error {
	if mock.UpdateFunc == nil {
		panic("LLMProxyRepositoryMock.UpdateFunc: method is nil but LLMProxyRepository.Update was just called")
	}
	callInfo := struct {
		P      *models.LLMProxy
		Handle string
		OuID   string
	}{
		P:      p,
		Handle: handle,
		OuID:   ouID,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(p, handle, ouID)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedLLMProxyRepository.UpdateCalls())
func (mock *LLMProxyRepositoryMock) UpdateCalls() []struct {
	P      *models.LLMProxy
	Handle string
	OuID   string
} {
	var calls []struct {
		P      *models.LLMProxy
		Handle string
		OuID   string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
