apiVersion: v1
kind: ConfigMap
metadata:
  name: amp-opentelemetry-collector-config
  namespace: openchoreo-observability-plane 
data:
  relay: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true
    exporters:
      opensearch:
        http:
          auth:
            authenticator: basicauth/opensearch
          endpoint: https://opensearch.openchoreo-observability-plane.svc.cluster.local:9200
          tls:
            insecure_skip_verify: true
        sending_queue:
          num_consumers: 5
          queue_size: 1000
          sizer: items
        traces_index: "otel-traces"
        traces_index_time_format: "yyyy-MM-dd"

    extensions:
      basicauth/opensearch:
        client_auth: 
          username: admin
          password: ThisIsTheOpenSearchPassword1
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
  
    processors:
      resource:
        attributes:
          - key: openchoreo.dev/component-uid
            from_context: metadata.x-user-component
            action: upsert
          - key: openchoreo.dev/environment-uid
            from_context: metadata.x-user-environment
            action: upsert
          - key: openchoreo.dev/project-uid
            from_context: metadata.x-user-project
            action: upsert
          - key: openchoreo.dev/namespace
            from_context: metadata.x-user-namespace
            action: upsert

    service:
      extensions: [basicauth/opensearch, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource]
          exporters: [opensearch]
