apiVersion: v2
name: wso2-amp-ai-gateway-extension
description: A Helm chart to deploy and auto-register the WSO2 AI API Gateway for the Agent Management Platform.
type: application
version: v0.13.0-rc2
appVersion: "v0.13.0-rc2"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-gateway
  - api-gateway

maintainers:
  - name: WSO2
    url: https://wso2.com
