apiVersion: v1
kind: Secret
metadata:
  name: observer-idp-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  idpClientId: {{ .Values.amObserver.observer.idpClientId }}
  idpClientSecret: {{ .Values.amObserver.observer.idpClientSecret }}
