{{- if .Values.amObserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.amObserver.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: amp-observer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.amObserver.service.type }}
  selector:
    app: amp-observer
  ports:
    - name: http
      port: {{ .Values.amObserver.port }}
      targetPort: {{ .Values.amObserver.port }}
{{- end }}
